### ISSUE TITLE
Better Register Allocator

### ISSUE THREAD

**Issue by kobalicek** [asmjit/asmjit#117]
Everyone that has ever used compiler have probably noticed that the register allocator performs really bad job, especially when it comes to inner loops. I would like to write a new register allocator from scratch that will work a bit differently than the current one:
1. It needs to understand branches and identify loops, maybe even with some user annotations (like using something like `Label::kTypeLoop` hint when creating it). I think this is possible to do within liveness analysis, won't consume much time to create such graph
2. It should be able to allocate blocks of instructions without doing a linear scan. If it can't, it should first try to eliminate all live registers that are not used or only used for read (aka constants) in that block, if this doesn't help it should just divide the block into a smaller one and repeat the allocation. This would ensure that the allocation always converges.
3. Maybe some abstract interface for experimenting with register allocation would be also nice.
4. It should be faster than the current one, Compiler is around 8x slower than using pure Assembler.

Comments welcome.

**Comment by kirbyfan64** [comment]
This would be awesome!

**Comment by kobalicek** [comment]
The next-wip branch has some work that prepares the ground for the new register allocator.

**Comment by kobalicek** [comment]
I'm not sure I have implemented everything I wanted, but the current RA (next-wip) implements the following:

  - Liveness analysis based on basic blocks, almost by book
  - Liveness of virtual registers is represented by ranges
  - Binpacking that scans liveness ranges and tries to pack them
  - Ability to use memory instead of a register in case that the register is spilled
  - Ability to spill registers that don't have home register assigned at the end of use in each basic block

So for now I think it's pretty complete and the new RA is as fast as the old one, which is okay.

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
