### ISSUE TITLE
Ret instruction is not marked as Flow

### ISSUE THREAD

**Issue by alexjbest** [asmjit/asmjit#121]
On line [3929 of src/asmjit/x86/x86inst.cpp](https://github.com/kobalicek/asmjit/blob/6ad975b7faa23bd79f56405f334c5643e75e3edc/src/asmjit/x86/x86inst.cpp#L3929) the instruction ret has flags F(None)|F(Special).
According to the comment on [line 1587 of x86inst.h](https://github.com/kobalicek/asmjit/blob/6ad975b7faa23bd79f56405f334c5643e75e3edc/src/asmjit/x86/x86inst.h#L1587) ret should have the flow flag.

I would make a pull request but I'm scared of all the changes node makes to x86inst.cpp when I run the script myself and am unsure whether these are due to my node install being different :).

**Comment by kobalicek** [comment]
Hi, thanks!

I'm gonna look at this tomorrow, I think that you are basically right, just wanna check it out if it was just a mistake or there was some reason to not mark it as flow. I think that I forgot to run the node script last time I changed one instruction (it was a 3dnow instruction so it did no harm I'm sure :), normally when you run the script on master there should be no change.

**Comment by kobalicek** [comment]
This should be finally fixed by introducing a portable `asmjit::AnyInst::JumpType` enum, thanks for the suggestion
