### ISSUE TITLE
Compiler - merging `Reg` and `Var` operands

### ISSUE THREAD

**Issue by kobalicek** [asmjit/asmjit#133]
Anybody comfortable with the current Reg vs Var difference?

I thought about merging these two to make the API easier to follow and more consistent. However, this change would also enable to pass physical register to asmjit's Compiler by mistake. I'm personally in favor of removing the whole `Var` thingy, but if there is any other opinion I would listen.

**Comment by kirbyfan64** [comment]
I personally like it for the extra type safety, though I can see it being painful to maintain...

**Comment by kobalicek** [comment]
Yeah, the type-safety is the only advantage, but I still think that it would be pretty hard to misuse the API. I have time to think of it while doing other things, but my goals are to cleanup the API a bit.

**Comment by kobalicek** [comment]
I have changed that and it made everything simpler, still finalizing some details, but x86operand.cpp is maybe only 30% of size now :)

**Comment by kobalicek** [comment]
Closing, this already happened in asmjit:next branch.
