### ISSUE TITLE
Missing multi-byte `nop` instruction (with reg/mem operand)

### ISSUE THREAD

**Issue by kobalicek** [asmjit/asmjit#135]
AsmJit doesn't define a nop instruction, which bubbles to `asmtk`, which is unable to parse `nop`.

**Comment by kobalicek** [comment]
Okay, there is `nop`, but not multi-byte `nop`.

**Comment by Nekotekina** [comment]
Asmjit never emits LNOP when using align with kAlignCode argument?

**Comment by Nekotekina** [comment]
Found the bug, kHintOptimizedAlign is required. It says it's enabled by default, but it's not.
Also I noticed that it sets kMaxNopSize = 9 for some reason, but the max instruction length is 15. Longer LNOPs are made by multiplying 0x66 prefix, they should have better throughput according to data from https://github.com/InstLatx64/InstLatx64.

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
