### ISSUE TITLE
(branch next) MOVQ GPReg, Xmm encoded as MOVD (loosing REX prefix)

### ISSUE THREAD

**Issue by ultraknur** [asmjit/asmjit#137]
Hi.
It looks like the MOVQ GPReg, Xmm instruction is using kEncodingExtMovd as this is the same instruction just prefixed by REX. 

So the code:
`asm.movq((asmjit::x86::rax, asmjit::x86::xmm0);`
is encoded as:
`movd eax, xmm0`
instead of:
`movq rax, xmm0`

The problem is that in line:
**x86assembler.cpp:2464**
`opCode = commonData->getAltOpCode();`
it is loosing the REX prefix by using alternate opcode.

Possible fix for this issue is to change:
`opCode = commonData->getAltOpCode();`
to:
`opCode &= X86Inst::kOpCode_REX_Mask;`
`opCode |= commonData->getAltOpCode();`

**Comment by kobalicek** [comment]
Thanks, should be fixed by now!
