### ISSUE TITLE
asmjit::Assembler::resetLastError() is buggy

### ISSUE THREAD

**Issue by brightening-eyes** [asmjit/asmjit#139]
hello,
i'm writing a JIT compiler for AngelScript, and my code had call to asmjit::Assembler::resetLastError() function and that call was crashing my library (which i've tested on AngelScript sandbox), after i've deleted that call, everything worked fine
i was debugging it with gdb, i've placed breakpoints on my function to detect that crash, and the ResetLastError just crashed my app
it crashe's c runtime (the application has requested to terminate in unusual way), but after deleting that call, everything worked fine
maybe the call to getLastError() reset's the error?

**Comment by kobalicek** [comment]
`resetLastError` just calls `setLastError(kErrorOk)`. I think that you are hitting an assertion:

```
  // This is fatal, CodeEmitter can't set error without being attached to `CodeHolder`.
  ASMJIT_ASSERT(_code != nullptr);
```

**Comment by brightening-eyes** [comment]
CodeHolder is not pointer, and also getLastError() works, but resetLastError() make's the application crash

**Comment by kobalicek** [comment]
Header:

```c++
  CodeHolder* _code;                     //!< CodeHolder the CodeEmitter is attached to.
```

Source:
```c++
Error CodeEmitter::setLastError(Error error, const char* message) {
  // This is fatal, CodeEmitter can't set error without being attached to `CodeHolder`.
  ASMJIT_ASSERT(_code != nullptr);

  // Special case used to reset the last error.
  if (error == kErrorOk)  {
    _lastError = kErrorOk;
    _globalOptions &= ~kOptionMaybeFailureCase;
    return kErrorOk;
  }

  if (!message)
    message = DebugUtils::errorAsString(error);

  // Logging is skipped if the error is handled by `ErrorHandler`.
  ErrorHandler* handler = _code->_errorHandler;
  ASMJIT_TLOG("[ERROR] 0x%08u: %s%s\n",
    static_cast<unsigned int>(error), message, handler ? "" : " (ErrorHandler not attached)");

  if (handler && handler->handleError(error, message, this))
    return error;

  // The handler->handleError() function may throw an exception or longjmp()
  // to terminate the execution of `setLastError()`. This is the reason why
  // we have delayed changing the `_error` member until now.
  _lastError = error;

  return error;
}
```

If you call `resetLastError()` it's the same as `setLastError(kErrorOk)`. So the only reason it crashes is the `ASSERT` or if `this` is an invalid pointer.

**Comment by brightening-eyes** [comment]
hi again, can it caused by my assembler? (because that was pointer, although i've completely updated the code to use latest asmjit next branch)
anyway, i somehow know that had caused by that problematic code
