### ISSUE TITLE
ability to optimize jit code

### ISSUE THREAD

**Issue by brightening-eyes** [asmjit/asmjit#140]
hello,
it would be cool to be aible to optimize the code in asmjit (for example, PassManager in llvm if i'm not mistaken)
at leest, something that comes to my mind is, using function pointers, and add them to Runtime (and then runtime call's those functions to optimize the code

**Comment by kobalicek** [comment]
Next branch has passes concept (it doesn't have PassManager though), however, I don't plan to optimize at asm-level. Optimizations should happen at a higher level as asm-level has simply not enough information to make optimizations possible (except some minor optimizations after register allocation and such, but I guess this is not what you are talking about).

**Comment by brightening-eyes** [comment]
also for asm it should be possible, although for compiler construction, something like llvm's pass manager is needed

**Comment by kobalicek** [comment]
I'm closing, passes are part of next-wip atm, so this will continue there.
