### ISSUE TITLE
asmjit's documentation.

### ISSUE THREAD

**Issue by lilezek** [asmjit/asmjit#142]
I'm interested in this project but every documentation url I find is too old and its pointing to 404s.

Where can I find some help?

Thank you, 

lilEzek.

**Comment by kirbyfan64** [comment]
https://github.com/asmjit/asmjit/blob/master/README.md

https://github.com/asmjit/asmjit/blob/next/README.md

**Comment by lilezek** [comment]
No ofense, but I've already read those, and I still have some questions. 

For instance, is there any Compiler method for generating calls given a calling convention?

Lets say I want to make the recursive fibonacci implementation using something like this:

```c++
 // ... 
 X86Compiler c(&a);
 
 auto fibonacci = FuncBuilder1<int, int>(kCallConvHost); 
 auto LExit = c.newLabel();

 c.addFunc(fibonacci);

  // Create 32-bit variables (virtual registers) and assign some names to
  // them. Using variable names is not necessary, however, it can make
  // debugging easier.
  X86GpVar x = c.newInt32("x");
  X86GpVar r = c.newInt32("r");
 
  // Check if less than 2, fibonacci should return 1
  c.cmp(x, 2);
  c.jle(LExit);
 
 // Some instructions here...
 // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
 // Here is the question
 // How should I call fibonacci's function inside his own ASM code? 
 // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 c.call(y, fibonacci);

  // More instructions here...

  c.bind(LExit);
  // Tell asmjit to return `r`.
  c.ret(r);

  // Finalize the current function.
  c.endFunc();

  // Now the Compiler contains the whole function, but the code is not yet
  // generated. To tell the compiler to serialize the code to `Assembler`
  // `c.finalize()` has to be called. After finalization the `Compiler`
  // won't contain the code anymore and will be detached from the `Assembler`.
  c.finalize();
```

**Comment by kobalicek** [comment]
checking asmjit_test_x86.cpp should be better than any documentation as it always reflects the current state.

Every function you create has entry label so `getEntryLabel()` should get you the label you can call, sent from phone

**Comment by kobalicek** [comment]
Finally on desktop, check out `X86Test_CallRecursive` test in `asmjit_test_x86.cpp` - it tests recursive function call. Let me know if it works for you so I can close the issue.

**Comment by lilezek** [comment]
I totally forgot to read the tests. They contain enough code. Thank you.
