### ISSUE TITLE
Arm32: make error

### ISSUE THREAD

**Issue by svost** [asmjit/asmjit#143]
Hello. Is it my missconfig or realy error in code?
H/W: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G138745696275
$ uname -a
Linux nvcnode 3.8.13.30 #1 SMP PREEMPT Fri Sep 4 23:45:57 BRT 2015 armv7l armv7l armv7l GNU/Linux
$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 3394.86
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

    $ cmake ./CMakeLists.txt
    $ make
    cut
    [ 25%] Building CXX object CMakeFiles/asmjit.dir/src/asmjit/base/cpuinfo.cpp.o
    In file included from /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/../base/../base/globals.h:12:0,
                     from /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/../base/cpuinfo.h:12,
                     from /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/cpuinfo.cpp:11:
    /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/cpuinfo.cpp: In function ‘void asmjit::armDetectCpuInfoOnLinux(asmjit::CpuInfo*)’:
    /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/cpuinfo.cpp:166:72: error: ‘hwCapMapping2’ was not declared in this scope
       armDetectHWCaps(cpuInfo, AT_HWCAP2, hwCap2Mapping, ASMJIT_ARRAY_SIZE(hwCapMapping2));
                                                                            ^
    /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/../base/../base/../build.h:779:38: note: in definition of macro ‘ASMJIT_ARRAY_SIZE’
     #define ASMJIT_ARRAY_SIZE(x) (sizeof(x) / sizeof(x[0]))
                                      ^
    CMakeFiles/asmjit.dir/build.make:182: recipe for target 'CMakeFiles/asmjit.dir/src/asmjit/base/cpuinfo.cpp.o' failed
    make[2]: *** [CMakeFiles/asmjit.dir/src/asmjit/base/cpuinfo.cpp.o] Error 1

**Comment by kobalicek** [comment]
It seems broken, it should be `hwCap2Mapping` instead of `hwCapMapping2`.

However, this is just CPU detection, ARM backend is not ready so you can only emit X86/X64 code on ARM, is that desired?

**Comment by svost** [comment]
Thanks for reply, it is just an experiment. https://github.com/asmjit/asmjit/pull/144
Make complete with one warning message
`[ 12%] Building CXX object CMakeFiles/asmjit.dir/src/asmjit/base/hlstream.cpp.o
In file included from /mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/hlstream.cpp:11:0:
/mnt/nvcvol/home/novacoin/src/asmjit/src/asmjit/base/../base/hlstream.h:144:17: warning: inline function ‘asmjit::HLNode::HLNode(asmjit::Compiler*, uint32_t)’ used but never defined
   ASMJIT_INLINE HLNode(Compiler* compiler, uint32_t type) noexcept; // Defined-Later.
                 ^
[ 16%] Building CXX object CMakeFiles/asmjit.dir/src/asmjit/base/logger.cpp.o
`

**Comment by kobalicek** [comment]
Thanks, let me know if you find anything else.
