### ISSUE TITLE
String instructions in X86Compiler

### ISSUE THREAD

**Issue by ireyon** [asmjit/asmjit#145]
Hello,

in the old master branch, Compiler had convenience methods for string instructions, such as ```rep_movsq```, which automatically handled register reallocation as necessary. In the next branch, X86Compiler doesn't seem to have anything of the sort, only the explicit ```rep``` and ```stos``` which do not handle register reallocation.

My question: Is there currently any transparent or "proper" way to use these string instructions with X86Compiler? My current workaround consists of saving the ```rsi```, ```rdi``` and ```rcx``` registers manually, but I don't think this is a very elegant solution, especially when the target registers happen to be unused or even contain the correct operands already.

**Comment by kobalicek** [comment]
Hi, it should work, the explicit rep() prefix takes a register, so the following:

```c++
cc.rep(cnt).movs(x86::byte_ptr(dst), x86::byte_ptr(src));
```

should work, does it work for you?

**Comment by ireyon** [comment]
Yes, it works, thank you. That's rather nice, didn't know it was supposed to be used this way.

**Comment by kobalicek** [comment]
You are welcome, I'm glad it works for you :+1:
