### ISSUE TITLE
CodeBuilder usability

### ISSUE THREAD

**Issue by kobalicek** [asmjit/asmjit#146]
Temporary until the `CodeBuiler` is fully available in 'next' branch.

**Comment by kobalicek** [comment]
I tested it in my local branch and CodeBuilder seems to work, let me know if you are interested in testing it so I can create a new branch for testing.

**Comment by claytonhotson** [comment]
Indeed, yes.  I am happy to test for you!

**Comment by claytonhotson** [comment]
@kobalicek - Let me know if there is a branch I can test for you...

**Comment by kobalicek** [comment]
@claytonhotson Sorry for delay, you can try next-wip branch (but don't use CodeCompiler, it doesn't work yet)

**Comment by kobalicek** [comment]
I'm closing this as a working `CodeBuilder` is already in next-wip.
