### ISSUE TITLE
fully portable asmjit

### ISSUE THREAD

**Issue by DarkoreXOR** [asmjit/asmjit#148]
Can you make asmjit fully portable to other operating systems? With user-defined memory management, and other needed functions. I want to work with asmjit on Kolibri operating system, but it is impossible now. Thanks.

**Comment by kobalicek** [comment]
Without describing the problems you are having it is difficult for me to just guess what to do. Memory management can be overridden by defining `ASMJIT_ALLOC` and similar macros, for example.

**Comment by DarkoreXOR** [comment]
What API calls needed to correct work for asmjit? I have seen the Windows API to get different information about the CPU, but I do not know how important it is for asmjit. I just want compile asmjit for unknown operating system but I don't know how it will be work.

**Comment by kobalicek** [comment]
Yeah, if you use the `next` branch the only APIs that call OS specific APIs are in `osutils.cpp` and `cpuinfo.cpp` - these two files can be hacked to compile asmjit on any platform. Then there are some compile defined macros that detect OS and such, you would need to add support for your OS as well here.

The best would be to just try to compile it and fix errors as you go, asmjit is pretty portable in this regard.

**Comment by kobalicek** [comment]
Well, anything to add here before closing the issue?

I cannot port asmjit to OSes I don't have, so if you have ported asmjit to any OS that is not currently supported I would review it and add it to asmjit, thanks.

**Comment by kobalicek** [comment]
Anything before I close the issue?

Porting efforts are always welcome, but I cannot do this myself..

**Comment by hypeartist** [comment]
I've ported a previous (befor "next") version of asmjit to C#. ([AsmJit](https://github.com/hypeartist/AsmJit)). And now thinking of starting to port the "next" version.

**Comment by kobalicek** [comment]
@hypeartist It was redesigned a bit - CodeHolder and CodeEmitter concepts are new, remaining stuff didn't change much. The current master is transitional before merging next-wip, which is not ready (and doesn't change much, its main purpose is better register allocator).

Maybe the interface will change a bit in the future, mostly by adding support for sections and other features aot assemblers have, but overall I don't expect many breaking changes and I already designed the interface to support sections at API level.

**Comment by hypeartist** [comment]
@kobalicek Thanks. Then I'm to give it a shot. If you are interested - I will inform you when the port gets finished.

**Comment by kobalicek** [comment]
@hypeartist Let me also know if you think something can be designed better. I'm trying to keep the library small but featured and logical, but it's not like I don't do mistakes :)

**Comment by hypeartist** [comment]
@kobalicek Sure, it'd be better to wait for the next "next" if you are planning to make it public soon. 
As of the overall code design of asmjit - I promise to let you know about any design ideas that will come up. Where are you planning to update asmjit with wip changes?

**Comment by kobalicek** [comment]
@hypeartist I'm working on it right now, but I will probably only port the existing register allocator to next-wip and work on the new on later on. I want this as the next-wip CodeBuilder and CodeCompiler is better than in the current master.

I'm closing this as I don't see any bugs here..
