### ISSUE TITLE
Mixing virtual and real registers?

### ISSUE THREAD

**Issue by MichaelRFairhurst** [asmjit/asmjit#151]
It doesn't seem clearly stated in the docs anywhere, but is this allowed?

Specifically when using instructions which manipulate exact registers, is it possible to simply:

```
  ... do work with a bunch of virtual registers
  mov rax, virtual_reg1
  idiv virtual_reg
  ... do work with a bunch of virtual registers
  add rax, virtual_reg2
```

Is it possible to do this without the result from `idiv` in `rax` getting clobbered? Or any virtual regs getting clobbered by `idiv`'s manipulation of `rax'? Or do you have to manually use the stack to ensure register values don't get corrupted?

```
  push rax ; save rax in case its in use before its clobbered by idiv
  idiv virtual_reg1
  mov virtual_reg2, rax ; save rax to new virtual reg since it might conflict with prior virtual registers
  pop rax ; restore rax in case its in use by a virtual register
```

Or perhaps the latter code should be used and an optimizer should review the final asm for unnecessary pushes & pops to save registers that aren't in use?

**Comment by kobalicek** [comment]
You can only use phys registers outside of GP|MM|XYZ|K scope, using physical registers the way you described is basically undefined - it can work in some rare case but it will most probably fail.

All instructions that use implicit registers have explicit form, this is from idiv test:

```c++
    cc.addFunc(FuncSignature2<int, int, int>(CallConv::kIdHost));

    X86Gp a = cc.newInt32("a");
    X86Gp b = cc.newInt32("b");
    X86Gp dummy = cc.newInt32("dummy");

    cc.setArg(0, a);
    cc.setArg(1, b);

    cc.xor_(dummy, dummy);
    cc.idiv(dummy, a, b);

    cc.ret(a);
    cc.endFunc();
```

so use the explicit form instead.

**Comment by MichaelRFairhurst** [comment]
Still pretty new to assembly, didn't know how to use `idiv` until yesterday and didn't realize it had a three operand form. I will use that. Thanks for teaching me more about assembly!

And of course thank you for this awesome and well-documented project.


I guess in terms of my own question, its answered. Thank you!

**Comment by kobalicek** [comment]
You are welcome! You can also join gitter if you need help, you can also report there minor issues in examples and/or asmjit's documentation, the goals is to improve these.
