### ISSUE TITLE
strict-aliasing warnings when compiling with -Wall

### ISSUE THREAD

**Issue by eliben** [asmjit/asmjit#155]
Nice-looking project :) Trying to play with it a bit

When compiling asmjit with `-Wall` (gcc 4.8), I get strict-aliasing warnings in asmjit's headers:

```
././base/../base/../base/../base/func.h:307:57: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     reinterpret_cast<uint32_t*>(_passedOrder[kind].id)[0] = p0;
                                                         ^
```

etc.

Is this something worth addressing to get clean compiles with `-Wall`?

**Comment by kobalicek** [comment]
Thanks, I committed a fix for this one, are there any more?

**Comment by kobalicek** [comment]
And yeah, -Wall would be nice, I mean asmjit compiles fine on my dev machine, but I'm not using -Wall

**Comment by eliben** [comment]
Thanks for the fast response

There's one on lines 307/308 in `base/func.h` and also in `base/codeholder.h` on lines 284/285

**Comment by kobalicek** [comment]
Okay, I turned it on and fixed some warnings, but I'm not hitting the one in codeholder. I thought that reinterpret_cast<> from char* is fine and only other types are problematic.

**Comment by kobalicek** [comment]
Ok fixed. If you hit anything else let me know. Thanks!

**Comment by eliben** [comment]
I can confirm it compiles cleanly with `-Wall` now, thanks.
