### ISSUE TITLE
X86Assembler::lea doesn't seem to have an effect

### ISSUE THREAD

**Issue by eliben** [asmjit/asmjit#156]
I'm trying to load an address known to the host into a register in JITed code:

```
  X86Assembler a(&code);
  a.lea(x86::rax, x86::ptr(0x2030405060ull));
  a.ret();
```

When this JITed function is called, it produces 0. I checked the machine code emitted from the `CodeHolder` and I see only:

```
   0:	c3                   	retq   
```

Playing with other registers and values and intermixing more assembly calls, it seems that the `lea` method doesn't have an effect.

Am I missing something? I can't find documentation about loading 64-bit addresses into registers (as opposed to using register as pointers)

**Comment by kobalicek** [comment]
I think this should be more documented more clearly. Memory operands that use 64-bit address or displacement are unencodable, 32-bit sign extension is default, 32-bit zero extension is possible on x64.

Check out the example with minimum error handling:

```c++
int main(int argc, char* argv[]) {
  CodeInfo ci(ArchInfo::kTypeX64);
  CodeHolder code;
  code.init(ci);

  X86Assembler a(&code);
  a.lea(x86::rax, x86::ptr(0x2030405060ull));
  a.ret();

  if (a.isInErrorState())
    printf("ERROR: %s\n", DebugUtils::errorAsString(a.getLastError()));

  return 0;
}
```

Prints:

```
ERROR: Invalid use of 64-bit address
```

Error handling is important, check out 

  https://github.com/asmjit/asmjit#logging
  https://github.com/asmjit/asmjit#error-handling

These will be your friends during development.

**Comment by eliben** [comment]
Ah, my bad not checking the error.

However, 64-bit immediate moves are possible on x64 with the form of `mov` AT&T syntax calls `movabs`. If I disassemble a binary written this way:

```
  400078:	48 b8 90 80 70 60 50 	movabs $0x2030405060708090,%rax
  40007f:	40 30 20 
```

Is there a way to express this in asmjit?

**Comment by eliben** [comment]
Just for context, what I'm trying to do is make the JITed code manipulate data defined in the host code. So I want to hard-code the addresses of these data in immediates in the JITed code; I think this is a fairly common thing to do when JITing. Is there an alternative way in asmjit to do this that I'm missing?

[I could make the JITed code a function that takes these addresses as arguments, but this isn't always convenient]

**Comment by kobalicek** [comment]
Yeah, 64-bit moves are supported by `mov` - asmjit doesn't distinguish between `mov` and `movabs` as these are not separated in Intel Manual. Also in 64-bit mode `mov x[ax], ptr` and `mov ptr, x[ax]` can be used with 64-bit address as well.

**Comment by kobalicek** [comment]
Also, while still not official, the https://kobalicek.com/asmgrid/ can be used to explore most X86 instructions and all forms that asmjit supports as it's based on https://github.com/asmjit/asmdb project.

**Comment by eliben** [comment]
Ah, OK. So this works:

```
  a.mov(x86::rax, Imm(0x2030405060ull));
```

Thanks again for the quick response.
