### ISSUE TITLE
Emitting x64 syscalls?

### ISSUE THREAD

**Issue by eliben** [asmjit/asmjit#157]
I grepped through the documentation and source code *really* hard, but I see no mention of emitting syscalls using asmjit (`0x0F 0x05 ...` encoding) [http://www.felixcloutier.com/x86/SYSCALL.html]

Is it possible?

I'm using syscalls to call `read`, `write` etc. from code that doesn't link in the C runtime library.

**Comment by kobalicek** [comment]
They are missing, nobody until now noticed, I will add them

**Comment by kobalicek** [comment]
Commit aa154e3590b76f7d20fbcba8ab36b4d747e5a129 adds most missing instructions, check it out.

BTW: Syscalls and other recently added are not really supported by X86Compiler, I may add the support in a while, just wanted encoder working.

**Comment by eliben** [comment]
I'm not sure I see it in the commit you point to. Is there a new method added to `X86Assembler`?

**Comment by kobalicek** [comment]
Instructions that are available to asmjit are defined in x86inst.h/x86inst.cpp and made accessible by x86emitter.h.

Alternatively I'm also working on this project:

  https://kobalicek.com/asmgrid/

Which contains all instructions provided by asmdb, which asmjit uses to generate its instruction tables.

**Comment by eliben** [comment]
Thanks!
