### ISSUE TITLE
Code Entry Point? Sections?

### ISSUE THREAD

**Issue by quiret** [asmjit/asmjit#158]
I am currently writing a PE image merging tool that aims to embed a DLL into a EXE file. For that I have selected asmjit to generate a special, new entry point for the newly generated executable so that fixups can be applied across IAT thunk tables, etc.

So I create an asmjit::CodeHolder object, initialize it with the PE image architecture and create a asmjit::X86Assembler instance to generate machine code. After that I sync the asmjit::CodeHolder to commit changes. All is well until here.

Where the problem lies is the concept of sections inside asmjit. Why does every relocation have an ID of 0xFFFFFFFF for source and target section? I believe this mechanism is supposed to allow pointers across sections and I am ready to implement cross-section pointer adjustments (if really the case).

And where can I expect asmjit to output the first code into? I would like to have a parameter with an "entry point" for asmjit code that I can fetch, unless it is a strong guarrantee to be zero into ".text".

Thank you in advance,
Martin

**Comment by kobalicek** [comment]
Sections in asmjit are a work-in-progress feature. They are present, but asmjit can now only use the first section, which is created automatically as ".text". Data structures are section ready, but some features to use sections properly are missing.

The relocation id you are seeing means no relocation is needed.

What do you mean by entry point. Do you mean the final address of the code? If you mean that then check out `baseAddress`, which specifies the first physical byte the code will be relocated to. If you mean the offset of the code, then you can assume it's zero (basically the first instruction starts at zero, relative to `baseAddress`, to be precise).

BTW: You can join gitter and we can chat about the issue, I'm not sure I 100% understand

**Comment by quiret** [comment]
We talked in gitter how the source and target section indices of 0xFFFFFFFF is a bug if the relocation is valid. I am okay with the statement that code starts at first section at offset 0. Will watch asmjit if anything changes :)

**Comment by quiret** [comment]
I would like to note that asmjit::Label is the way to go for selecting assembly as "entry point" or generating multiple assembly routines and calling a specific one. See here:

'''
// Generate code.
asmjit::Label entryPointLabel;
{
    asmjit::X86Assembler x86_asm( &asmCodeHolder );

    entryPointLabel = x86_asm.newLabel();
 
    x86_asm.mov( asmjit::x86::eax, 0 );
    x86_asm.ret();
}
asmCodeHolder.sync();

const asmjit::LabelEntry *entryPointLabelEntry = asmCodeHolder.getLabelEntry( entryPointLabel );

// Use entryPointLabelEntry->getOffset() and entryPointLabelEntry->getSectionId() to call your assembler!
'''
