### ISSUE TITLE
X86 mov instruction does not generate relocation entry

### ISSUE THREAD

**Issue by quiret** [asmjit/asmjit#159]
http://imgur.com/a/ZjnYd

I am trying to generate X86 mov instructions that are relocatable in asmjit. For that I am using asmjit::X86Mem to read and write to fixed memory locations (RVAs in a PE image).

But the use of asmjit::X86Mem does not appear to cast relocation entries! I was under the assumption that all absolute offsets passed to assemblers in asmjit still had to be "finalized", even if it meant abs2abs relocation entry. abs2abs is important because it can be different during relocation (+moduleBaseAddress).

What am I supposed to do? Is this expected behavior?

**Comment by quiret** [comment]
Apparently asmjit does only generate relocation entry that are abs2rel and rel2abs (for example in call instruction). This is a problem because like that in X86 architecture you cannot create code in executables that are /DYNAMICBASE.

**Comment by kobalicek** [comment]
I don't think assemblers patch absolute addresses in general. You need to indicate every address for relocation. Some assemblers use `rel` or `wrt` or labels to indicate that, and then generate GOT and similar.

I mean there is no support for all of these in asmjit, but the framework is pretty solid and can handle all of these with a bit of hacking. I'm very open to having all of these features, but it really needs to have proper design and shouldn't break existing code.

**Comment by kobalicek** [comment]
I would like to close this issue, but I'm wondering, can you describe what is wrong in the current state?

Mov instruction won't generate a relocation entry, why it should generate it and under what circumstances? I'm open to changes if they are justified.
