### ISSUE TITLE
Problem with X86Compiler::ret() ?

### ISSUE THREAD

**Issue by thomaslee** [asmjit/asmjit#169]
Very new to asmjit & possible I'm doing something wrong, but something seems amiss here.

I have code like this:

```
JitRuntime rt;
CodeHolder code;
FileLogger logger(stdout);
code.init(rt.getCodeInfo());
code.setLogger(&logger);

X86Compiler cc(&code);

cc.push(x86::rbp);
cc.mov(x86::rbp, x86::rsp);
// do other stuff
cc.mov(x86::rax, imm(0));
cc.leave();
cc.ret();
cc.finalize();
```

No `ret` instruction appears in the assembly output from the logger and stepping through gdb I can confirm that the ret instruction is not in the emitted code either.

First I verified that we create the expected CBNodes, that the linked list looks good, etc. -- indeed we get a `CBNodeRet` in the call to `cc.ret()` and it seems to be properly appended to the compiler's instruction list.

Digging a little deeper, in the call to finalize() there is a call `X86Compiler::serialize(X86Assembler*)` that switches on `node_->getType()`. The ret node's type (`kNodeFuncExit`) is not handled & falls through to the `default` block which effectively ignores/drops the instruction. As a result, no `ret` is emitted.

To me this seems like a bug, but please do let me know if I'm doing something silly.

**Comment by kirbyfan64** [comment]
Aren't you supposed to call `cc.endFunc()` after `cc.ret()`?

**Comment by kobalicek** [comment]
@thomaslee You should just use `X86Assembler` in your case. `X86Compiler` provides register allocation so you never use physical registers directly, stack and function prolog/epilog is also generated automatically in that case.

**Comment by thomaslee** [comment]
Ah I see -- I think I mixed up example code. Thanks!
