### ISSUE TITLE
Dumping the generated code to a file

### ISSUE THREAD

**Issue by aktemur** [asmjit/asmjit#170]
Hi,

Is it possible to dump the dynamically generated code to a file, so that I can
1. use `objdump` to examine the contents of the file (for debugging purposes)
2. link that file with other code to execute offline.

Thanks.

**Comment by kirbyfan64** [comment]
Part 1 is already possible using just the built-in loggers, and IIRC part 2 is planned in asmtk: https://github.com/asmjit/asmtk/blob/master/README.md#todo

**Comment by quiret** [comment]
Possible? Kind of. Embedding code into PE executable file: https://osdn.net/projects/eirasmjit/scm/svn/blobs/head/shared/src/Relocation.cpp
Does not have to be assembler.

**Comment by aktemur** [comment]
Thanks. Logger facility will satisfy most of my needs.

**Comment by kobalicek** [comment]
Just to add, this functionality should go to `asmtk`. I currently don't need it so I don't focus on it, but I can help with implementation if anybody is interested in these.
