### ISSUE TITLE
Consider adding an opaque type and conversions to/from Operand types

### ISSUE THREAD

**Issue by dibyendumajumdar** [asmjit/asmjit#171]
Hi

One problem I am facing with asmjit is that the operand type is not available without including the whole of asmjit definitions. In my compiler there is a front end and a back end.  The front end should not have any knowledge of the back end but currently this is hard to achieve with asmjit.

I am therefore using something like this:

```
struct backend_data { uint64_t x[2]; };
```

The front end only knows above, the back end then does following:

```
struct backend_data wrap(Operand &op)
{
	struct backend_data d;
	static_assert(sizeof(struct backend_data) == sizeof(Operand),
		      "mismatch in operand and backend data type size");
	memcpy(&d, &op, sizeof d);
	return d;
}
X86Gp unwrap_register(struct backend_data &d)
{
	X86Gp op;
	memcpy(&op, &d, sizeof op);
	return op;
}
Label unwrap_label(struct backend_data &d)
{
	Label op;
	memcpy(&op, &d, sizeof op);
	return op;
}

X86Mem unwrap_ptr(struct backend_data &d)
{
	X86Mem op;
	memcpy(&op, &d, sizeof op);
	return op;
}
```

**Comment by kirbyfan64** [comment]
FWIW what you're doing is basically a C union, except even more unsafe because you're implicitly ignoring copy/move constructors.

```c++
union backend_data {
    X86Gp gp;
    Label lbl;
    X86Mem mem;
```

A better, more C++-style alternative would be to use a variant type:

https://github.com/mapbox/variant

Heck, if you're making a compiler, you could probably find even more use from Mach7:

https://github.com/solodon4/Mach7

**Comment by kobalicek** [comment]
Well Operand is basically a union already, no need to put to another one.

```c++
const X86Mem& asMem(const Operand& op) {
  return op.as<X86Mem>();
}
```

**Comment by kobalicek** [comment]
And BTW `struct backend_data { uint64_t x[2]; };` is completely fine. However, I would not `memcpy()` it but just cast it, as the data is compatible and also has the same alignment.

**Comment by kirbyfan64** [comment]
As a little extra thing, if you're trying to avoid any mention of AsmJit in your frontend, you could always use a `void*` pointer (which is horrible advice BTW):

```
void* my_data;
my_data = reinterpret_cast<void*>(new MyOperand);
```

or just plain old type erasure:

```
struct BackendData {};
struct AsmJitBackendData {
    Operand op;
};

// later...
std::unique_ptr<BackendData> ...
```

**Comment by dibyendumajumdar** [comment]
I should have mentioned that the front-end is C not C++ so I cannot use C++ types anyway in the front-end.

**Comment by kirbyfan64** [comment]
Then just use the `void*` pointer and watch out for memory management.

**Comment by dibyendumajumdar** [comment]
I don't think using void * and memory allocation is viable. The current approach I have works fine, but I think it is better if asmjit supplies an abstract type that is compatible with C - and provides conversions from/to this type. It will also help if in future you wanted to provide a C API.

**Comment by kobalicek** [comment]
Well I never thought about providing a C API for asmjit, I mean asmjit really takes advantage of C++, for intrinsics, RIAA, etc... C API would really be pain to develop and maintain. If you look at JIT assemblers for C it's mostly macro-based, I never wanted to go this way.

**Comment by dibyendumajumdar** [comment]
Sure I understand your reasons for writing in C++. There is no need to provide a C API if you don't want to - but it does make your library more available to other projects as C API can be used anywhere, even with other languages. As for macros, you seem to be using them as well :-) In fact I found it hard to figure out the API because its all macro based.

**Comment by kobalicek** [comment]
Well but I use them to generate some boilerplate, macros are not part of public API (except for some build configs and such)

**Comment by kobalicek** [comment]
Well, my point was, that providing bindings to other languages is possible, but it's not good idea to make C API and bind that, it's better to make high quality bindings that can use well what asmjit offers, which is operands, instruction database - for example you don't need to wrap each instruction as function, you can look it up if you use dynamically typed language, etc. AsmJit offers a lot of functionality that can be used to write nice bindings actually :)

**Comment by kobalicek** [comment]
But more docs is needed that's true, I would like to improve that.

**Comment by kobalicek** [comment]
Some closing words: 16 byte structure to represent operands is okay with asmjit - no dynamic memory allocation is needed. It will hardly change to something else as I consider 16 bytes per operand a maximum and it will never be possible to shrink it down to 8.
