### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by xxauroraxx** [asmjit/asmjit#174]
Error C2589 '(': illegal token on right side of '::' <project><path>\asmjit\base\zone.h	603	

Theres a lot more errors, but I have a feeling this is an issue on my side. MSVS 2017 and 2012

**Comment by kobalicek** [comment]
This is not asmjit's issue, something #defines `max` and/or `min` that conflicts with `std::max/min`, respectively. It's most probably from some Windows headers

**Comment by xxauroraxx** [comment]
Shouldn't `std::max` resolve that though because the scope is explicit?

**Comment by kobalicek** [comment]
It's not about the scope, some macro defines `min` like `#define min(a, b) ...`, and then expands wrongly. I'm trying to say that it's a problem of windows headers, so if you include them you should cleanup the mess before including asmjit, or include asmjit before these headers, or use `NOMINMAX`:

https://stackoverflow.com/questions/4913922/possible-problems-with-nominmax-on-visual-c
