### ISSUE TITLE
What is GPQ in asmjit means?

### ISSUE THREAD

**Issue by ghost** [asmjit/asmjit#181]
What is GPQ in asmjit means?

**Comment by kobalicek** [comment]
Hope this answers your question:

  * GP = General Purpose [register]
  * GPB = General purpose byte register (8-bit) (AL, AH, BL, BH, any 8-bit).
  * GBP-LO - General purpose low-word register (8-bit - AL, BL, CL, DL + REX regs like SIL, DIL, etc...)
  * GBP-HI - General purpose high-word register (8-bit - AH, BH, CH, DH)
  * GPW = General purpose word register (16-bit) (AX, BX, CX, ...) .
  * GPD = General purpose dword register (32-bit) (EAX, EBX, ECX, ...) .
  * GPQ = General purpose qword register (64-bit) (RAX, RBX, RCX, ...) .
