### ISSUE TITLE
Invalid opcode for vcvtss2si

### ISSUE THREAD

**Issue by wjakob** [asmjit/asmjit#182]
Hi,

while debugging some code generated using the latest version of asmjit (which is **great**), I noticed that  ``X86Compiler::vcvtss2si()`` incorrectly generates a ``vcvtsd2si`` instruction (I believe the entry in ``x86inst.cpp`` should start with ``F30F`` and not ``F20F``).

After fixing that on my end, I realized that there is another problem. The VEX-encoded instruction somehow does not work with a 64-bit output argument: asmjit always generates a conversion to a 32 bit register (i.e. ``vcvtsd2si eax, xmm0`` instead of ``vcvtsd2si rax, xmm0``). It works without problems for the non-VEX encoded SSE equivalent, so there are probably other incorrect entries in the table (whose encoding I don't fully grasp, hence this ticket instead of a PR).

Best,
Wenzel

**Comment by kobalicek** [comment]
Hi @wjakob, thanks for reporting this. It's a bug and I'm gonna fix it.

BTW: These bugs can be now quickly checked online here:

  https://kobalicek.com/fiddle-asmtk.html

**Comment by kobalicek** [comment]
Ok I fixed this in next-wip branch, will also backport to master.

**Comment by wjakob** [comment]
Fantastic, thank you. I really look forward to the new register allocator :)
