### ISSUE TITLE
Invalid opcode for vcvtsi2ss (reverse direction)

### ISSUE THREAD

**Issue by wjakob** [asmjit/asmjit#184]
Hi,

after fixing #182, it looks like there is another issue with the reverse direction: the following both generate the same opcodes, but they should be different.

```
vcvtsi2ss xmm0, xmm0, rax                   ; C5FA2AC0
vcvtsi2ss xmm0, xmm0, eax                   ; C5FA2AC0
```

Thanks,
Wenzel

**Comment by kobalicek** [comment]
DAMN! :+1: 

You are right of course, fix on the way
