### ISSUE TITLE
movabs rax, 1

### ISSUE THREAD

**Issue by neo85** [asmjit/asmjit#191]
Hey,  here is my problem.

a.mov(rax, 1);  -> mov eax, 1
i want it to generate mov rax, 1

is that possible?

**Comment by kobalicek** [comment]
Yes, this is a feature offered by asmjit to generate smaller code, to tell the assembler you really want the long version then this should work:

```c++
a.long_().mov(rax, 1);
```

This may change in the future to always generate the long variant when R register is used as it's controversial whether the assembler should optimize the code or not, but it would have to be discussed first.

**Comment by neo85** [comment]
Thx, it worked.
In my opinion, optimization should be disabled by default.

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
