### ISSUE TITLE
No logger::setOption() method

### ISSUE THREAD

**Issue by Zeex** [asmjit/asmjit#192]
Hi,

I'm upgrading from an old version of asmjit to this one, and one of the problems I encountered is that the Logger API has no `setOption` method anymore.  There are various options defined but it's not possible to set them.

I'm not sure if I'm missing something. How do you set logger options now? I used to do it like this:

```
    logger_->setIndentation("\t");
    logger_->setOption(asmjit::kLoggerOptionHexImmediate, true);
    logger_->setOption(asmjit::kLoggerOptionHexDisplacement, true);
```

**Comment by kobalicek** [comment]
I split `Logger` and `FormatOptions` into to classes. Something like this should work:

```c++
// This would work.
logger_->options().setFlags(asmjit::FormatOptions::kFlagHexImms);

// Or a shortcut (preferred)
logger_->addFlags(asmjit::FormatOptions::kFlagHexImms);
logger_->addFlags(asmjit::FormatOptions::kFlagHexOffsets);
```

The reason for this change: Some compiler tools can output into a `StringBuilder` without a logger and can still respect formatting options. I change the term `option` to `flags` to not confuse options with `FormatOptions`. Let me know if you have a better name for these or if you think it's okay.

Indentation is unfortunately not string anymore, it's a number of spaces instead. You can now set separately indentation of code, labels, and comments.
