### ISSUE TITLE
type-safe X86Compiler::call

### ISSUE THREAD

**Issue by yatli** [asmjit/asmjit#194]
Now that we already have variadic `FuncSignatureT`, one step further and we make type-safe calls to external functions.
For example:

```c++
// type-safe call
template <typename TRET, typename... TARGS>
CCFuncCall* safecall(X86Compiler &cc, TRET(TARGS...) func)
{
    return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>());
}

// later, use:
auto call = safecall(cc, memcpy);
call->setArg(0, ctx.cellPtr);
call->setArg(1, src);
call->setArg(2, imm(plan[0]));
```

**Comment by kobalicek** [comment]
Nice suggestion! I would definitely like to have something like this to be part of asmjit.

I would like to check one more thing - is it possible to get a calling convention of such a function? For example whether it's cdecl, stdcall, fastcall, or MS-specific vectorcall? That would be really nice to have, however, I'm not sure whether it's possible or not.

**Comment by yatli** [comment]
Interesting. I did some quick experiments:

```c++
// note, it does allow insertion of cc into the signature, which could probably be leveraged with std::enable_if or so.
template <class TRET, class... TARGS>
CCFuncCall* safecall(X86Compiler &cc, TRET (__cdecl* func)(TARGS...))
{
    return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>());
}

//but......
//the compiler gets away happily with:
void __fastcall foo()
{

}

void bar(void (__cdecl *target)())
{

}

void baz()
{
    bar(foo);
}
```

**Comment by yatli** [comment]
oops:

```c++
// type-safe call
template <class TRET, class... TARGS>
CCFuncCall* safecall(X86Compiler &cc, TRET (__cdecl* func)(TARGS...))
{
    return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>());
}

template <class TRET, class... TARGS>
CCFuncCall* safecall(X86Compiler &cc, TRET (__fastcall* func)(TARGS...))
{
    return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>());
}
```

results in `1>d:\git\graphengine\src\modules\graphengine.jit\graphengine.jit.native\jitroutines.cpp(74): error C2995: 'asmjit::CCFuncCall *safecall(asmjit::X86Compiler &,TRET (__cdecl *)(TARGS...))': function template has already been defined
` for MSVCv14.1

So the answer is probably "no".

**Comment by kobalicek** [comment]
I would probably close this as wont-fix, however, I really liked the idea of expressing function signatures with templates.

**Comment by DatBrick** [comment]
Functions with different calling conventions do actually have different types (at least on MSVC, GCC and Clang), but if you are on a platform such as x64 where they are actually the same thing, then they will be the same type. For example, this will compile on x64 but fail on x86:
```cpp
static_assert(std::is_same<void(*)(int, int), void(ASMJIT_STDCALL*)(int, int)>::value, "Different Types");
```

So you just need to ifdef out the overloads when they are not applicable. Something like:
```cpp
namespace asmjit
{
    template <typename TRET, typename... TARGS>
    CCFuncCall* safecall(X86Compiler &cc, TRET(*func)(TARGS...))
    {
        return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>(CallConv::kIdHost));
    }

#if ASMJIT_ARCH_X86
    template <typename TRET, typename... TARGS>
    CCFuncCall* safecall(X86Compiler &cc, TRET(ASMJIT_CDECL* func)(TARGS...))
    {
        return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>(CallConv::kIdHostCDecl));
    }

    template <typename TRET, typename... TARGS>
    CCFuncCall* safecall(X86Compiler &cc, TRET(ASMJIT_STDCALL* func)(TARGS...))
    {
        return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>(CallConv::kIdHostStdCall));
    }

    template <typename TRET, typename... TARGS>
    CCFuncCall* safecall(X86Compiler &cc, TRET(ASMJIT_FASTCALL* func)(TARGS...))
    {
        return cc.call(imm_ptr(func), FuncSignatureT<TRET, TARGS...>(CallConv::kIdHostFastCall));
    }
#endif
}
```

**Comment by kobalicek** [comment]
I think this should get closed. I would rather keep the current interface than trying to do something that may break on some compilers for whatever reason.

Any reason to not close this?

**Comment by yatli** [comment]
yeah this has been hanging there since forever. I'll close it now :)
