### ISSUE TITLE
VBLENDPS - minor issue

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#195]
Just noticed in logs:
```vblendps ymm1, ymm2, yword [rdx+rax], 4080; C4E36D0C0C02F0```
Immediate is 0xF0, but printed as 4080 for some reason.

**Comment by Nekotekina** [comment]
Got it, I passed 0xFF0 as an argument.

**Comment by kobalicek** [comment]
Hi @Nekotekina, so it's fine then? I wanted to check it out, but seems this is okay
