### ISSUE TITLE
class LabelByName have bug

### ISSUE THREAD

**Issue by flarejune** [asmjit/asmjit#199]
Member variable "hVal" never assigned.
in file "codeholder.cpp" at line 370
so,  CodeHolder::getLabelIdByName It's always wrong (return  0),

**Comment by kobalicek** [comment]
Please can you include a test-case which is failing for you? To use this functionality you must first create a named label, which is implemented here and sets the hash value:

  https://github.com/asmjit/asmjit/blob/master/src/asmjit/base/codeholder.cpp#L497

So I'm not sure if you are using the API right.

**Comment by flarejune** [comment]
[https://github.com/asmjit/asmjit/blob/master/src/asmjit/base/codeholder.cpp#L480](url)
LabelEntry* le = _namedLabels.get(LabelByName(name, nameLength, hVal));
This parameter "LabelByName" is a new instance,then,the hVal is 0 (There is no value assigned to hVal  in the constructor ).
on "_namedLabels.get" function, compare hashValue always 0;

**Comment by kobalicek** [comment]
I think I still need a test-case because names labels work for me and are used by `asmtk` as well.

**Comment by kobalicek** [comment]
Any luck with the test-case?
