### ISSUE TITLE
mov qword seems only loading the lower 4 bytes

### ISSUE THREAD

**Issue by hanayashiki** [asmjit/asmjit#205]
I try to pass argument on stack:
`mov qword [rcx+8], 2226861050160`
where 2226861050160 = `0x2067b430930`

while the callee get `0xXXXXXXXX7b430930`，the XXXXXXXX changes every time.
My full code is like
```
		X86Mem stack = compiler->newStack(16, STRUCT_ALIGN);
		X86Gp vRegPtrToStack = compiler->newGpq();
		compiler->lea(vRegPtrToStack, stack);
		compiler->mov(
			x86::ptr(vRegPtrToStack, 0, 4),
			imm(12345)
		);
		compiler->mov(
			x86::ptr(vRegPtrToStack, 8, 8),
			imm(2226861050160)
		);
...
               call->setArg(0, vRegPtrToStack);
```

and I tried to use `mov dword` twice, and it is fixed, but this is very troublesome.

I am using X64 with X86Compiler

Thanks in advance for checking this.

**Comment by hanayashiki** [comment]
Well I looked up the x86 manual and found in fact imm64 to mem is not supported. Sorry for that. Maybe something like `assertion fail` should be implemented for such illegal case?

**Comment by kobalicek** [comment]
Hey, sorry for late reply. This is currently resolved in next-wip branch - it returns error instead of silently truncating the value to 32-bit. I have no intentions to fix this is master branch atm as all the development happens in next-wip.
