### ISSUE TITLE
Multiple labels bug

### ISSUE THREAD

**Issue by ZQiu233** [asmjit/asmjit#206]
I tried to compile code:
a:
jmp a
and then I got correct bytes with the jmp jumps to a.

But for this:
a:
b:
jmp a
I got bytes "E9 04 04 04 04"
why?
I think they are equalvalent.

I had more test and found that it occurs when more than one label is existed.
I mean every "jmp" will get "E9 04 04 04 04".

**Comment by kobalicek** [comment]
Hello, can you share the code to reproduce the bug? When you see 04040404 it means the jump has not been relocated (the 04 just means that the relocation is 4 bytes long, you can also see 01 in short jumps).

**Comment by ZQiu233** [comment]
sorry for my late
Here's the code:

int main()
{

	CodeInfo codeinfo(ArchInfo::kTypeX86, 0, 0);
	CodeHolder code;
	code.init(codeinfo);
	X86Assembler a(&code);
	AsmParser p(&a);
	p.parse("a:\nb:\njmp a");
	code.sync();

	auto & buffer = code.getSectionEntry(0)->getBuffer();
	auto v = buffer.getData();
	size_t len = buffer.getLength();
	cout << buffer.getLength() << endl;
	for (size_t i = 0; i < len; i++)
	{
		printf("%.2x\n", v[i]);
	}
	return 0;
}
