### ISSUE TITLE
arm directory is missing

### ISSUE THREAD

**Issue by ronaaron** [asmjit/asmjit#207]
'arminst.h' and 'arminst.cpp' are not checked-in to git

**Comment by AndroDevcd** [comment]
Arm support for x86 is a work in progress and is not ready to be released yet. You can find the "experimental" code in the ``next-wip`` brahch. below I have included what i did to remedy this issue as i don't want to pull from the experimental branch:

```c++
#ifndef _ASMJIT_ARM_H
#define _ASMJIT_ARM_H

// [Dependencies]
//#include "./base.h"

//#include "./arm/armassembler.h"
//#include "./arm/armbuilder.h"
//#include "./arm/armcompiler.h"
//#include "./arm/arminst.h"
//#include "./arm/armoperand.h"

// [Guard]
#endif // _ASMJIT_ARM_H

```

As you can see i simply commented out the following. Hope that helps!

**Comment by ronaaron** [comment]
OK, thank you!

**Comment by kobalicek** [comment]
This will take long time before it's finalized guys, any volunteers are welcome of course :)

**Comment by kobalicek** [comment]
Duplicate of #74

**Comment by dtcrong** [comment]
> This will take long time before it's finalized guys, any volunteers are welcome of course :)

@kobalicek what's the progress here?  Do you have any plan for arm64 support?

**Comment by AndroDevcd** [comment]
@alohali please refer to https://github.com/asmjit/asmjit/issues/74
