### ISSUE TITLE
Cant get value of Label

### ISSUE THREAD

**Issue by AndroDevcd** [asmjit/asmjit#208]
I am trying to get the value of my label into a register I am using the X86Assembler and the "mov" instruction does not have a way to use a Label as an operand. I used godbolt to see what the following code does below me and it generated the following.

```c++
void* lli =   &&test;
    test:
        int x = 0;

// godbolt generates 
/**
.L2:
  mov QWORD PTR [rbp-16], OFFSET FLAT:.L3
.L3:
  mov DWORD PTR [rbp-20], 0
*/
```

below is a sample of what I am trying to do.
```c++
X86Assembler cc(&code);                  // Create and attach X86Compiler to `code`.
....some code
/*
* here i am attempting to perform a dynamic computed goto in the psuedo code representation
*
* int64* labels[];
*
* labels[0] = .L1;
* labels[1] = .L2;
* labels[3] = .L3;
* .. ect
*/
// labeles[] setting here
cc.comment("; setting label values", 22);
cc.mov(tmp, labelsPtr);                         // get a temporary ref to int64_t* labels
X86Mem labelIndex = qword_ptr(tmp);
X86Mem lbl;
for(int64_t i = 0; i < sz; i++) {
      lbl = X86Mem(labels[i], 0); // here is the problem Labels arent memory!!! I get the wrong value sent to my "ctx" register
      cc.mov(ctx, lbl);
      cc.mov(labelIndex, ctx);

      if((i + 1) < sz)                       // omit unnecessary add instruction
          cc.add(tmp, (int64_t )sizeof(int64_t));
}

```

The problem I am experiencing above is that Labels aren't memory they are hard values and when I reference the label it takes that label value and points that address to some random memory address which is wrong. I just simply need the label address. Please help

**Comment by kobalicek** [comment]
Hello, if I understand it correctly you want to get an address of a label into a register, is that right?

I would suggest something like this:

```c++
X86Assembler cc(&code);
Label L = cc.newLabel();

// Either use label as address, which would do:
cc.mov(reg, ptr(L)); // mov reg, [L]

// Or use lea to calculate the address.
cc.lea(reg, ptr(L)); // mov reg, addressof(L)

```

I replied quickly without testing the code, let me know if this way would work for you or this is not what you initially wanted to do.

**Comment by AndroDevcd** [comment]
H have tried ptr() i will try the Lea and see if that works tonight.
