### ISSUE TITLE
Convert assembly code to hex code? 

### ISSUE THREAD

**Issue by sesey** [asmjit/asmjit#209]
Thank you for the project.
How do I convert assembly code to hex code?

**Comment by kobalicek** [comment]
Do you mean how to convert the bytes asmjit outputs to hex output or how to get the bytes so you can convert them?

**Comment by sesey** [comment]
```
mov rax, rax
cmp rax, a
```

How do I get the above code to output hex?

**Comment by kobalicek** [comment]
There is already an example for exactly this:

https://github.com/asmjit/asmjit/tree/next-wip#more-about-codeinfo

**Comment by sesey** [comment]
I need to write the bo code as c #.
codeinfo and codeholder classes do not exist.

**Comment by kobalicek** [comment]
Hello, asmjit is a C++ library, I cannot help you with C#.
