### ISSUE TITLE
MOV to/from 64 bit variable/register to/from 32 bit location

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#21]
Something is wrong...

I use mov with 64-bit variable and 32-bit location (dword_ptr):

http://pastebin.com/UYUUNNJW

But it seems to be qword.

**Comment by kobalicek** [comment]
I think you are right in the end, if the memory size doesn't match the register size asmjit should at least report a warning. I faced the same scenario recently.

**Comment by kobalicek** [comment]
UPDATE: Asmjit will get an option to perform a much more strict validation, which should resolve all issues related to wrong operands and their sizes.

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
