### ISSUE TITLE
Cache bytecode for fast compilation 

### ISSUE THREAD

**Issue by AndroDevcd** [asmjit/asmjit#210]
I am writing a very extensive JIT compiler for a project. I was wondering is there a way to cache the bytecode in the X86Assembler bytecode after i compile it. And cache it in a file to be used later. Below i explain what I am trying to do:

```c++
...
X86Assembler cc(&code);

cc.mov(eax, 1);
...
void *x86Code = cc.bytecode;
File *fp = open("out.jitcache");
fp->write(x86Code);

// On next run of the program we do this
File *fp = open("out.jitcache");

If(fp) {
string data = fp->readAllText();
If(data.size() > 0)
cc.dumpBytes(data.c_str()); // this is esentially what i want to do can we "inject" bytecode an runtime so that i dont have to compile everytime compiling will take a long time
Else
    goto compile_bytecode;
}

```

I know that u can get the pointer to the physical bytecode in the assembler(the above code may not be 100% correct but u get the idea)

**Comment by kobalicek** [comment]
Well this very much depends on what you are compiling. If your output is something like a shader that doesn't have any links to pointers outside of that program then it would be pretty easy to do that, however, if your code accesses things outside then you would need to implement a light linker that would be able to create a linkable code, store it, and then load it and patch it so it works within the environment that loaded it.

A small example:

```x86
mov rax, @memcpy
call rax
```

If you compile something similar with asmjit and provide a RAW pointer to `memcpy` as provided by your C++ compiler then you cannot anyhow store the generated code as it would have hardcoded immediate to that address which doesn't have to stay the same next time you run the main application.

I would compare your problem to object files and linker that generates an executable.

**Comment by AndroDevcd** [comment]
Ah well that makes me a bit sad lol. But yes this does make sense as i do hold raw pointers to function like memcpy(). I guess i will have to stick to jit compile everytime at runtime then.

Thanks!
