### ISSUE TITLE
Some dynamic API to make instructions

### ISSUE THREAD

**Issue by hanayashiki** [asmjit/asmjit#211]
Hello, I wonder if it is better to be able to:
```
Operand op1, op2; 
...
cc->add(op1, op2);
```
This should work if the real type of op1 and op2 both match one of the `add` instr,
and if it doesn't match, this will use some 'mov' instr to make everything in the correct place.
Maybe virtual reg is suggested, but virtual regs are stored in the stack, but I hope to store them somewhere else :(

**Comment by kobalicek** [comment]
It's already possible with untyped API, but you would have to provide also instruction id - `cc->emit(id, op1, op2)`

I thought about providing additional API for people that only have operands, like `add_()`, but never actually started implementing it

**Comment by hanayashiki** [comment]
Thank you. I did not find this. Seems this save a lot of work!
