### ISSUE TITLE
Ambiguous behavior with vector pointers

### ISSUE THREAD

**Issue by JohnSully** [asmjit/asmjit#213]
assembler.emit(asmjit::X86Inst::kIdVpmulld, asmjit::x86::ymm0, asmjit::x86::ymm0, asmjit::Operand(asmjit::x86::ptr(displacement, 4)));

Emits a 256-bit vector op on ymm0.

However

assembler.emit(asmjit::X86Inst::kIdMovdqa, asmjit::Operand(asmjit::x86::ptr(displacement, 4)), asmjit::x86::ymm0);

Emits a 128-bit operation on xmm0.

Expected:  Either an error is triggered or the explicit register size should win.

**Comment by JohnSully** [comment]
The root of the issue is the use of movdqa instead of vmovdqa.  Still I think this should trigger an error rather than emit an SSE instruction and change ymm0 to xmm0 silently.

**Comment by kobalicek** [comment]
Hello, asmjit by default balances between performance and conformance by only checking register types when it's necessary for deciding about a correct encoding, so by default you get performance. However, it also provides a feature to turn on additional validation, which could be very handy for debugging:

```c++
// master - there is no API for this, however, you can turn it on this way:
assembler._globalOptions |= CodeEmitter::kOptionStrictValidation;

// next-wip
assembler.addEmitterOptions(BaseEmitter::kOptionStrictValidation);
```

When the strict validation option is enabled the assembler will validate each instruction against possible signatures first. There is a small database asmjit contains to make this possible. The database is also inspectible, but I focused on inspection more in next-wip branch, and there are still things to do.

**Comment by JohnSully** [comment]
Thanks I appreciate that approach.  I've enabled this flag in my debug builds and confirmed it does indeed flag on this error.
