### ISSUE TITLE
Question: How to get pointers to multiple functions?

### ISSUE THREAD

**Issue by Chlumsky** [asmjit/asmjit#214]
I found an example of having more than one function compiled here: https://github.com/asmjit/asmjit/blob/ab59e3518f8918a9185a49ab8bca321465462814/test/asmjit_test_x86_cc.cpp#L3274

However, it seems that only the first function added is then exposed by the function pointer. What if I need to be able to call either of the two functions from C++ code, which might also need to call one another, so they cannot be compiled separetely?

Or is there no additional cost to calling by the generated function pointer as opposed to the label from `CCFunc`, so I should simply compile them separetely and use `call(imm_ptr(functionPtr), ...)`? What if the two functions recursively call each other? Then I can't have the second function's pointer when generating the first one.

Here is a minimal example I was testing this on: https://pastebin.com/LuucHf6C

Also, unrelated side question: Is it OK to use `X86Compiler` in a 64-bit program on Windows? Can anything go wrong, e.g. when calling a native function?

Thank you.

**Comment by kobalicek** [comment]
Hi Victor,

I will try to explain first what is happening when you compile a function and then try to provide a possible solution. You are right that you only get the first function when compiling the code held by CodeHolder. Well, I would probably correct it to "pointer to the first byte of the code" as that's more precise.

The first problem here is that the memory manager allocates memory for both functions as a single continuous block (basically it allocates a single block for the whole content of CodeHolder to be precise), and only this block of memory can then be freed when you no longer need it (so it frees both functions at the same time). It's not possible to release a part of the block (it's similar to malloc/free behavior).

Now a bit of illustration - suppose this is a CodeHolder content, ABC are functions, 'x' is some code:

```
[AxxxxxxBxxxxxCxxx]
```

When you relocate this content you get a pointer to the first byte, which would be 'A'. However, if you created this code by Assembler or Compiler you can get 'B', 'C', or any label you created by offsetting 'A':

```c++
CodeHolder code;
// Your second function.
CCFunc* b = ...;

// After code-generation:
void* base = ...; // the start of the buffer, entry point of A.

// You can get its entry point like this:
Label bEntry = b->getLabel();
intptr_t bOffset = code.getLabelOffset(BEntry);

// And offset it to get B.
void* bPtr = (uint8_t*)base + bOffset;
```

If your only concern was to get a pointer to 'B' or any other function then this solution may work for you. You can use the same trick to call functions btw. If you need to call itself recursively, or a function which was not yet generated, but will be generated and part of the same CodeHolder scope then this is okay.

Depending on your needs it's possible to create a more complex solution. One solution could be to allocate a table of functions and dispatch your code dynamically by accessing the table. I'm not sure you would want to do that as it's complicated, but it could look like this:

```c++
void* functionTable[128];

uint32_t IndexOfA = 0;
uint32_t IndexOfB = 1;

// Compile functions - more like a pseudo-code here.
functionTable[0] = compileA();
functionTable[1] = compileB();

// And during compilation instead of using labels, you can dynamically dispatch the call:
X86Gp functionTable = c.newIntPtr();
c.mov(functionTable, imm_ptr(functionTable));

// Doesn't matter if the function exists as the call is 'virtual'.
CCFuncCall *call = c.call(ptr(functionTable, int(IndexOfA * sizeof(void*))), signature);
```

Depending on how many functions are flying at the same time this may not be a good idea at all as you might need to reallocate `functionTable` and then you would need a mechanism to either patch the existing code to point to a new table, or access a pointer to the table dynamically.

Well I probably wrote longer answer that I wanted :) But, I just wanted to say that asmjit is not a VM that would manage the memory for you, asmjit can only manage blocks of memory that always represent a continuous CodeHolder content (and this works as malloc/free basically). This means that anything more complex (like reference counting, or GC, etc) must be done by users and asmjit cannot help with that.

Let me know if you have more questions or suggestions.

**Comment by Chlumsky** [comment]
Thank you for the extensive explanation, it makes everything much clearer. I was able to use the shifted function pointer successfully. However, I didn't find the answer to two parts of my question. One was, whether or not there is any advantage to calling a function that is defined within the same `X86Compiler` as opposed to an arbitrary function pointer. I have done some basic benchmarking to determine this, and it seems that function calls are relatively expensive in general, but there is no difference between the two kinds.

The other one was the side question, that is, whether I can be sure that the "x86" in the class names also covers the x64 architecture, or if I need a separate `X64Compiler`. I know it's probably a stupid question, and it seems to be working just fine, but just for the peace of mind.

**Comment by kobalicek** [comment]
Sorry I missed the questions:

1. Relative vs absolute call - on modern machines this is probably very comparable, however, theoretically the relative call should be always faster and generally better for the CPU (if the target entry point is known in advance the CPU will start fetching instructions early and the call overhead should be minimal or close to zero - actually I would say that the call overhead today is almost always register save/restore and not the call instruction itself).

2. Asmjit's 'x86' covers both 32-bit and 64-bit architectures so you shouldn't worry about it. I would say that the best experience is generating code for 64-bit x86 as in 32-bit mode you exhaust registers quite fast (and asmjit is not LLVM to have a state of art register allocator).

BTW: There was a discussion on gitter some time back about a call overhead of simple functions. The problem is (in general) that the call is just fine, but saving and restoring registers is what generates the surrounding code that can get quite big sometimes. As a result I have added a lightweight calling convention to handle such cases (I guess LightCall or something like that), but it's not quite tested so I would not recommend this for general use.

**Comment by Chlumsky** [comment]
Alright, thanks.
