### ISSUE TITLE
Proper way to emulate .data section

### ISSUE THREAD

**Issue by JohnSully** [asmjit/asmjit#216]
I'm trying to simulate the equivalent of a .data section.  I've created my own Virtual Memory manager and ensured that the page is allocated within 4GB of the section where the JIT assembly will go.  However I'm having trouble figuring out the proper way to reference this and still have relocatable code (i.e. not passing hardcoded addresses to the assembler).

In the short term I've been using labels and .bind() after my code however because I want my code to be read only when executing this is not a suitable long term solution.  The .data variables need to be in a different page with different permissions.

How can I bind a label to a different page than my code?

**Comment by JohnSully** [comment]
I should also mention that while I could give the pointer an explicit address compilation will fail unless I also gurantee a start address for the code upfront.  I can't do that without knowing its size.  So what I'd like to do is promise that it will be somewhere within the 4GB limit for relative addresses as required by X86 - but not lock in a specific address until the end.

**Comment by JohnSully** [comment]
This is resolved by sections I think.  I'll let you be the arbiter on closing the issue, but I'm happy with the current solution.

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
