### ISSUE TITLE
Convert hex code to asmjit x86::Assembler/emiter ? 

### ISSUE THREAD

**Issue by or75** [asmjit/asmjit#218]
how to conver: "55 8B EC E8 02 00 00 00 EB 06 B8 05 00 00 00 C3 90 5D C2 04 00"

00401000 | push ebp
00401001 | mov ebp,esp
00401003 | call project1.40100A
00401008 | jmp project1.401010
0040100A | mov eax,0x5
0040100F | ret
00401010 | nop
00401011 | pop ebp
00401012 | ret 0x4 

to -> example (emiter(with Label support)):

x86::Assembler a(&code);
a.emit(x86::Inst::kIdPush, x86::ebp);
a.emit(x86::Inst::kIdMov, x86::ebp, x86::esp);
...
...

or use Assembler(with Label support):

x86::Assembler a(&code);
a.push(ebp);
a.mov(ebp, esp);

any ideas ?

**Comment by kobalicek** [comment]
You have to be more specific as I don't understand the problem yet

**Comment by or75** [comment]
if the code (function) is very large, it would be nice to add it in automatic mode, such as in asmtk and not manually )

**Comment by kobalicek** [comment]
Well I think you should elaborate a bit as I still don't understand what is the question or problem. You can of course use assembler or builder to create such code.

You can try it even online <https://kobalicek.com/fiddle-asmtk.html>:

Just paste:

```x86asm
push ebp
mov ebp,esp
call 0x40100A
jmp 0x401010
mov eax,0x5
ret
nop
pop ebp
ret 0x4
```

and set base address to `401000`.
