### ISSUE TITLE
Error generating x32 byte code

### ISSUE THREAD

**Issue by Vedaevolution** [asmjit/asmjit#224]
Dear community,
i believe i found a x32 byte generation error. Using the code below i'm generating bytecode. Instead of getting the expected result i get the wrong one.

        using namespace asmjit;
	using namespace asmjit::x86;            // Easier access to x86/x64 registers.

	CodeHolder code;                        // Create a CodeHolder.
	code.init(CodeInfo(ArchInfo::kTypeX32));
	X86Assembler a(&code);
	a.push(eax);
	a.push(eax);
	a.mov(eax, jumpAddress);
	a.mov(ptr(esp, 4), eax);
	a.pop(eax);
	a.ret();

	code.sync();   

	CodeBuffer& buf = code.getSectionEntry(0)->getBuffer();

	auto data = buf.getData();
	auto dataLength = buf.getLength();
	destVector = std::vector<byte>(data, data + dataLength);

	// expected bytecode
	76D059F0 | 50                       | push eax                                |
	76D059F1 | 50                       | push eax                                |
	76D059F2 | B8 7011C700              | mov eax,<grayeminenceconsole.void * __s |
	76D059F7 | 894424 04                | mov dword ptr ss:[esp+4],eax            |
	76D059FB | 58                       | pop eax                                 |
	76D059FC | C3                       | ret                                     |
	
	// actual (wrong) bytecode
	76D059F0 | 50                       | push eax                                |
	76D059F1 | 50                       | push eax                                |
	76D059F2 | B8 7011C700              | mov eax,<grayeminenceconsole.void * __s |
	76D059F7 | 67:8944 24               | mov dword ptr ds:[si+24],eax            |
	76D059FB | 04 58                    | add al,58                               |
	76D059FD | C3                       | ret                                     |

Could someone verify this behavior?

Thank you very much!

**Comment by kobalicek** [comment]
Can you try what you do again but with using `kTypeX86`? The `kTypeX32` may not be what you are looking for as it specifies `X32` architecture - AMD64 instruction set with 32-bit pointers, which is probably not what you want and it's completely untested.

**Comment by Vedaevolution** [comment]
@kobalicek As always there are the easy made errors. My bad. I close this issue right away.

Thank you very much and sorry for bothering you!

**Comment by kobalicek** [comment]
You are welcome and don't be sorry. The enum name is probably confusing and I have removed it in next-wip already as nobody ever tested the x32 support anyway.
