### ISSUE TITLE
push imm32 with "negative" value doesn't pass validation

### ISSUE THREAD

**Issue by mappzor** [asmjit/asmjit#227]
When kOptionStrictValidation is used, validation will reject `push imm32` with negative value e.g. `push 0xCCCCCCCC`. This happens because immediate value is treated as signed and that makes sense for x64 where 32-bit constant is sign-extended to 64 bits. Unfortunately this doesn't make sense in x86 mode and prevents generation of rather common instruction.

I think the fix would be to treat operand as unsigned for x86 mode only. As far as I understand asmjit's database generation process the actual fix would be required in asmdb rather than in asmjit itself.

This is the opposite problem to #226 I tested only master branch so far.

**Comment by kobalicek** [comment]
I can reproduce this. It's actually that unsigned immediate is not accepted, if you use `0xFFFFFFFFCCCCCCCC` then that would be accepted. Gonna fix this

**Comment by mappzor** [comment]
Yes, that's what I meant. I called it "negative" because current signature was treating it as signed while in reality problem is about unsigned immediates in range 0x80000000-0xFFFFFFFF.

**Comment by kobalicek** [comment]
This is now fixed in next-wip, but I don't plan to update master as that would require a bit of additional work right now.

**Comment by mappzor** [comment]
Thank you. I noticed that scripts from master don't work with current asmdb anymore as I tried to regenerate database files by myself, so I understand your decision.

Unfortunately using next-wip turned out to be too costly for me right now. Suprisingly not because of API changes but unexpected VS2017 requirement and I have way too many different dependencies to justify 2015->2017 upgrade for just one library :(

**Comment by kobalicek** [comment]
You can try to remove the VS2015 check in the build.h header and try to run unit tests. If they pass you should be safe, but you should really understand that the compiler can generate wrong code regarding constexpr's

**Comment by kobalicek** [comment]
BTW if you really need this fixed I can take a look this weekend and update master, but I cannot do it today

**Comment by mappzor** [comment]
Thanks, but there's no need to. I've worked around this by disabling verification for this one case and it works fine. Ugly, I know, but since this is just one extra if in a single place code I can live with it.

I will try to experiment with VS2015 and next-wip during the weekend. Actually I already tried that yesterday but it seemed that cmake ignored "-DASMJIT_STATIC=1" for some reason, so I gave up and left it for later. Probably I did something wrong as I was in a rush.

**Comment by kobalicek** [comment]
There are few changes in next-wip, one of them is to normalize build options to start with `ASMJIT_BUILD_...` so it would become `ASMJIT_BUILD_STATIC=1`, `ASMJIT_BUILD_TEST=1`, etc

**Comment by mappzor** [comment]
Oh, good to know. I expected this would be a trivial issue to resolve but just couldn't spend more time on it. Thanks again.

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
