### ISSUE TITLE
Minor error in addFunc() example

### ISSUE THREAD

**Issue by KFSPC8** [asmjit/asmjit#229]
Conflicting declaration of variable name "src" and "dst"
Fix:
`// Test the generated code.
  uint32_t inSrc[6] = { 1, 2, 3, 5, 8, 13 };
  uint32_t inDst[6];
  memcpy32(inDst, inSrc, 6);

  for (uint32_t i = 0; i < 6; i++)
    printf("%d\n", inDst[i]);`

**Comment by kobalicek** [comment]
Thanks, this should be corrected by now

**Comment by kobalicek** [comment]
Closing as next-wip was merged.
