### ISSUE TITLE
Question: Create Memory variables from memory pointers

### ISSUE THREAD

**Issue by fred26** [asmjit/asmjit#230]
I am trying to do Static Symbolic execution and I see asmjit as a good framework.

Let's say I have:

X86Gp src = x86::rax; 
X86Mem m = x86::ptr(src);

Can I define let's say X86Mem m1; and assign [[rax]] to it? The pointer in [rax]?

Something like:

X86Mem m1 = ptr(m); ?

if not, is there a way I can do this? Let's say:

xxxxxxx  mov rax,rbx
xxxxxxx  mov rax, [rax+0x10]
xxxxxxx  mov rcx, [rax]

Calculate the value of rcx at the end of this sequence. Ex: [[rbx+0x10]]

Thanks!

**Comment by kobalicek** [comment]
This is not possible as asmjit's operands were designed to model operands used by instructions (and not arbitrary expressions that we can see in programming languages, for example). So when using asmjit to model low-level constructs you would have to stay what each ISA basically offers to you, which would be similar to what you have written:

```x86asm
// Assuming you don't need the original address in `rax`.
mov rax, [rax] // Defererence [rax]
mov rax, [rax] // Dereference [rax] again
```

**Comment by fred26** [comment]
Ok Thanks. so my other question is:

can you emulate a set of instruction and get the value/state at a certain point?

xxxxxxx mov rax,rbx
xxxxxxx mov rax, [rax+0x10]
xxxxxxx mov rcx, [rax]

Calculate the symbolic value of rcx at this point.

Thanks

**Comment by kobalicek** [comment]
No asmjit was never designed for this, to do that you would need to get the read/write information of each instruction and calculate that symbolic value. The read/write info is btw discussed on asmjit's gitter chat often and I'm working on improving it in general. In other words, asmjit can help with something, but not with everything.

**Comment by fred26** [comment]
Ok thanks for all the info.
Regards
