### ISSUE TITLE
PPC64EL Port

### ISSUE THREAD

**Issue by madscientist159** [asmjit/asmjit#232]
With the resurgence of the ppc64le architecture on the desktop as a blob-free alternative to buggy, insecure x86 machines*, there is strong interest in ppc64el support for asmjit (blocking among other things GZDoom on this libre-friendly architecture).

We're willing to provide access to development hardware (VPS) if needed.

* See Talos II / Blackbird / etc. and the Linux community surrounding the POWER9 chip.

**Comment by pkubaj** [comment]
+1 for user demand, this blocks porting software like rpcs3.

**Comment by seb777** [comment]
+1 for company willing to sponsor the effort

**Comment by pkubaj** [comment]
> +1 for company willing to sponsor the effort

Can you clarify? Are you willing to sponsor it?

**Comment by seb777** [comment]
Unfortunately not, but I encourage anyone who can do it

**Comment by bencz** [comment]
https://openpower.ic.unicamp.br/minicloud/

Here, you can get a free access to a IBM Power8 and Power9, and create a Linux Instance, like Debian, Ubuntu, CentOS ....

**Comment by bencz** [comment]
Just an idea ... it might be interesting to have an abstraction layer, that is, the creation of an intermediate language between JIT and the program that is using JIT ... like, for example, MSIL ... but, it also exists the possibility of using JIT directly, passing the instructions ....
The creation of this layer would be to abstract the code between the architectures

**Comment by kobalicek** [comment]
I will not work on PPC port myself, this would really need a sponsor as I have a lot of other things to do.

**Comment by justinlynn** [comment]
What kind of sponsorship/ongoing support would be required to get a port up and running for this architecture? I could contribute code and testing assistance here but I'm very much a newbie WRT this project.

**Comment by kobalicek** [comment]
I have a very little interest in PPC architecture myself, so there would have to be somebody willing to work on the port, most likely backed by some company that would be interested in having PPC support in AsmJit, for some business reason most likely.

This is really a different situation compared to ARM/AArch64, which has much higher market capitalization, and thus interest of companies.

**Comment by justinlynn** [comment]
@kobalicek Understood and absolutely reasonable. Thank you :)

**Comment by kobalicek** [comment]
https://github.com/asmjit/asmjit/issues/430
