### ISSUE TITLE
Label in dd/dq

### ISSUE THREAD

**Issue by RazvanAciu** [asmjit/asmjit#237]
Hi, I'm trying to encode on 32 bits (next-wip branch) a table of labels for indexed jmp, something like:

mov eax,[selector]	// an integer 0...N-1 to select a branch
jmp [table+eax*4]
label1:	// some code
label2: // some code
...
labelN:	// some code
table:
dd label1
dd label2
...
dd labelN

I saw that "dd" only accepts an int32 value, not a Label. Is there a way to encode such a table, or this should be a feature request?
I did something similar by using assembler offsets, but in this case there are more instructions needed for the jmp selector.
Thank you

**Comment by kobalicek** [comment]
Hello, this functionality is supported through `embed(label)`. Let me know if that works for you.

**Comment by RazvanAciu** [comment]
Thank you for your quick answer. It works perfectly (using embedLabel).
