### ISSUE TITLE
Structs as arguments and return value to FuncSignature?

### ISSUE THREAD

**Issue by nickwanninger** [asmjit/asmjit#240]
Is it possible to have the following?
```cpp
struct foo {
	int a, int b;
};

// ...
  cc.addFunc(FuncSignature1<foo,
                            foo
                            >());
// ...
```

I can't seem to find any documentation about this. Is it going to end up being a pointer to the location of the value and I have to copy it over on my own? Should I just treat the type as void* for the time being?

**Comment by kobalicek** [comment]
Passing structs by value is not supported as it can get really tricky. If you need to pass a struct the best you can do is to pass a pointer to it. So it would become `FuncSignature2<void, foo*, foo*>`

**Comment by nickwanninger** [comment]
Does Asmjit support reference values there instead of pointers or do references and pointers work the same way internally?

**Comment by kobalicek** [comment]
There is no difference from asmjit perspective (they are the same). I don't even know if the function builder has support for references, I would have to check it out to be honest. Usually when people create JIT functions the signatures of such functions are simple (usually just pointers, integers, and maybe floating points).

Maybe I can review this code and add support for structs with one member (aka smart pointers, etc) or structs having 2 or 4 values of the same type, but nobody needed such functionality so far.

**Comment by nickwanninger** [comment]
Oh awesome, appreciate the help!
