### ISSUE TITLE
GCC 9.1.0 warning: -Wdeprecated-copy for Operand implicit copy constructor

### ISSUE THREAD

**Issue by pfent** [asmjit/asmjit#248]
Current GCC 9.1.0 warns about deprecated implicit `operator=` in `asmjit/base/operand.h`.

Consider this snippet:
```c++
#include "src/asmjit/asmjit.h"
int main(int argc, char**) {
	asmjit::Operand op;
	op = asmjit::Imm();
	(void) op;
}
```
Compiling it produces this warning:
```
$ g++ --version | head -n 1
g++ (GCC) 9.1.0
$ g++ -Wextra main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:6:19: warning: implicitly-declared ‘constexpr asmjit::Operand& asmjit::Operand::operator=(const asmjit::Operand&)’ is deprecated [-Wdeprecated-copy]
    6 |  op = asmjit::Imm();
      |                   ^
In file included from src/asmjit/././base/arch.h:13,
                 from src/asmjit/./base.h:12,
                 from src/asmjit/asmjit.h:34,
                 from main.cpp:1:
src/asmjit/././base/../base/operand.h:421:17: note: because ‘asmjit::Operand’ has user-provided ‘asmjit::Operand::Operand(const asmjit::Operand&)’
  421 |   ASMJIT_INLINE Operand(const Operand& other) noexcept { _init(other); }
      |                 ^~~~~~~
```

[cppreference](https://en.cppreference.com/w/cpp/language/copy_assignment) has some more information for this:
> The generation of the implicitly-defined copy assignment operator is deprecated(since C++11) if T has a user-declared destructor or user-declared copy constructor. 

The following snippet fixes this warning and preserves the *current* behavior. However, I'm not sure if this is the *intended* behavior, or if is should mirror the copy constructor?
```c++
ASMJIT_INLINE Operand& operator=(const Operand& other) noexcept = default;
```

**Comment by kobalicek** [comment]
I have pushed two commits, first to enable GCC 9 on CI and the second to fix the operand issue:
  - https://github.com/asmjit/asmjit/commit/82515e56cb23355e949742b896bd74d0c38ff3c2
  - https://github.com/asmjit/asmjit/commit/423eb0a4e45883895b1893ba6c3369849483ac17

I don't know whether I want to fix master branch (aka oldstable) as it's gonna be replaced by next-wip this month.

**Comment by pfent** [comment]
Thanks!
I think fixing oldstable shouldn't be necessary.

**Comment by kobalicek** [comment]
BTW: There are still some warnings in `next-wip` branch regarding this issue, but they will be fixed by my future commits as I'm still doing some cleanups. I expect this all to land this month.
