### ISSUE TITLE
avx512 masking examples

### ISSUE THREAD

**Issue by jspark1105** [asmjit/asmjit#250]
This is a question rather than an issue. One of the most useful additions in avx512 is its more flexible and general masking but I wasn't able to find examples/documentations how to use it in asjmjit. Any pointer would be really appreciated.

**Comment by kobalicek** [comment]
Hello, what particularly are you interested in?

If you want to use zeroing/masking then simply use `k()` and `z()` as a prefix, like this:

```c++
  using namespace asmjit;
  using namespace asmjit::x86;

  JitRuntime rt;
  CodeHolder code;
  code.init(rt.codeInfo());

  x86::Assembler a(&code);
  // k(reg) is like {kreg} in Intel syntax.
  // z() is like {z} in Intel syntax.
  a.k(k1).z().vaddpd(zmm0, zmm1, zmm2);
```

Similarly to rounding modes and {sae}:

```c++
  a.sae().instruction(...); // Adds {sae}
  rn_sae().instruction(...); // Adds {rn} + {sae}
  rd_sae().instruction(...); // Adds {rd} + {sae}
  ru_sae().instruction(...); // Adds {ru} + {sae}
  rz_sae().instruction(...); // Adds {rz} + {sae}
```

Broadcast is part of memory operand:

```c++
  // Forms: vaddpd zmm0 {k1} {z}, zmm1, [rcx] {1to8}
  a.k(k1).z().vaddpd(zmm0, zmm1, x86::mem(rcx)._1to8());
```

Some little documentation is also here:

https://asmjit.com/api/structasmjit_1_1x86_1_1EmitterExplicitT.html#acbfb329aa1a46b765974572275ef54a5

I will keep this open until I add some examples to the README.md

**Comment by jspark1105** [comment]
This answers my question. Exactly what I was looking for. Thanks!

**Comment by kobalicek** [comment]
AVX512 examples are now part of AsmJit documentation, thanks!
