### ISSUE TITLE
Win64 parameter passing example

### ISSUE THREAD

**Issue by ykim362** [asmjit/asmjit#257]
I have a question. Would you be able to provide an example code or a pointer for parameter passing (by stack) on windows x64? I am converting a Linux function (asmjit code) to a windows function, and they have different calling conventions. The function I am trying to port is using 6 parameters which fits into Linux calling convention, but not for the windows calling convention. I need to pass 2 arguments through stack.
For your information, below is the code change I made. (#ifdef _MSC_VER). This code is from [FBGEMM](https://github.com/pytorch/FBGEMM).
Thank you!

```
  // arguments to the function created
#ifdef _MSC_VER
  asmjit::X86Gp buffer_A = a->zcx();
  asmjit::X86Gp buffer_B = a->zdx();
  asmjit::X86Gp B_pf = a->gpzRef(8);
  asmjit::X86Gp CBase = a->gpzRef(9);
  asmjit::X86Gp kSize = a->zdi();
  asmjit::X86Gp ldcReg = a->zsi();
#else
  asmjit::X86Gp buffer_A = a->zdi();
  asmjit::X86Gp buffer_B = a->zsi();
  asmjit::X86Gp B_pf = a->zdx();
  asmjit::X86Gp CBase = a->zcx();
  asmjit::X86Gp kSize = a->gpzRef(8);
  asmjit::X86Gp ldcReg = a->gpzRef(9);
#endif

  asmjit::FuncDetail func;
#ifdef _MSC_VER
  func.init(asmjit::FuncSignature6<void, uint8_t*, int8_t*, int8_t*, int32_t*, int, int>(
      asmjit::CallConv::kIdHost));
#else
  func.init(
      asmjit::
          FuncSignature6<void, uint8_t*, int8_t*, int8_t*, int32_t*, int, int>(
              asmjit::CallConv::kIdHost));
#endif

  asmjit::FuncFrameInfo ffi;
  ffi.setDirtyRegs(
      asmjit::X86Reg::kKindVec,
      asmjit::Utils::mask(0, 1, 2, 3, 4, 5, 6, 7) |
          asmjit::Utils::mask(8, 9, 10, 11, 12, 13, 14, 15));
  ffi.setDirtyRegs(
      asmjit::X86Reg::kKindGp,
      asmjit::Utils::mask(8, 9, 10, 11, 12, 13, 14, 15));

  asmjit::FuncArgsMapper args(&func);
#ifdef _MSC_VER
  args.assignAll(buffer_A, buffer_B, B_pf, CBase, kSize, ldcReg);
#else
  args.assignAll(buffer_A, buffer_B, B_pf, CBase, kSize, ldcReg);
#endif

  args.updateFrameInfo(ffi);

  asmjit::FuncFrameLayout layout;
  layout.init(func, ffi);

  asmjit::FuncUtils::emitProlog(a, layout);
  asmjit::FuncUtils::allocArgs(a, layout, args);

#ifdef _MSC_VER
  // retrieve parameters from stack
  a->mov(kSize, asmjit::x86::dword_ptr(asmjit::x86::rsp, func.getArg(4).getStackOffset()));
  a->mov(ldcReg, asmjit::x86::dword_ptr(asmjit::x86::rsp, func.getArg(5).getStackOffset()));
#endif

```

**Comment by kobalicek** [comment]
If you use asmjit's function utilities (like you do) then all the necessary moves will be generated by `emitProlog()` and `allocArgs()` so there is no need to add explicit moves, all the registers will be properly allocated.

Maybe isolating this example into something complete would help me understanding your problem.

And btw, I would recommend to port your code into a new asmjit - you are using `oldStable` branch, which will be discontinued at the end of the year - and since you seem to only use Assembler interface it should be really easy to port.

**Comment by ykim362** [comment]
Thank you so much!
It seems that it's working fine after commenting `mov` lines out.

And, thanks for the recommendation!
This is a fork from another open source project. The mother project might have switched to the new asmjit. I will sync with the mother project.
