### ISSUE TITLE
Linkage Errors on Linux?

### ISSUE THREAD

**Issue by AndroDevcd** [asmjit/asmjit#258]
I tried to compile my project recently on linux and recieved the following error:

```
/tmp/ccAokKeg.o: In function `asmjit::VirtMem::allocDualMapping(asmjit::VirtMem::DualMapping*, unsigned long, unsigned int)':
virtmem.cpp:(.text+0x331): undefined reference to `shm_open'
virtmem.cpp:(.text+0x351): undefined reference to `shm_unlink'
virtmem.cpp:(.text+0x5ea): undefined reference to `shm_open'
virtmem.cpp:(.text+0x609): undefined reference to `shm_unlink'
```

in my main header file for the JIT I had the following code 

```
#ifndef SHARP_JITASSEMBLER_H
#define SHARP_JITASSEMBLER_H

#define ASMJIT_BUILD_HOST  1
#define ASMJIT_STATIC   1
#define ASMJIT_BUILD_RELEASE 1

#include "../util/jit/asmjit/src/asmjit/asmjit.h"
...
```

Have I done something wrong here? I am compiling on an AWS virtual machine and `cat proc/cpuinfo` returned  

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xb000037
cpu MHz         : 2299.892
cache size      : 46080 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
...
bogomips        : 4600.12
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xb000037
cpu MHz         : 2299.892
cache size      : 46080 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
...
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 4600.12
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
```

**Comment by kobalicek** [comment]
I don't know how to help if I don't know how you compile asmjit and how you link to it. It seems you are missing `librt` library.

I would first try to build official asmjit (with tests, for example) - and to look how it builds. In general you should only need few libraries like `-lpthread` and `-lrt`

**Comment by AndroDevcd** [comment]
It looks like I was missing -lrt, Thanks!
