### ISSUE TITLE
"movabs rax,[imm_pointer]" 

### ISSUE THREAD

**Issue by Paliha** [asmjit/asmjit#260]
Hi!
what is the difference when encoding if the operand is not equal rax&eax and (rip+disp) = pointer ?
mov rax(or eax),[decode_pointer]&mov[decode_pointer],rax(or eax)
after coding instructions
movabs rax(eax),[imm_pointer]&movabs [imm_pointer],rax(or eax)

**Comment by kobalicek** [comment]
Can you be a bit more specific? I don't think I understand the question 100%.

Movabs is a special instruction that can only be encoded with `[r|e]ax` operand, all other forms with RIP etc are regular `mov` instructions. AsmJit at the moment has the same name for both instructions (mov and movabs) because the Intel Architecture Manual didn't differentiate between these two.

**Comment by Paliha** [comment]
>>all other forms with RIP etc are regular mov instructions
I understand that for the operand [r | e] ax, the pointer relative to the location of the instruction must be encoded itself?
unfortunately, the jit itself determines that the pointer in the instruction will not be dependent on the location of the instruction.
   00000001403C00A4
   MOVABS RAX, QWORD PTR [0x1423B0BF0]
   insn->id: 450
   insn->size : 0x0A byte
   CS_AC_WRITE ( 2 )
   x86->operands[0].type: X86_OP_REG
   x86->operands[0].reg : X86_REG_RAX
   x86->operands[0].size: 0x08 byte
   CS_AC_READ  ( 1 )
   x86->operands[1].type: X86_OP_MEM 
   x86->operands[1].size: 0x08 byte
   x86->operands[1].mem.disp: 0x1423B0BF0
   ++++++( 1 )++++++
   00000001403C00A4
   MOV RAX, QWORD PTR [RIP + 0x1FF0B45] | 0x1423B0BF0
   insn->id: 449
   insn->size : 0x07 byte
   CS_AC_WRITE ( 2 )
   x86->operands[0].type: X86_OP_REG
   x86->operands[0].reg : X86_REG_RAX
   x86->operands[0].size: 0x08 byte
   CS_AC_READ  ( 1 )
   x86->operands[1].type: X86_OP_MEM 
   x86->operands[1].size: 0x08 byte
   x86->operands[1].mem.base: X86_REG_RIP
   x86->operands[1].mem.disp: 0x1FF0B45

**Comment by Paliha** [comment]
x86assembler.cpp:
str.1539 // Handle a special form `mov al|ax|eax|rax, [ptr64]` that doesn't use MOD.
str.1573 // Handle a special form `mov [ptr64], al|ax|eax|rax` that doesn't use MOD.
it seems that it is enough to comment out so that the reg_operand does not play a value during encoding.
if there are variations precisely with the opcode "movabs", can it be repelled from it?

**Comment by kobalicek** [comment]
Maybe forcing ABS on the memory operand is what you are looking for? For example:

```c++
assembler.mov(x86::ptr_abs(0x1234), x86::rax);
assembler.mov(x86::rax, x86::ptr_abs(0x1234));
```

**Comment by Paliha** [comment]
I excluded your code from the case, and the result is quite fine with me. I have never met the instruction "movabs" with  pointer VA. basically the second operand has always been an imidiate. 
If disassemblers define such an instruction as valid, it probably is.
And my question is how to fix the code in the case so that my corrections do not harm. In your decision, the operand [r|e]ax is primary, while the instruction code for some reason is secondary, or it does not matter.

**Comment by UnlimitedChild** [comment]
The author’s question is how to get the code mov rax,[imm_pointer] in the form MOV RAX, QWORD PTR [RIP + Pointer], but not in the form movabs rax(eax),[imm_pointer]&movabs [imm_pointer],rax(or eax).

**Comment by kobalicek** [comment]
I would say you can always choose between these two by using either ptr_abs or ptr_rel:

```c++
assembler.long_().mov(x86::ptr_rel(0x1234), x86::rax);
assembler.long_().mov(x86::rax, x86::ptr_rel(0x1234));
```

However, relative addressing depends on RIP so only +-2GB range is encodable relative to the code.

**Comment by kobalicek** [comment]
Update: AsmJit will get `movabs` instruction that would always work either with 64-bit immediate value (`mov reg, imm64`) or 64-bit absolute immediate address (`mov reg, [imm64]` and `mov [imm64], reg`) - I went over open issues this weekend and i think this is the only sensible way of specifying a particular encoding.

**Comment by kobalicek** [comment]
`movabs` is now supported, starting with 58b6c025f2b89b1beac9c5a5f84c4c6ae5a521b1 commit. The logic of encoding mov changed slightly, but not much. Use `ptr_rel()` to force relative address (if the heuristics fail for some reason) or `mod_mr()` prefix to force MOD byte, which has a similar effect with `mov` as `ptr_rel()`.
