### ISSUE TITLE
Trying to read and sum integer and real variables.

### ISSUE THREAD

**Issue by thiagomacg** [asmjit/asmjit#262]
I am using the asmjit library to compile a numeric function in assembler. 
 
 Example:
 `int x [5];
  double y [4];
  fo = x[2] + y[1] + 3*x[4] - y[2] + 5.6 + 7*x[1]` 

```    
        asmjit::JitRuntime rtt;
        asmjit::CodeHolder codee;
        codee.init(rtt.codeInfo());
        asmjit::x86::Assembler aa(&codee);
        

        asmjit::Zone zonee(1024);
        asmjit::ConstPool constPooll(&zonee);
        asmjit::Label constPoolLabell = aa.newLabel();

        asmjit::x86::Compiler cc(&codee);

        cc.addFunc(FuncSignatureT<int, uint32_t*>(CallConv::kIdHost));

        asmjit::x86::Gp src = cc.newIntPtr("src");    
        cc.setArg(0, src);

        aa.mov(asmjit::x86::eax, 0);
        aa.mov(asmjit::x86::ebx, 3);
        aa.mov(asmjit::x86::eax, asmjit::x86::ebx);

        for(int i = 0; i < dim; i++){
            cc.add(src, i*sizeof(int));
            asmjit::x86::Gp tmp = cc.newInt32("tmp");             
            cc.mov(tmp, asmjit::x86::dword_ptr(src));
            cc.mov(asmjit::x86::ebx, tmp);
            cc.sub(src, i*sizeof(int));
            aa.add(asmjit::x86::eax, asmjit::x86::ebx);
        }

        cc.endFunc();                           // End of the function body.
        cc.finalize();

        aa.ret();
        FuncParam fn;

        aa.embedConstPool(constPoolLabell, constPooll);
        rtt.add(&fn, &codee);         
        int res = fn(int_val);
        printf("%d\n", res);                
        rtt.release(fn);
```
In the code above I tried to follow as described in this link: https://github.com/asmjit/asmjit/blob/master/test/asmjit_test_x86_cc.cpp#L2056. 

In the excerpt presented the values ​​read in src are not stored in variable ebx and therefore are not summed.  cc.mov(asmjit::x86::ebx, tmp);

Any tips, references? What to do in case of double variables?
            
Thanks

**Comment by kobalicek** [comment]
You are mixing assembler and compiler so you are essentially creating two asm streams. It doesn't work the way you wrote it. The documentation (README.md) explains briefly Assembler, Builder, and Compiler so I would read it first and then decide which tool to use first.

**Comment by thiagomacg** [comment]
Hello,
Thank you, I was making this basic mistake.

Now, I am trying to include/read a function with boolean parameters.

I did not find any examples that used, it is possible to pass boolean vector, or should instead use integers. Can the chosen records be used for this?   bools = x86 :: esi;  ints = x86 :: rdi; doubls = x86 :: rsi;

   `   



       typedef double (*FuncParam)(bool*, int*, double*);
       bool bool_val[6] = {false, false, true, true, false, false};
       std::vector<int> int_val = {5, 5, 5, 5, 5, 5};
       std::vector<double> doub_val = {1.5, 1.5, 1.5, 1.5, 1.5, 1.5}; // (dim, 1);

       asmjit::JitRuntime rtt;
       asmjit::CodeHolder codee;
       codee.init(rtt.codeInfo());

       asmjit::x86::Assembler aa(&codee);

        asmjit::Zone zonee(1024);
        asmjit::ConstPool constPooll(&zonee);
        asmjit::Label constPoolLabell = aa.newLabel();

        x86::Gp bools;
        x86::Gp ints;
        x86::Gp doubls;

        if (ASMJIT_ARCH_BITS == 64) {
        #if defined(_WIN32)
            bools = x86::rbx;
            ints = x86::rcx;                   
            doubls = x86::rdx;                     
        #else
            bools = x86::esi;
            ints = x86::rdi;                    
            doubls = x86::rsi;
        #endif
        }
        else {
            bools = x86::ecx;
            ints = x86::edx;
            doubls = x86::ebx;
            aa.mov(bools, asmjit::x86::ptr(asmjit::x86::esp, 4));
            aa.mov(ints, asmjit::x86::ptr(asmjit::x86::esp, 8));
            aa.mov(doubls, asmjit::x86::ptr(asmjit::x86::esp, 12));
        }

        FuncParam fn;

         a.ret();
        FuncParam fn;

        // At the end of the code, after it returns, you may embed the data.
        // This would bind the label here with proper alignment and embed
        // all constants.
        a.embedConstPool(constPoolLabel, constPool);

        rt.add(&fn, &code);         // Add the generated code to the runtime.
       
        double res = fn(bool_val, int_val.data(), doub_val.data());
        printf("%f\n", res);                 // Print the resulting "1".

        rtt.release(fn);  `

Thank you

**Comment by kobalicek** [comment]
You can pass basically anything, but then you should know how compiler sees `bool[]` - it's most likely just the same as `char[]` as `char` is the smallest type.

In addition, I'm not sure about your code, for example:

```
     a.add(bools, 4);
     a.mov(asmjit::x86::ebx, asmjit::x86::dword_ptr(bools));
     a.add(bools, 4);
     a.mov(asmjit::x86::ebx, asmjit::x86::dword_ptr(bools));
```

the seems just too wrong as you overwrite your `ebx|rbx` register, which could be a parameter
