### ISSUE TITLE
relocCode not found

### ISSUE THREAD

**Issue by dexter4life** [asmjit/asmjit#264]
Trying to use maybe an old version of asmjit but noticed that in this new update my code doesn't run as expected. relocCode is missing. What's the alternative to this function?

**Comment by dexter4life** [comment]
Here is my code that's giving me errors
```

 if ((bufferList.offset + codeSize) > m_BufferSize) {
    // can't place function in buffer, allocate another and try again
    allocateBuffer(original);
    // we could relocate the code and the data but this is simpler
    return storeTrampoline(reroute, original, preambleSize, rerouteOffset);
  }

  // copy code to buffer
  codeSize = static_cast<size_t>(assembler.relocCode(spot));

  bufferList.offset += preambleSize + codeSize;

  return spot;
```

**Comment by kobalicek** [comment]
I think you are looking for `CodeHolder::relocateToBase()` - this logic is now in CodeHolder and not in Assembler.

In addition, asmjit now supports sections so if you do custom relocation maybe this example would help you to understand the complete process:

https://github.com/asmjit/asmjit/blob/master/test/asmjit_test_x86_sections.cpp
