### ISSUE TITLE
Iterative calls to an external function

### ISSUE THREAD

**Issue by thiagomacg** [asmjit/asmjit#265]
I am trying to create a parser of a function and generate its corresponding assembler code.
In the code snippet below, I try to parser the sine function by storing the result in the asmjit :: x86 :: xmm1 registry

`   

      this->parameters.front()._impl->compileAsmJit(c, constPool, constPoolLabel, ints, dbls, no_raiz);

       asmjit::x86::Xmm tmp = c.newXmmSs("a");
       asmjit::x86::Xmm ret = c.newXmmSd("ret");
       c.movsd(tmp, asmjit::x86::xmm1);

       auto call_c = c.call((uint64_t)(double(*)(double))std::sin, asmjit::FuncSignatureT<double, double>(asmjit::CallConv::kIdHost));
       call_c->setArg(0, tmp);
       call_c->setRet(0, ret);

       c.movsd(asmjit::x86::xmm1, ret); `
      
For example, given the function below

`fx = sin(90.1)+sin(90.1)+sin(120.1)
 fx = 0.658993
`

The first line in the code above reads the values ​​in degrees and stores in xmm1. This value is then passed to the function. However for some reason, the final calculation stores only the value of the last sine term.

Note: This sum works when I do not use an external function call.

**Comment by kobalicek** [comment]
One tip: Don't mix physical and virtual registers - The compiler doesn't see the physical ones, it ignores them, so if you use them the behavior is basically undefined. I mean these moves to xmm1 like `c.movsd(asmjit::x86::xmm1, ret);`.

This is most likely the root of the problem in this case.

**Comment by thiagomacg** [comment]
Hello. I got the hint you gave me.
However in another piece of my code, I use movsd between a Gp and an Xmm.
In this case it works because the physical variable was previously created?
Perhaps if, in the previous example, physically creating the ret variable previously would help?



           x86::Gp dbls;
           dbls = x86::rdi;
            int index = sizeof(double)*this->index;
            a.add(dbls, index);
            a.movsd(asmjit::x86::xmm1, asmjit::x86::dword_ptr(dbls));
            a.sub(dbls, index);

**Comment by kobalicek** [comment]
Well, if you want to use a XMM register, you should first create it like `compiler->newXmm()`, then you can use it. Using physical registers with Compiler is really not supported, it cannot be done like this.
