### ISSUE TITLE
Bug for "mov word ptr [rsp-0x20], cs"

### ISSUE THREAD

**Issue by remittor** [asmjit/asmjit#266]
I used "oldstable" brunch.
Code `mov word ptr [rsp - 0x20], cs` translate to 66 8C **54** 24 E0.
It should be like this: 66 8C **4C** 24 E0
Where should I look for an error?

**Comment by kobalicek** [comment]
Thanks! I think I have found the problem. Let me know whether the commits above fix the problem.

**Comment by remittor** [comment]
Fixed!
