### ISSUE TITLE
mov rax, qword ptr gs:[0x30]

### ISSUE THREAD

**Issue by ZehM4tt** [asmjit/asmjit#27]
The instruction in the title above is impossible to generate. I'm trying to setup a Mem object and say setSegment(gs)

It produces:

MOV RAX,QWORD PTR GS:[RDI+30]

I don't see how the RDI is getting there.

**Comment by kobalicek** [comment]
I'm closing this.

AsmJit has no longer noGpReg, and its use should be eliminated if possible. The preferred way to encode such memory operand is:

```
// Create [address] operand:
X86Mem m = x86::ptr((uint64_t)absoluteAddress);

// Specify segment override:
m.setSegment(X86Seg::kIdGs);
```

I think it would be possible to add an overload so you can just write x86::ptr(segmentReg, address) as this is a common use-case, but the current behavior should work as well and it's more concise with other mem-operand builders.
