### ISSUE TITLE
StringBuilder

### ISSUE THREAD

**Issue by AntonSazonov** [asmjit/asmjit#271]
Hello.
What is StringBuilder? It does not exists in library headers.
I want to dump function code to console. How can i do it?

**Comment by kobalicek** [comment]
There is no `StringBuilder`in asmjit, only `String`. StringBuilder was used in older versions, for example `oldstable` branch still uses it, but that's now legacy and unsupported version.

Please read `README.md`, which contains examples of using logging and dumping output as binary.

**Comment by AntonSazonov** [comment]
Ok. Thanks.
