### ISSUE TITLE
Calling diferent std functions in calls 

### ISSUE THREAD

**Issue by thiagomacg** [asmjit/asmjit#273]
Good morning,

Consider the following expression: cos(abs(x1)) + cos(abs(x2)) + cos(abs(x3)) ... ;
I m trying to execute in this form; 

`
```
... // Initialize assembly code (CodeHolder, Jit... )
asmjit::JitRuntime jit;                       
asmjit::CodeHolder code;               

code.init(jit.codeInfo());              
asmjit::x86::Assembler a(&code); 

asmjit::Zone zonee(1024);
asmjit::ConstPool constPool(&zonee);
asmjit::Label constPoolLabel = a.newLabel();

a.movsd(asmjit::x86::xmm0, asmjit::x86::xmm1);
a.call((uint64_t) (double(*)(double)) ::abs);
a.movsd(asmjit::x86::xmm1, asmjit::x86::xmm0);

a.movsd(asmjit::x86::xmm0, asmjit::x86::xmm1);
a.call((uint64_t) (double(*)(double)) ::cos);
a.movsd(asmjit::x86::xmm1, asmjit::x86::xmm0);

// Finishing
FuncParam fn;

a.ret();
a.embedConstPool(constPoolLabel, constPool);
a.finalize();                         

auto err = rt.add(&fn, &code);       
if (err) return NULL;

return fn;
```

`

Any details I forgot to add? Any considerations or observations to be made?
Thanks

**Comment by kobalicek** [comment]
Yeah, you would have to study 64-bit calling conventions (SystemV and Win64 in this case). If you do a mistake in this case it could be very hard to debug. For example stack is always aligned to 16-byte boundary before calling any function in 64-bit mode and this code doesn't seem to respect that. I would just use Compiler in this case as it makes this much easier. In addition, you don't have to call `abs()`, absolute value is just masking and can be done inline.

**Comment by thiagomacg** [comment]
Thanks, 

My question is also because it works normally if I make several calls to the same function (cos) in sequence. If they are different functions, an error already occurs when calling the second function to be evaluated (cos + sen; cos + pow)

```
... // Initialize assembly code (CodeHolder, Jit... )
asmjit::JitRuntime jit;                       
asmjit::CodeHolder code;               

code.init(jit.codeInfo());              
asmjit::x86::Assembler a(&code); 

asmjit::Zone zonee(1024);
asmjit::ConstPool constPool(&zonee);
asmjit::Label constPoolLabel = a.newLabel();

a.movsd(asmjit::x86::xmm0, asmjit::x86::xmm1);
a.call((uint64_t) (double(*)(double)) ::cos);
a.movsd(asmjit::x86::xmm1, asmjit::x86::xmm0);

a.movsd(asmjit::x86::xmm0, asmjit::x86::xmm1);
a.call((uint64_t) (double(*)(double)) ::cos);
a.movsd(asmjit::x86::xmm1, asmjit::x86::xmm0);

// Finishing
FuncParam fn;

a.ret();
a.embedConstPool(constPoolLabel, constPool);
a.finalize();                         

auto err = rt.add(&fn, &code);       
if (err) return NULL;

return fn;
```

**Comment by kobalicek** [comment]
Here is a relevant material that may help in your case:
  - https://uclibc.org/docs/psABI-x86_64.pdf (Unix)
  - https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019 (Win64)

As I said, if you construct a wrong call it's basically undefined behavior - it may crash or it may work depending on the function that you call. I think asmjit logger and going to disassembly is your option.
