### ISSUE TITLE
jump generates extra null bytes!

### ISSUE THREAD

**Issue by overtech1** [asmjit/asmjit#274]
why jump instruction generates extra null bytes?

x86::Assembler a(&codeHolder);
...
a.jmp(Label);
...

Output : \xe9\x4b\x00\x00\x00

and altogether the assembler generates more machine code related to other assemblers like nasm

**Comment by kobalicek** [comment]
It doesn't know in advance how much the space it would need for a forward label, so it allocates the most it can. You can force short jump by `a.short_().jmp(Label)`, but then make sure the displacement is encodable otherwise you would get an error.

**Comment by overtech1** [comment]
thanks, this solution fixed the problem.
