### ISSUE TITLE
Generation can be improved for: mov qword ptr ds:[addr], rax

### ISSUE THREAD

**Issue by m417z** [asmjit/asmjit#275]
I stumbled upon the issue while using x64dbg, which uses asmjit as the assembler engine.
I tried to assemble the following command:

    mov qword ptr ds:[0x00007FF723E63008], rax

on the following address: `0x00007FF723E6102B`.

I expected the following sequence to be generated: `48 89 05 D6 1F 00 00`, but instead I got: `48 A3 08 30 E6 23 F7 7F 00 00`.

Here's a short gif:
![demonstration](https://user-images.githubusercontent.com/4129781/74589786-09f5ef00-5011-11ea-93bf-7f155fc81066.gif)

This causes two problems: the sequence is larger, and it encodes an absolute address, so the code is no longer position independent.

Also, as you can see on the gif, other registers (at least rcx) cause the expected sequence to be generated.

It's possible that it's already fixed and that x64dbg needs to update to a newer version of asmjit. I'm not sure, and currently I don't have the time to check (I haven't found an online assembler or something - that could be nice). I skimmed over the closed issues and didn't see anything relevant.

**Comment by kobalicek** [comment]
Hi, since this is a recurring issue I have decided to actually split the `mov` instruction into `mov` and `movabs`, because it seems it's just too hard to control which one should be emitted. The `mov` was initially used as Intel manuals used that mnemonic as well for both variants of the instruction.

**Comment by kobalicek** [comment]
btw asmjit supports both forms at the moment:

Try:
```
mov qword ptr ds:[rel 0x00007FF723E63008], rax -> 488905D61F0000
mov qword ptr ds:[0x00007FF723E63008], rax -> 48A30830E623F77F0000
```

**Comment by Paliha** [comment]
https://github.com/asmjit/asmjit/issues/260
x86assembler.cpp:
str.1539 // Handle a special form mov al|ax|eax|rax, [ptr64] that doesn't use MOD.
str.1573 // Handle a special form mov [ptr64], al|ax|eax|rax that doesn't use MOD.
------
leave part of the case code under the comments, and reassemble the library

**Comment by kobalicek** [comment]
@Paliha that is not a solution and I don't recommend doing that.

As I wrote above, you are able to specify which instruction form will be emitted, it's just hidden behind `addrType()`, which can be set to `abs` or `rel`.

The problem in this case is that asmjit has to decide if this is not specified, and sometimes it doesn't do what you may expect, so the question is whether the current behavior is okay or whether a new instruction `movabs` should be added - which would be a breaking change, that's why I'm not 100% sure about that.

**Comment by m417z** [comment]
> I think that in this case asmjit's heuristics is most likely wrong, because if the offset of the code is known the absolute address can really be converted to relative in this case.

I agree. By the way, XEDParse (x64dbg's second assembler engine) uses the relative command in this case.

**Comment by kobalicek** [comment]
Let me know whether the commit fixed the issue.

**Comment by m417z** [comment]
If you can build a dll for me, I'll try it with x64dbg.

**Comment by kobalicek** [comment]
I won't do that, sorry :)

**Comment by m417z** [comment]
OK, so I'll wait until @x64dbg updates to the new version I guess :)

**Comment by Paliha** [comment]
>OK, so I'll wait until @x64dbg updates to the new version I guess :)
updated assembly, with my corrections on this topic:
asmjit_xedparse-master_bin https://dropmefiles.com/oZS8A.
### @kobalicek, i like how the motor manages the imm, especially with a sign, there is no need to convert 0xffff, to -1. but this concerns conventional instructions, and there is in the instructions with three operands, and in the instructions of the memory recording, there is not.
Can such support be provided for such instructions?
.............................

**Comment by m417z** [comment]
The behavior is different in the new version, but looks like it still has issues.
In the old version:
* The absolute command was always used.
* Using the `rel` syntax made no difference (see the gif below to verify that I did it right).
In the new version:
* The relative command is always used.
* Looks like there's no way to get the absolute command, neither by using a "far" address, nor by using the `abs` syntax.

See the following gif to see what I tried:
![jJPHbYKg9M](https://user-images.githubusercontent.com/4129781/75473875-a075c900-599e-11ea-9291-d12c0dd73d0c.gif)

**Comment by kobalicek** [comment]
There are already tests that work:

https://github.com/asmjit/asmtk/blob/master/test/asmtk_test_x86parser.cpp#L201

Can you write tests that would actually fail?

**Comment by m417z** [comment]
> Can you write tests that would actually fail?

Unfortunately, not at this point. Until now my report was from a user's (not a programmer's) point of view. I hoped that it would be enough to demonstrate the bug with x64dbg (which is open source), and that I won't have to dive into code, since I never used asmjit as a programmer.

I can try and dive into the code, but I don't think it's going to be productive since I'm not familiar with the library at all.

**Comment by kobalicek** [comment]
Hi, I think that commit 37cf5c857a75e1e7da140d06893cc48a90525ee7 should close this issue. Now you can decide between `mov` and `movabs` instructions - `mov` still decides which encoding to use, `movabs` always forces 64-bit immediate encoding.
