### ISSUE TITLE
Relocation of relative address fails on macOS 64bit

### ISSUE THREAD

**Issue by christophhart** [asmjit/asmjit#276]
The call to `JitRuntime::add()` seems to fail with the error code `kErrorRelocOffsetOutOfRange` when there is a relocation of type `RelocEntry::kTypeAbsToRel`. 

I am using these relocations for "global variables" (which are stored in a separate data range), so whenever I am using variables defined outside the function, the `JitRuntime::add()` fails to create a function pointer:

```cpp

float works(float input)
{
    input *= 5.0f;
    return input;
}

float x = 2.0f;

float doesnt(float input)
{
    x *= input;
    return input;
}
```

The code path in question is found in CodeHolder.cpp at line 965:

```cpp
case RelocEntry::kTypeAbsToRel: {
        value -= baseAddress + sectionOffset + sourceOffset + regionSize;
        if (gpSize > 4 && !Support::isInt32(int64_t(value)))
          return DebugUtils::errored(kErrorRelocOffsetOutOfRange);
        break;
      }
```

in my case, `gpSize` is 8, and the value is a "full" 64bit address (`value	uint64_t	105548690437400` so it can't be casted to a 32bit integer and the function aborts here...

I don't understand the full details of how this works, but what does that line mean? if the register size is 8 bytes, it should be able to hold a 64bit address, so why isn't the condition

```
if (gpSize == 4 && !Support::isInt32(int64_t(value)))
```

This only happens on macOS, on Windows (64bit)  everything is fine.

**Comment by kobalicek** [comment]
The problem is that in this case the displacement is not encodable (it's an architecture constraint).

Can you share how you call the function?

**Comment by christophhart** [comment]
Actually I could reproduce it with a very minimal example:

```cpp
        using namespace asmjit;
        
        int ok = 0;
        
        JitRuntime rt;
        CodeHolder ch;
        
        ok = ch.init(rt.codeInfo());
        
        
        X86Compiler cc(&ch);
        
        FuncSignatureX sig;
        sig.setRetT<float>();
        sig.addArgT<float>();
        
        cc.addFunc(sig);
        
        // a dummy external data location
        float x = 18.0f;
        auto xPtr = (void*)(&x);
        
        auto r1 = cc.newXmmSs();
        auto mem = x86::ptr(reinterpret_cast<uint64_t>(xPtr));
        //auto mem = cc.newFloatConst(ConstPool::kScopeLocal, 18.0f);
        
        ok = cc.setArg(0, r1);
        ok = cc.movss(r1, mem);
        cc.ret(r1);
        
        ok = cc.endFunc();
        ok = cc.finalize();
        
        void* f = nullptr;
        
        ok = rt.add(&f, &ch);
        
        expect(f != nullptr);
        
        using signature = float(*)(float);
        
        auto func = (signature)f;
        auto returnValue = func(19.0f);
        
        expect(returnValue == 18.0f);
```

If I uncomment the other line so that it uses a constant float, it passes both tests. Also the code was running fine with an older version of asmjit.

Happens on an i7 Macbook Pro running macOS Mojave 10.14.5 with 64bit build.

**Comment by kobalicek** [comment]
Yeah I see. As I said, this is an architecture constraint - you cannot encode 64-bit absolute address in memory operand except in a special mov case.

The solution is to load the address first to register and then use the register:

```
x86::Gp baseAddress;
cc.mov(baseAddress, reinterpret_cast<uint64_t>(xPtr));
auto mem = x86::ptr(baseAddress);
```

BTW you seem to be using old asmjit (oldstable at the moment), I would recommend updating.

**Comment by christophhart** [comment]
Hmm, actually I've updated it a few weeks ago to the latest master state. What makes you think I'm using the old asmjit?

**Comment by kobalicek** [comment]
I see, well I saw `X86Compiler`, which was used by oldstable :)

**Comment by christophhart** [comment]
Ah, I see, I'm using an alias so I don't have to update my codebase, but forgot about it when I was writing this example:

```cpp
using X86Compiler = x86::Compiler; // or whatever :)
```

Is there a noticeable performance hit if I load it into a register first? Because then I would branch the code generation between Windows and macOS.

**Comment by kobalicek** [comment]
I would not think of performance hit in this case - if the code compiles you are basically lucky that you are within the +-2GB bounds, it's not OS specific, it's just lucky vs not lucky, so I would always move to the register first.

**Comment by christophhart** [comment]
Alright, I've changed the memory addressing and everything works now. Feel free to close.
