### ISSUE TITLE
[Question] AOT Compilation

### ISSUE THREAD

**Issue by AndroDevcd** [asmjit/asmjit#277]
Can you do AOT compilation to generate an ELF file? If so how would one go about doing that?

**Comment by kobalicek** [comment]
There is no functionality to generate COFF or ELF in asmjit at the moment and that functionality would most likely go to asmtk library. You can still do AOT compilation even without ELF if you can guarantee that the code is position independent and or you can link it properly.

Maybe @ZehMatt has something to say as we have already talked about this topic, but no work has been done.

**Comment by AndroDevcd** [comment]
Ahh okay, so how in simple terms would I go about generating an AOT compiled code. I know that you can get the raw generated code from one of the objects. Just wondering for a future feature in my prog. lang.

**Comment by ZehMatt** [comment]
What I'm working on is basically generating COFF files out of the CodeHolder, I'm having some difficulties regarding relocations and its not ready yet but you would want to do probably the same if you like to support cross platform support.

**Comment by AndroDevcd** [comment]
got it thanks!
