### ISSUE TITLE
Why x86::Compiler extends EmitterExplicitT?

### ISSUE THREAD

**Issue by ZQiu233** [asmjit/asmjit#278]
Why x86::Compiler extends EmitterExplicitT while x86::Builder and x86::Assembler extends EmitterImplicitT?

Is there any reason for x86::Compiler should not use implicit opcode?

**Comment by kobalicek** [comment]
The compiler needs to know all registers used by each instruction for RA purposes - it would not work with implicit registers, that's the reason all registers must be given.

**Comment by ZQiu233** [comment]
> The compiler needs to know all registers used by each instruction for RA purposes - it would not work with implicit registers, that's the reason all registers must be given.

Can you give further information about "RA"?

**Comment by kobalicek** [comment]
Yeah RA==RegisterAllocator - the purpose of Compiler is to allocate registers, so it has to know everything about instructions and their operands

**Comment by ZQiu233** [comment]
> Yeah RA==RegisterAllocator - the purpose of Compiler is to allocate registers, so it has to know everything about instructions and their operands

I don't think there're ways to specify any actual register argument to instruction like "cpuid".
Does it mean that any virtual register specified to instruction like this will always be converted to the same registers at last?

**Comment by kobalicek** [comment]
Well, you specify virtual registers that will be allocated in specific physical registers for instructions where the registers are implicit and not part of the encoding. There is plenty of instructions where this is the case in addition to cpuid, like mul/div/shift/etc...

**Comment by ZQiu233** [comment]
OK, I got it, thanks a lot.
