### ISSUE TITLE
In which case will jmp(Label) emit E9 04 04 04 04

### ISSUE THREAD

**Issue by ZQiu233** [asmjit/asmjit#279]
I'm writing a managed wrapper named "AsmJit.NET" for asmjit.
When I tried to emit a jmp which jumps to a label I got "E9 04 04 04 04".
I guess it indicates that the label is invalid and tried to get the error of jmp(Label).
To my surprise, the error code is **kErrorOk**.
I don't know what's wrong with it.Here's my test code:
```C#
CodeInfo info = new CodeInfo(ArchInfo.Id.kIdX86);
CodeHolder holder = new CodeHolder();
holder.Initialize(info);
Assembler asm = new Assembler(holder);
Label l1 = asm.NewLabel();
var err = asm.jmp(l1);
Console.WriteLine("ErrorCode:{0}", err);
Console.WriteLine("Code Length:{0}", holder.Sections[0].Buffer.Size);
byte* b = holder.Sections[0].Buffer.Data;
for (int i = 0; i < holder.Sections[0].Buffer.Size; i++)
{
	Console.Write("{0:X2} ", *(b + i));
}
asm.Dispose();//equivalent to delete;
holder.Dispose();
info.Dispose();
```

**Comment by kobalicek** [comment]
The reason is that the label is not bound - in that case asmjit stores the size of the label in the displacement byte or bytes (usually it would be either 0x01 or 0x04040404).

**Comment by ZQiu233** [comment]
It works, thanks a lot.
