### ISSUE TITLE
MESA driver for Libre SoC could use parts of AsmJIT

### ISSUE THREAD

**Issue by dumblob** [asmjit/asmjit#280]
Any devs who'd like to get paid for RISC-V support in AsmJIT? Then might be a way:

http://lists.libre-riscv.org/pipermail/libre-riscv-dev/2020-January/003302.html

See also https://github.com/blend2d/blend2d/issues/66#issue-574576722 .

**Comment by kobalicek** [comment]
I really don't see how asmjit can be helpful in this case. MESA uses LLVM already, which is the right tool for the job actually as it provides really great optimizations and have already support for many architectures.

I think this can be closed.

**Comment by dumblob** [comment]
It was meant as an underpinning issue to https://github.com/blend2d/blend2d/issues/66 , but feel free to close this.

**Comment by kobalicek** [comment]
Yeah okay, I'm closing, I think one issue is enough in this case.
