### ISSUE TITLE
Issue in Vec::xmm/ymm/zmm

### ISSUE THREAD

**Issue by jspark1105** [asmjit/asmjit#281]
In
https://github.com/asmjit/asmjit/blob/304bf43a23607839eacf5b04a1bdb78568ae7b3f/src/asmjit/x86/x86operand.h#L384
we should return Xmm(id()) instead of Xmm(*this, id())?

I think this is causing the issue in https://github.com/pytorch/FBGEMM/pull/361

**Comment by kobalicek** [comment]
Thanks, no idea how this happened, it's a bug.
