### ISSUE TITLE
Trouble with calls that involve doubles in 32-bit build only

### ISSUE THREAD

**Issue by Chlumsky** [asmjit/asmjit#285]
I have implemented comprehensive expression evaluation using AsmJit and everything seemed to work fine up until the point I compiled the 32-bit version of my project. For some reason, emitting a call to function with a `double` return value such as

```c++
double __cdecl sqrt(double x);
```

works perfectly fine in the 64-bit build, but **sometimes** does not work in 32-bit, specifically, it throws a write access violation. As long as I only call functions with `int`, `float`, pointers, etc., there is no problem. However, this doesn't happen always, so I spent a lot of time making a minimal example to reproduce this, because any slight change suddenly makes it work. The following should compile and evaluate the expression `sqrt(double(sqrt(float(81))))`:

```c++
#include <cstdio>
#include <cmath>
#include <asmjit/asmjit.h>

int main() {
    asmjit::JitRuntime jitRuntime;
    asmjit::CodeHolder codeHolder;
    asmjit::x86::Compiler compiler;

    codeHolder.init(jitRuntime.codeInfo());
    codeHolder.attach(&compiler);
    compiler.addFunc(asmjit::FuncSignatureT<void, void *>());
    asmjit::x86::Gp outputPtr = compiler.newIntPtr();
    compiler.setArg(0, outputPtr);

    asmjit::x86::Mem tmp = compiler.newStack(8, 4);
    asmjit::x86::Mem tmpFloat = tmp;
    tmpFloat.setSize(sizeof(float));
    asmjit::x86::Mem tmpDouble = tmp;
    tmpDouble.setSize(sizeof(double));
    float inputVal = 81.f;
    compiler.mov(tmpFloat, *reinterpret_cast<const int *>(&inputVal));
    {
        asmjit::x86::Xmm retValue = compiler.newXmmSs();
        asmjit::x86::Xmm argValue = compiler.newXmmSs();
        compiler.movss(argValue, tmpFloat);
        asmjit::FuncCallNode *call = compiler.call(asmjit::imm(&sqrtf), asmjit::FuncSignatureT<float, float>());
        call->setRet(0, retValue);
        call->setArg(0, argValue);
        compiler.movss(tmpFloat, retValue);
    }
    compiler.fld(tmpFloat);
    compiler.fstp(tmpDouble);
    {
        asmjit::x86::Xmm retValue = compiler.newXmmSd();
        asmjit::x86::Xmm argValue = compiler.newXmmSd();
        compiler.movsd(argValue, tmpDouble);
        asmjit::FuncCallNode *call = compiler.call(asmjit::imm(static_cast<double (*)(double)>(&sqrt)), asmjit::FuncSignatureT<double, double>());
        call->setRet(0, retValue);
        call->setArg(0, argValue);
        asmjit::x86::Mem outputVal = asmjit::x86::ptr(outputPtr);
        outputVal.setSize(sizeof(double));
        compiler.movsd(outputVal, retValue);
    }
    
    compiler.endFunc();
    if (asmjit::Error err = compiler.finalize())
        return err;

    void (*fn)(void *);
    jitRuntime.add(&fn, &codeHolder);

    double doubleResult;
    fn(&doubleResult);
    printf("Returned %g, expected %g\n", doubleResult, sqrt(double(sqrtf(inputVal))));
    return 0;
}
```

The faulty code that is generated is:

```asm
.section .text {#0}
L0:
sub esp, 24
mov eax, dword [esp+28]
mov dword [esp+8], 1117913088
movss xmm0, dword [esp+8]
movss dword [esp], xmm0
mov dword [esp+20], eax
call 3322525 ; float sqrt(float);
fstp dword [esp+16]
movss xmm0, dword [esp+16]
movss dword [esp+8], xmm0
fld dword [esp+8]
fstp qword [esp+8]
movsd xmm0, qword [esp+8]
movlps qword [esp], xmm0
call 3326230 ; double sqrt(double);
fstp qword [esp+16]
movsd xmm0, qword [esp+16]
mov eax, dword [esp+20]
movsd qword [eax], xmm0
L1:
add esp, 24
ret
```

Interestingly, in this case, the error is `Access violation writing location 0x40080000.` while `0x4008000000000000` is the binary representation of 3.0, which is the resulting value, so the output pointer might have gotten overwritten with the double? Could this be related to calling conventions? Maybe I'm doing something wrong?

Also, attempting to emit the instruction `cvttsd2si` crashes for me on 32-bit only, and I can't seem to be able to use the version of this instruction with `DWORD` output (I suspect the opposite is true for `cvttss2si` making it not possible to directly convert `float` to `int64_t`), but I have circumvented that by replacing it with a function call.

**Comment by Chlumsky** [comment]
I think that the output pointer is stored at `[esp+20]`, but it got overwritten by `fstp qword [esp+16]` after the last function call? I didn't put in the `fstp` though, so I don't think I could have prevented it.

**Comment by kobalicek** [comment]
Thanks! With the code I can repro the problem on my Linux machine as well. I will try to fix this now.
