### ISSUE TITLE
Jump to address in memory

### ISSUE THREAD

**Issue by Chlumsky** [asmjit/asmjit#286]
What I need to do is store a label's address into memory and then, at a later point, read that address back from memory and jump to it. I thought the first half was going to be the hard part since the label doesn't have an address at this point and isn't even bound yet, but surprisingly this worked without any issue: (Is there a better way without the `lea`?)

```c++
void storeLabelAddress(x86::Compiler &compiler, x86::Mem &dst, const Label &label) {
    x86::Gp address = compiler.newIntPtr();
    compiler.lea(address, x86::ptr(label));
    compiler.mov(dst, address);
}
```

However, I then realized that I am unable to emit the actual jump instruction. Even though the compiler class has a `jmp` function that accepts `Gp` and `Mem`, if I try to use it, `finalize` returns `kErrorInvalidState`. According to [[1]](https://www.felixcloutier.com/x86/jmp), a version of the JMP instruction that accepts a register or memory operand exists, so this should be possible.

P.S. I am done after I solve this problem, so I promise this is the last issue. :)

**Comment by kobalicek** [comment]
This is actually not that easy as it seems. Since the Compiler's RAPass does control flow and liveness analysis it needs to know all possible targets of the jump. The control flow and liveness analysis is well prepared for this scenario, but not rest of the code.

Basically when a compiler sees such jump, like `jmp rax`, it doesn't know the target, it cannot add any descendants to the basic-block, which also means that it cannot do liveness analysis properly. It would be possible to somewhat assume that any label could be a target, but that would be also very inefficient, basically a worst-case scenario.

The following has to be done to support this feature:
  - There needs to be something like `ZoneVector<TargetNode*>` for every jump that jumps to unknown
  - The register allocator may need some fixes as well, but I would say not that much
  - Maybe, to make this simpler, introduce something like a jump table.

I'm not sure when I can focus on this to be honest, I will try to find some time, but no ETA.

**Comment by Chlumsky** [comment]
Thank you for the reply and for quickly resolving the other issues I have posted.

So the problem is that the register allocator wouldn't know the contents of registers after the jump, right? I have found that in my scenario, I never have more than 8 instances of `asmjit::x86::Gp` at the same time. Does that guarantee that the register allocator will never spill any registers to memory?

The reason I'm asking is that I've already devised a way to patch in the `jmp` instruction directly into the binary representation of the function after it is generated. Now I'm not sure though if that is safe to do, or if it can result in registers containing wrong data. Only 5 of my `Gp`'s are used globally throughout the function and need to survive the jumps, is there a way to mark them for the register allocator as "unspillable"? Or could I perhaps bypass the register allocator altogether and use fixed register names? (I'm not sure if this works with `BaseCompiler::setArg`, since I think function arguments need to be in specific registers?)

You mentioned an inefficient worst-case scenario solution. I think it would work OK for me due to the low number of registers used. Would that also be hard to implement? Do you have any other ideas how I could workaround this?

**Comment by Chlumsky** [comment]
Alright, I though this would be just a simple fix with adding the appropriate JMP instruction, but since it is this complex of an issue, don't worry about it. I think I will be able to restructure the whole thing to use function calls instead.

However, when I was experimenting with what I mentioned in my last post, I tried pushing the "global" registers before each unsafe jump and popping them right after, but the sequence of the 5 `pop` instructions generated:

```asm
pop rsp
pop rsp
mov qword [rsp+72], rsp
pop rsp
pop rsp
pop rsp
```

This is clearly wrong since it overwrites the stack pointer but still tries to use it to store data on the stack. Replacing `pop` with `nop` correctly shows 5 different registers/memory locations, none of which is `rsp`. Could this be another bug?

**Comment by kobalicek** [comment]
I will definitely check out how to add some support for this in the upcoming weekend.

**Comment by Chlumsky** [comment]
Actually, I think I came up with a way to trick the compiler that seems to work without any issues, although it's a hack.

Each of the jumps is generated like this:

```c++
Label memoryJumpInstruction = compiler.newLabel();
compiler.bind(memoryJumpInstruction);
compiler.nop(jumpAddress); // this will be changed to JMP after compilation
compiler.jmp(jumpTargetHub); // this will become unreachable but AsmJit doesn't know it
memoryJumpInstructions.add(memoryJumpInstruction);
```

Then at the very end, after `ret`, I do this:

```c++
compiler.bind(jumpTargetHub);
for (Label &target : allPossibleJumpTargets)
    compiler.jz(target); // conditional jump so that the following targets seem reachable
```

The part after `jumpTargetHub` label actually never gets executed, but should make the compiler think that any of the possible jump targets can be reached after the jump. Of course, once the function is compiled, I patch all the NOP instructions pointed to by `memoryJumpInstructions` with JMP in binary.

**Comment by kobalicek** [comment]
I would not do that. I looked into this and I'm pretty far to support this out of box.

**Comment by kobalicek** [comment]
I'm wondering whether you can test that branch. It's an initial implementation, so I have no idea whether it would work on something more complex - maybe you will hit an assert quickly, but it's designed in a way so the Compiler knows what's happening and how to approach it. I will think about a possibility to specify which labels are possible targets, because this implementation pessimistically makes all labels except the function's entry possible targets, which ruins the CFG totally.

**Comment by Chlumsky** [comment]
Alright, I've only gotten around to it now (sorry), but I checked it out and it works. The performance of the generated code seems to be roughly the same so that's nice.

However, the performance of the compilation itself is significantly worse - maybe an order of magnitude slower. This is the most important aspect for me, so at this point I will stick to the solution I mentioned earlier. A typical function I am compiling ends up taking ~400 kB and has ~2000 labels (only a few of those are possible targets of the memory-based jumps).

Also, it is now not possible to build the library with `ASMJIT_NO_LOGGING`.

**Comment by kobalicek** [comment]
@Chlumsky That was just an initial implementation, I have updated the branch to allow for using annotated jumps. You can do the following now:

```c++
      JumpAnnotation* annotation = cc.newJumpAnnotation();
      annotation->addLabel(L_Add);
      annotation->addLabel(L_Sub);
      annotation->addLabel(L_Mul);
      annotation->addLabel(L_Div);
      cc.jmp(target, annotation);
```

Let me know whether this works better. I have also fixed the compilation issue with disabled logging.

**Comment by Chlumsky** [comment]
I'm sorry, but there is no difference. The compilation takes over 2 seconds up from 0.15.

**Comment by kobalicek** [comment]
Can you give it another try? I rushed it and the initial approach was never working.

**Comment by Chlumsky** [comment]
Alright, now it's perfect. 👍 It's still very slightly slower than my workaround but I can live with it.

**Comment by kobalicek** [comment]
Do you have any numbers about how much?

**Comment by Chlumsky** [comment]
Well, for my largest test case, the compilation was originally 0.16 seconds and now is about 0.21 seconds. After I divided the jumps into several `JumpAnnotation`s instead of using just one, it went back to 0.16, but I didn't try the same optimization for my original version, so it probably would have been faster as well.

**Comment by kobalicek** [comment]
Fixed by https://github.com/asmjit/asmjit/commit/e78bba83da7fed4d8d3d5ed87cd23d64d9fcbb55

Thanks!
