### ISSUE TITLE
Documentation for hasBaseOrIndex()

### ISSUE THREAD

**Issue by christophhart** [asmjit/asmjit#287]
Not the biggest issue in the world, but the documentation for this method seems to be copy and pasted over from the hasBaseAndIndex method without adjustment

```cpp
//! Tests whether the memory operand has BASE and INDEX register.
```

**Comment by kobalicek** [comment]
Thanks, I will fix that. Definitely copy/paste :)

**Comment by kobalicek** [comment]
Fixed, Thanks!
