### ISSUE TITLE
Multiple JitRuntime (concurrent threads) in one process

### ISSUE THREAD

**Issue by ykim362** [asmjit/asmjit#288]
Hi,

I have question about JitRuntime.
In my multi-threaded program, I have JitRuntime as a static thread-local variable.

I expected that the multiple JitRuntimes run concurrently, but it seems only one JitRuntime is running at a given time.

Could you let me know if running multiple JitRuntime is possible and what I need to change?

https://github.com/marian-nmt/FBGEMM/blob/youki/unordered_map/src/GenerateKernel.h#L164

Thank you in advance.

**Comment by kobalicek** [comment]
Hi @ykim362,

`JitRuntime` is thread-safe, so you can either share a single instance between multiple threads or let each thread has its own. To be honest I have never tried to make it `thread_local` - the locking in JitRuntime is minimal, basically only to find free memory when a function is added to it, or to mark memory as unused when a function is removed.

I would ask whether you are trying to solve a particular problem, like you know a single `JitRuntime` is slow, etc

**Comment by ykim362** [comment]
Thanks @kobalicek .
In my use case, the machine has 24 CPU cores and 20 independent threads are using `JitRuntime`. And, the CPU utilization is very low. (Seems only one `JitRuntime` is running at a time). In the FBGEMM implementation, `JitRuntime` is a `static `variable. https://github.com/marian-nmt/FBGEMM/blob/master/src/GenerateKernel.h#L163 . So, I thought it might be because of that, and I changed it to `static thread_local ` . But, still CPU utilization is quite low. (Ideally 2000%, but I only see 250%).
I wondered if I had to use `JitRuntime` in a different way to increase the cpu utilization.

**Comment by kobalicek** [comment]
It's not enough to just make `JitRuntime` thread_local - you need to utilize those cores for code generation, if this is what you are doing - what I mean is - there is Assembler/Compiler or some emitter that generates code, this has to be multithreaded - and code generation takes much more time then JitRuntime::add/release. So I would definitely first try to utilize cores for code generation, and then, if there is a problem with contention while using JitRuntime, then I would try to use thread_local or something else.

**Comment by ykim362** [comment]
Yes, CodeGen (emitter) is also `static thread_local`. So, all the threads generate their own code and run. And, generated code is cached and never released until the program ends. It seems there's a limited number of threads are running.  Thanks for the information! I will look into the other part of the code.

**Comment by ykim362** [comment]
Thanks so much for the help, @kobalicek !
I found the issue causing the poor CPU utilization in the upper layers.
Asmjit works perfectly fine with `thread_local` and concurrent threads.
