### ISSUE TITLE
CMOV and other instructions not working now with constant value

### ISSUE THREAD

**Issue by crazynds** [asmjit/asmjit#289]
I have a project that used the asmjit library, however when updating the library some instructions that use constant values ​​are not working like the cmove statement (rax, 10);
and mul (5);
Have these usage functions been withdrawn?

**Comment by kobalicek** [comment]
Can you elaborate a bit? There are no immediate forms of `cmov` and `mul` - this should have never worked like that.

**Comment by crazynds** [comment]
Using the version of asmjit that is installed in the project, the following code compiles without errors.
![image](https://user-images.githubusercontent.com/36674096/85207937-c08d1780-b302-11ea-8882-d9b7bfd9a261.png)

When using the latest version in the git repository, errors appear in the compiler related to these lines of code.

**Comment by crazynds** [comment]
OK, I found my mistake. These instructions shouldn't even exist, even though using the old version of asmjit it doesn't show any errors in the compiler.
