### ISSUE TITLE
Add CMake "Export" files to install

### ISSUE THREAD

**Issue by kbrowder** [asmjit/asmjit#290]
It would be nice if find_package(asmjit) could find an install and add the appropriate include dir when you link against it.

**Comment by kobalicek** [comment]
I didn't forget about this, it's a good idea to have it, I just haven't tried the PR branch yet.

**Comment by kobalicek** [comment]
@kbrowder Do you think you can check out the related branch? I did a bit more than you and I also added namespace to the export. I tested it locally and it seems to work.

**Comment by kbrowder** [comment]
@kobalicek apologies for the delay this looked good to me thanks 👍

**Comment by kobalicek** [comment]
It's okay I just have more branches and projects and I needed to rebase :)
