### ISSUE TITLE
`x86::rax` and friends declared as `Gp` instead of `Gpq`

### ISSUE THREAD

**Issue by vogelsgesang** [asmjit/asmjit#292]
I realized that `x86::rax` and friends are declared as `Gp` instances, although the more specific `Gpq` would be available.
This seems inconsistent with, e.g., `ymm` and friends which use the `Ymm` class and thereby prefer the more specific class over the more generic `Vec` class.
Is this an oversight which could be changed or is this by design?

My motivation:
I ran into this while building a templated quick-and-dirty register allocator. This register allocator is instantiated once for the `Gpq` registers (for all integer values in my programs) and once for the `Xmm` registers (for all double precision values).
I now can't use the `reserveSpecificRegister(x86::rdx)` call (as required e.g. for multiplication/division), because the `reserveSpecificRegister` would expect a `Gpq` parameter, but rdx is only a `Gp` instance.
It would be great if rdx etc. were `Gpq` instances instead

Cheers,
Adrian

**Comment by kobalicek** [comment]
This is true, and I actually remember why I kept only `Gp` types a while ago. The reason was that for example `x86::Gp arg = is32Bit ? x86::ecx : x86::rdx` doesn't work when the registers are of different C++ types, so that's basically why the provided registers have the generic type.

I will think about this, but I'm unsure whether to change it now as this could potentially break a lot of existing code.

**Comment by vogelsgesang** [comment]
Thanks for providing that detailed reasoning! I see how changing this can break existing code and might not be viable

An alternative solution for my particular issue would be to add an additional entry to `RegTraits`.
Right now, `RegTraits<BaseReg::kTypeGp64>::RegT` is `Gpq`.
An additional `RegTraits<BaseReg::kTypeGp64>::LiteralRegT` which would be defined as `Gp` would allow me to adjust the signatures of my templated register allocator accordingly.

Not sure if that solution is actually a good idea, though.
It feels like a workaround to me, and it seems to be less clean than changing the types of `rax` and friends to `Gpq`

**Comment by kobalicek** [comment]
I will review this once more, I'm currently working on AArch64 support and there the registers have correct types, and it seems fine. It would be a breaking change though.
