### ISSUE TITLE
Address table breaks if it's not the last section

### ISSUE THREAD

**Issue by jhogberg** [asmjit/asmjit#293]
Hi!

I've run into a strange issue where the address table doesn't work unless it's the last section. As far as I can tell this is due to its size only being set if it's the [last section](https://github.com/asmjit/asmjit/blob/8474400e82c3ea65bd828761539e5d9b25f6bd83/src/asmjit/core/codeholder.cpp#L1049-L1054), otherwise it stays at 0 and doesn't get copied over.

Here's a quick reproducer:

```c++
static int some_function() {
    return 1234;
}

void test() {
  Section *dummy = nullptr;
  x86::Assembler a;
  CodeHolder code;
  JitRuntime rt;
  Func fn;

  code.init(rt.environment());
  code.attach(&a);

  a.jmp(imm(some_function));

  /* Everything works fine without this. */
  code.newSection(&dummy,
                  "dummy",
                  SIZE_MAX,
                  Section::kFlagConst,
                  8);

  rt.add(&fn, &code);

  printf("%d\n", fn());

  rt.release(fn);
}
```

**Comment by kobalicek** [comment]
You are right. I think this can be solved by adding priority to the section so address table would always end last. I will be able to solve this most likely on Monday as I'm out over the weekend and I'm not sure I would be able to fix/test it now.

**Comment by kobalicek** [comment]
@jhogberg Sorry for delay. I have added section ordering in the linked branch. Can you verify it fixes the issue for you?

**Comment by kobalicek** [comment]
Should be fixed on master.

**Comment by jhogberg** [comment]
Thank you, it works! :)
