### ISSUE TITLE
Use `.byte` directive for constant data instead of `db`

### ISSUE THREAD

**Issue by vogelsgesang** [asmjit/asmjit#295]
I am currently trying to feed asmjit's log (i.e. the generated assembly) as input into `gcc`/`clang`.
For most of asmjit's log output this works just lovely. But for embedded data (`embedUInt64` etc.), the line

> db 000102FF

is not accepted by gcc/clang. Instead they would expect

> .byte 0x00,0x01,0x02,0xFF

Afaict, the code which would need adjusting is in [Logger::logBinary](https://github.com/asmjit/asmjit/blob/0e04695f64028034b1376ecf577592992e8552fc/src/asmjit/core/logger.cpp#L63) and would be pretty simple to change.

Would it be possible to change asmjit's logging of constants such that it is directly consumable by gcc/clang?
Or is the `db`-style for constants necessary for compatibility with some other compiler?

My motivation to use `clang`:
For debugging purposes I would like to get a `.so` file for the assembly I generated. And calling clang seems to be the simplest way to get such a `.so` file

**Comment by kobalicek** [comment]
This would be possible although the logging would be a bit more noisy. I would like to warn you that logging was not designed to provide output for third party assemblers - it's provided so the users can see what the assembler encounters as it could get messy sometimes. So the priority in logging is to display everything regarding the instruction and its operands as AsmJit uses it.

**Comment by ZehMatt** [comment]
I would argue that db is far more common, Nasm, Yasm, Fasm, Masm all go with 'db' and they are the most used assemblers I believe.

**Comment by kobalicek** [comment]
I have made it simpler to change this in the future, but at the moment I would like to keep .db, .dw, .dd, and .dq for x86/x86_64 targets.

Clang uses .byte, .short, .long, and .quad for x86/x86_64 targets, while GCC uses .byte, .value, .long, and .quad, so even these two compilers are not compatible in their outputs. I would like to keep DB, DW, DD, and DQ as I think that on x86/x86_64 this is just more standard - it seems to me that LLVM/GCC naming follows more AT&T than nasm/yasm.
