### ISSUE TITLE
Emitting `rip`-relative label addresses

### ISSUE THREAD

**Issue by vogelsgesang** [asmjit/asmjit#296]
I would like to use `rip`-relative addressing in combination with a not-yet-bound Label.
From [the documentation](https://asmjit.com/doc/group__asmjit__x86.html#gacf0d5836a668238696d1a76adcb39274) it seems that `rip`-relative addressing is only available if I already know the exact byte offset of my target label.

I was wondering what it would take to make rip-relative addressing also work in combination with Labels.
I guess one would need some new "link type"/"relocation type"?

E.g. for negating a double, I am currently generating code of the form

>    xorps xmm0, [neg_pattern]
> ... somewhere much later ...
> neg_pattern:
> db 00000000000000800000000000000080

but instead I would need to emit a

> xorps xmm0, [rip + neg_pattern]

**Motivation**:
I am trying to generate a position-independent, shared library with asmjit for Linux.
As far as I know (and I might be completely wrong here; currently still figuring out what "position-independent" actually means), this means I cannot use instructions like `xorps xmm0, [L3]` because those would need relocations inside the `.text` segment and those are not allowed for position-independent shared libraries.

**Comment by kobalicek** [comment]
AsmJit would always encode the address as relative in 64-bit mode. For example:

```c++
Label L = assembler.newLabel();
assembler.mov(xmm0, x86::ptr(L));
assembler.bind(L);
```

In 32-bit mode there will be relocation (resolved in `relocateTo()`), because there is no relative addressing. However, in 64-bit mode it will be encoded by using a relative displacement (rip + offset) . AsmJit uses the same operand for both scenarios - it's a memory operand with a label as a base. And then Logger just serializes the content of such operands - so in log it appears as [L] but in practice it's encoded as [rip + L] in 64-bit mode.

**Comment by vogelsgesang** [comment]
> And then Logger just serializes the content of such operands - so in log it appears as [L] but in practice it's encoded as [rip + L] in 64-bit mode

Ah, so this is where my confusion came from.
Would it be possible to adjust the logger to make the rip-relative indexing explicit?
I.e. use `[rip + L]` instead of `[L]`?

I actually stumbled across this while trying to feed asmjit's log output into clang (also see #295).
In case you agree, that the general approach of "feed asmjit's log into clang" is useful/desirable, I think adapting the logging for rip-relative labels would be useful.

(Also, it would have saved me the time reading through docs/source code in order to see how to get asmjit to emit rip-relative code...)

In any case: thanks for this great library and also for your quick responses! :)

**Comment by kobalicek** [comment]
That would be tricky - I think it would be possible to display [rip + L] in case that the memory address was explicitly made relative (by either ptr_rel or marked through Mem API). At the moment such override looks like `lea rax , [abs L]` and `lea rax , [rel L]`

**Comment by vogelsgesang** [comment]
to close the loop on this:
I went with the following approach:
* explicitly set all memory accesses to relative, to they have the from `[rel L]`
* simple string replacement "[rel" -> "[rip +"

It's hacky, but it works :)

Thanks for your help!
Without the hint towards explicitly marking the addresses as relative, I would probably have not been able to find this trick...

**Comment by kobalicek** [comment]
Closing as I think the current behavior is OK.
