### ISSUE TITLE
`_finalStackSize` uninitialized?

### ISSUE THREAD

**Issue by vogelsgesang** [asmjit/asmjit#297]
maybe I am missing something obvious, but it seems that the `Frame::_finalStackSize` returned by `Frame::finalStackSize` is never actually set...

**Comment by kobalicek** [comment]
Yeah this is true. I have already fixed this in my AArch64 port. Thankfully it's not used anywhere in the code so it doesn't break AsmJit itself.

Resolution: Will be fixed when merging changes required to merge AArch64 port.

**Comment by vogelsgesang** [comment]
same for `_callStackSize` 😢 

But I guess you also already fixed that on the AArch64 port

**Comment by kobalicek** [comment]
CallStackSize must be set by the user - it means how many bytes the function should reserve for function calls. Leaf functions have CallStackSize always zero, however, non-leaf functions may have it non-zero if required either by the calling convention or in case the function requires additional stack for the call (or both).

**Comment by vogelsgesang** [comment]
makes sense... it seems I misunderstood the docs on the stack setup...

What I was actually looking for, was the overall number of bytes by which the prolog modifies `rsp`, since I would need that number to generate an `eh_frame` section for my function (i.e., I needed the number I can pass to the `.cfi_def_cfa_register` directive).

By now, I realized that my approach was flawed anyway, since I also need to emit `.cfi_offset` directives which will tell the debugger the exact spill locations, and that would need more information than exposed by asmjit right now

Is generating `eh_frame`-information (such that C++ code can throw exceptions through code generated by asmjit) something which would be in-scope for asmjit?

**Comment by kobalicek** [comment]
This should get fixed by https://github.com/asmjit/asmjit/commit/cd44f41d9b34ed4bd5f2ea2da5ed460d52bd1134

Sorry that I haven't answered the question. I think generating EH frames is out of scope of AsmJit at the moment, but I would like to provide you all the information that you would need to actually be able to generate it. Would you open another issue where we can discuss this?
