### ISSUE TITLE
Extended Family Id calculation incorrect

### ISSUE THREAD

**Issue by marenz2569** [asmjit/asmjit#298]
Looking at the family id using the builtin functions of asmjit on a Bulldozer system resulted in 111 instead of 21.

Intel does not use the extended family id except for Presler (65nm) and Prescott (90nm) according to [this intel website](https://software.intel.com/content/www/us/en/develop/articles/intel-architecture-and-processor-identification-with-cpuid-model-and-family-numbers.html).
The description of the calculation in the Intel Instruction Set Extension and Future Feature Programming Reference looks somewhat counter-intuitive to me.
AMD however in their Processor Programming Reference has a clear explanation.
As Intel only uses the extended family id for two old architecture I suggest following the AMD manual.
I do not have any Presler or Prescott system to test this on.

I will make a pull request for this change.

Kind regards.

**Comment by kobalicek** [comment]
I'm wondering, can this be confirmed somehow that the changes work on both Intel and AMD?

**Comment by marenz2569** [comment]
The [linux kernel implementation](https://github.com/torvalds/linux/blob/296d05cb0d3c9f4648e31abb8ce404ac6915d66c/arch/x86/lib/cpu.c) is the same as the one I have suggested.
These properties are important for the project I am working on, as we have to differentiate between different payloads for different micro-architectures. The payloads are not just dependent on the supported x86 extensions.
