### ISSUE TITLE
`commentf` formats its parameters, even if no logger is attached

### ISSUE THREAD

**Issue by vogelsgesang** [asmjit/asmjit#306]
While trying to speed up my code which interacts with AsmJit, I just realized that `commentf` is not cheap, even if no logger is attached. `commentf` still formats its parameters into a string.
`commentf` is currently taking up 7% of the time it takes me to emit my assembly snippet.

I could wrap each call to `commentf` into an `if (a.hasLogger())` check, but I think code would stay more readable if `commentf` wouldn't even do the string formatting, as long as no logger is attached.

My first idea would be: let `emitter::commentf` and `emmitter::commentv` check `emitter::hasLogger()` and skip the string formatting if there is no logger.

However, I am not sure if this is the correct way to go about it, because I am currently confused about the "comment" design:

It seems that the `BaseBuilder::comment` function currently does create a comment node, even if no logger is attached. Doing the change I proposed above would hence lead to `BaseBuilder::commentf` no longer creating a comment node, although it seems comment nodes are supposed to be independent of loggers...

But then again, `BaseBuilder::comentf` is a no-op if `ASMJIT_NO_LOGGING` is set, while `BaseBuilder::comment` still creates a comment node even if `ASMJIT_NO_LOGGING` is not set...

**Comment by kobalicek** [comment]
It's tricky.

As you have figured out, when you use `comment()` in a builder/compiler the emitter must emit the node as it doesn't know whether the comment will be used or not. It's questionable though whether the node should be emitted when `ASMJIT_NO_LOGGING` is defined. I think it shouldn't.
