### ISSUE TITLE
Does asmjit have a global state?

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#307]
I'm having a weird issue when a function compiled in a certain cpp file only emits first 256 bytes of it, which resembles initialization order fiasco. JitRuntime I use is initialized before it's used ("magic static"). I even wrote my own memory manager, but it didn't help. I can provide more info if necessary.

**Comment by kobalicek** [comment]
I'm not aware of any globals except the information about the host CPU, which is initialized on-demand. The initialization is here:

https://github.com/asmjit/asmjit/blob/master/src/asmjit/core/cpuinfo.cpp#L75

But you can provide more details if you have any.

**Comment by Nekotekina** [comment]
Thank you for confirmation. It appears it was a bug in my code that caused wrong function size to be reported.
