### ISSUE TITLE
How to emit call far/jmp far?

### ISSUE THREAD

**Issue by lifeengines** [asmjit/asmjit#310]
Is there a way to emit call far/jmp far instruction? I see in x64dbg disassembly `jmp far fword ptr ds:[rax]` are okay,but can't re-encode to bytecode.I did't figure out a way in code either.Is asmjit not support emit there instruction or I do something wrong?

**Comment by kobalicek** [comment]
far jmp/call are currently missing - I can add them, nobody really needed them so far I guess.

**Comment by kobalicek** [comment]
I will look into this, it shouldn't be problem to add few more instructions regarding far call/jmp
