### ISSUE TITLE
GetSize function returning bool

### ISSUE THREAD

**Issue by bit-hack** [asmjit/asmjit#311]
I just checked out `asmjit` master branch and compiled it along with the tests.  There is a suspicious warning in the compilation log however that I wanted to bring to your attention.

In the file `x86assembler.cpp` line 498 the function:
```
static ASMJIT_INLINE bool x86GetMovAbsInstSize64Bit(uint32_t regSize, uint32_t options, const Mem& rmRel) noexcept {
  uint32_t segmentPrefixSize = rmRel.segmentId() != 0;
  uint32_t _66hPrefixSize = regSize == 2;
  uint32_t rexPrefixSize = (regSize == 8) || ((options & Inst::kOptionRex) != 0);
  uint32_t opCodeByteSize = 1;
  uint32_t immediateSize = 8;

  return segmentPrefixSize + _66hPrefixSize + rexPrefixSize + opCodeByteSize + immediateSize;
}
```

It returns a `bool` but it looks like its intended to return the instruction length.  The usage site lower down seems to expect a sized type aswell.
```
...

        uint32_t instructionSize = x86GetMovAbsInstSize64Bit(regSize, options, rmRel);
        uint64_t virtualOffset = uint64_t(writer.offsetFrom(self->_bufferData));
        uint64_t rip64 = baseAddress + self->_section->offset() + virtualOffset + instructionSize;
...
```

It would be trivial to change the return type to `uint32_t` but I didnt want to start changing the code given that I am not familiar with it yet.

**Comment by kobalicek** [comment]
Good catch, thanks!
