### ISSUE TITLE
Dual-mapped allocations broken on some OS X versions 

### ISSUE THREAD

**Issue by jhogberg** [asmjit/asmjit#312]
Dual-mapped allocations fail on at least one OS X version: we've seen it on `Darwin 19.3.0`, but `Darwin 18.7.0` appears to work. 

Opening the shared memory file works, but `mmap(2)` fails with `EPERM` which the [documentation](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/mmap.2.html) doesn't mention.

I've noticed that it works fine if we delay the `unlink(2)` call until _after_ the call to `mmap(2)`, and while I can find no documentation relating to this, it might be a reasonable workaround.

**Comment by jhogberg** [comment]
As an aside, I noticed that the error code is not propagated to the caller of `JitAllocator::alloc`, it returns `kErrorOutOfMemory` regardless of why it fails.

**Comment by kobalicek** [comment]
Hi John,

I assume that if you compile asmjit with tests and run unit tests they would fail as well? Let me first add newest osx images on travis CI to see whether this can be reproduced at least on the CI infrastructure. I will take a look

**Comment by kobalicek** [comment]
The build is still running for some reason, so I will take a look tomorrow:
https://travis-ci.org/github/asmjit/asmjit/builds/741482570

**Comment by kobalicek** [comment]
I will take a look at `MAP_ANON` as well.

**Comment by jhogberg** [comment]
Thanks for the quick response!

> I assume that if you compile asmjit with tests and run unit tests they would fail as well?

Yep, they fail in the same spot as the CI run you linked. Let me know if you want me to test things out locally.

**Comment by kobalicek** [comment]
I have fixed it in https://github.com/asmjit/asmjit/tree/issue_312 branch - I have basically followed your observation that if i unlink the file after mmap() it's fine. However, this makes the time-frame somebody can open the file a bit larger.

To be honest I don't understand why this works on one version and stops working on another, maybe Apple is hardening it, no idea.

I will merge the branch soon, since I have discovered that TravisCI restricted OSS plans I would like to migrate to GH Actions, almost there.

**Comment by jhogberg** [comment]
> I have fixed it in https://github.com/asmjit/asmjit/tree/issue_312 branch - I have basically followed your observation that if i unlink the file after mmap() it's fine.

Awesome, thanks!

> To be honest I don't understand why this works in one version and stops working in another, maybe Apple is hardening it, no idea.

I wouldn't be surprised, Apple really likes adding mitigations though I have hard time seeing how this improves security. I can't say I have much of a clue either.

> However, this makes the time-frame somebody can open the file a bit larger.

I think an attacker who controls a user with sufficient permissions to force the file open has already won. The process could of course have capabilities that its user doesn't have (through something analogous to `setcap(8)`), but that feels a bit far-fetched.

It seems pretty easy to add a runtime check at first glance though, unlinking early when possible and deferring it when it isn't. I doubt it's worth the hassle but I can send a PR if you want.

**Comment by kobalicek** [comment]
Indeed! I wish they have just all implemented `SHM_ANON` so dancing around the tmp file would be totally unnecessary.
