### ISSUE TITLE
documentation typo on 'Compiler' page

### ISSUE THREAD

**Issue by wscott** [asmjit/asmjit#314]
I don't see the documentation source so I guess I have to file an issue. 

On https://asmjit.com/doc/group__asmjit__compiler.html in the first paragraph
"has more limitations that" should be "has more limitations _than_"

**Comment by wscott** [comment]
discovered the documentation is Doxygen so I will collect them locally and submit a pull request in the future.

**Comment by kobalicek** [comment]
Can you make the PR? It would be nice to correct the docs if possible :) Thanks!

**Comment by kobalicek** [comment]
I have fixed this one already, closing.
