### ISSUE TITLE
Need help with project

### ISSUE THREAD

**Issue by AndroDevcd** [asmjit/asmjit#315]
Hey asmjit dev. I was wondering if I would be able t get help regarding my programming language that I am building. I am getting undefined behaviorwhen code is jit'ed, however, I am not sure if it is the library causing some issues or my terrible x86 programming skills. I have been trying for months with not much progress and could really use a hand. I am even willing to go as far as provide a small compensation to help out in fixing the issue.  

As you know you have probably seen me around a bit using the project and asking various questions. However, it appears that I am at an inflection point. I am building a programming language that with the use of this library should provide a 10-15x in speed but it doesn't seem to have little to ay performance gains and even slower than the original code. The project is [Sharp](https://github.com/AndroDevcd/Sharp/tree/concurrency-jit), please let me know if there is anything you can do to help out. Thanks

**Comment by jhogberg** [comment]
>  I am getting undefined behaviorwhen code is jit'ed, however, I am not sure if it is the library causing some issues or my terrible x86 programming skills.

Have you tried using [mozilla rr](https://rr-project.org/)?

If you're unfamiliar with it, it lets you record debugging sessions for later replay and allows you to step backwards in time when debugging. For example if you've corrupted memory somewhere, you can replay it until the crash and then set a watchpoint on said memory before going backwards. It'll then stop right at the offending instruction.

I can't recommend it enough, the Erlang JIT would've taken months longer to implement without it.

**Comment by kobalicek** [comment]
@AndroDevcd I'm not able to help you with your project, however, I can help with dealing with #309 - but I would need more input from you, something that I can use to discover whether it's a bug in asmjit or not.

**Comment by AndroDevcd** [comment]
@kobalicek I have fixed the issue currently with the library. However, despite the library being able to compile the source code I am just getting undefined behavior most likely due to the fact that I have bugs where I am reading data the wrong way or something.
