### ISSUE TITLE
Existing object code?

### ISSUE THREAD

**Issue by progman1** [asmjit/asmjit#322]
hi
given ASMjit can goes from textual assembler to running code, can it also
ingest pre-assembled object code (file or memory) and link it in?
thanks.

**Comment by kobalicek** [comment]
No, it doesn't have the capability. In general asmjit can only link JIT code, but it doesn't understand relocations as provided by object files and dynamic libraries. Somebody would have to experiment and write the support.

Assembler parser is currently provided by a separate library called asmtk (it's not a core part of asmjit).

**Comment by progman1** [comment]
ok, thanks for that.
