### ISSUE TITLE
newLabel and newNamedLabel

### ISSUE THREAD

**Issue by januwA** [asmjit/asmjit#328]
Hi, I would like to ask what is the difference between newLabel and newNamedLabel, when should I use newNamedLabel?

❤️❤️❤️

**Comment by kobalicek** [comment]
Only use `newNamedLabel()` if you want to query that label later by its name. By default `newLabel()` creates an anonymous label, which cannot be queried by `CodeHolder::labelByName()` - named labels can.

**Comment by januwA** [comment]
@kobalicek  Thank you
