### ISSUE TITLE
compile errors occur when using cmake with vs2010 as generator

### ISSUE THREAD

**Issue by rocketion** [asmjit/asmjit#329]
I'm not familiar with cmake, so I choose CMake with GUI to generate VS project.
After I generated my asmjit project using VS2010 as the default generator, I encounter with lots of compile errors such as no declaration of constexpr which might be the imperfect support for C++11 of MSVC2010. Constrained to the working enviroment, I have no choice except for VS2010. It seems that those commits before 2019 work well, so if are there any solutions can help me deal with this kind of problem. Wish your applies.

**Comment by kobalicek** [comment]
I'm afraid I cannot fix this. AsmJit requires a C++11 capable compiler - if your compiler doesn't understand C++ constructs it won't compile it. Maybe you can fix constexpr somehow, but then most likely you will face other issues regarding C++11 support.

**Comment by kobalicek** [comment]
Closing.
