### ISSUE TITLE
Enhancement: Extend `newLabel` with a debug name

### ISSUE THREAD

**Issue by vogelsgesang** [asmjit/asmjit#333]
**Request**

I would love the `newLabel` function to take an additional parameter, a `debugName`.
The `newLabel` function would still always return a new label, even if another label with the same name already exists.
Creating two labels with the same `debugName` is not an error.
The `debugName` would serve no purpose, except for being printed as part of the label's name to the log.
E.g., instead of `L1`, the label would be called `L_<debugname>_1`.

What do you think about this functionality?

**Use case**

Writing my own code emitter on top of asmjit's assembler, I found myself using the following pattern quite frequently

```
Label lbl;
if (a.hasLogger()) {
   lbl = a.newNamedLabel(name.data(), name.length());
} else {
    lbl = a.newLabel();
}
```

My use case is:
* I don't need label names for correctness. I never need to retrieve a label by its name. I keep track of my labels through their `Label` handles.
* I still want to name my labels in the logged output, such that I have an easier time to understand/debug my code
* My scenario is highly focused on code generation times. The hashing/string copies inside `newNamedLabel` adds measurable overhead to my codegen times. As such, I am only willing to pay this overhead if I am indeed debugging my code, i.e. if I actually have a logger attached.

**Comment by kobalicek** [comment]
I'm not sure I understand the use-case:
  - If you want performance - you don't want logging at all as logging is actually much slower than the actual code generation.
  - If you want clarity / debugging - you can just name your labels and the hashing in newNamedLabel() shouldn't really affect you (because the logging has most likely much bigger overhead).

What I mean is that in release builds you would most likely not have logger attached at all (and maybe only give user the option to do so in case there is some issue). However, in debug builds, you most likely want to have logging enabled and used.

**Comment by vogelsgesang** [comment]
I agree with all of your reasoning and what I currently have implemented is very close to what you describe:

> [...] in release builds you would most likely not have logger attached at all and give the user the option to do so in case there is some issue)

In my case, I give the user an option to attach a logger, both in my release and my debug builds. (My release builds also have the logging infrastructure enabled. No `ASMJIT_NO_LOGGING`.) By default, there is no logger attached.

As you stated, I don't care about the overhead of the hashing in `newNamedLabel` if I am currently debugging my code. However, I do care about that overhead when I am not debugging. This is what lead me to the snippet

```
Label lbl;
if (a.hasLogger()) {
   lbl = a.newNamedLabel(name.data(), name.length());
} else {
    lbl = a.newLabel();
}
```

such that I am only paying the hashing overhead/string copying if I am actually debugging my code.

As I have many places which create labels, I had to duplicate this pattern in quite a few places. Given this is a general pattern, independent of my particular usage of AsmJit, I was wondering whether it is worth to add support for those "labels which debug names" directly into AsmJit and if others might also benefit from it.

(I don't have an overview of other people's use cases, though... so it might be that I am the only one so obsessed with code generation performance)

**Comment by kobalicek** [comment]
I think the feature request makes sense in the end, thanks for the explanation.

**Comment by vogelsgesang** [comment]
oh, since I forgot to mention:

A downside of my current approach

```
if (a.hasLogger()) {
   lbl = a.newNamedLabel(name.data(), name.length());
} else {
    lbl = a.newLabel();
}
```

is that `newNamedLabel` has a different semantics from `newLabel`: I must ensure that labels never accidentally have the same name. Otherwise the `newNamedLabel` would fail.

This means, I am currently appending an incrementing number to each of my label names.
In a sense, I really want the semantics of `newLabel` which internally already increments the number and creates labels `L1`, `L2`, `L3`, ...

That's why I proposed
> Creating two labels with the same debugName is not an error.
> The debugName would serve no purpose, except for being printed as part of the label's name to the log.
> E.g., instead of L1, the label would be called L_<debugname>_1.

**Comment by kobalicek** [comment]
I think this makes sense in the end, but I need to find a way to make this change nice and to not confuse users about having named anonymous labels.

**Comment by kobalicek** [comment]
I have done some work regarding this in `refactor` branch.

**Comment by kobalicek** [comment]
This functionality is now available via `newAnonymousLabel()`.

Closd by https://github.com/asmjit/asmjit/commit/996deae3273073bf75fbd6ddeac038dff5fdb6eb
