### ISSUE TITLE
Random copy paste bug in aarch64 branch in CMakeLists.txt

### ISSUE THREAD

**Issue by CuiCui66** [asmjit/asmjit#334]
Hi I have nothing to do with this project but I was scrolling randomly because I was interested. 

On the last commit (`b74ba0`) to the branch `aarch64` in the `CMakeLists.txt` at line 61 there is:
```
if (NOT DEFINED ASMJIT_NO_ARM)
  set(ASMJIT_NO_X86 FALSE)
endif()
```

Shouldn't it be:
```
if (NOT DEFINED ASMJIT_NO_ARM)
  set(ASMJIT_NO_ARM FALSE)
endif()
```

Because the unchanged line just above is:
```
if (NOT DEFINED ASMJIT_NO_X86)
  set(ASMJIT_NO_x86 FALSE)
endif()
```

Maybe you already fixed it and not merged it in yet in which case I'm sorry.

**Comment by kobalicek** [comment]
Thanks for the issue, good catch!
