### ISSUE TITLE
Save/Store work incorrectly for aarch64 Q Register

### ISSUE THREAD

**Issue by akkaze** [asmjit/asmjit#337]
I was using asmjit for writing math functions on aarch64 branch in Compiler mode.However, the compiler did not insert correct SAVE/LOAD instructions for q register when registers need to be spilled into memory.The SAVE/LOAD instructions the compiler inserted have incorrect size, I need it to insert ld1 and st1 for q registers, it actually insert ldr and str for d registers, which led to incorrect results.Can you fix it for aarch64

**Comment by kobalicek** [comment]
Please check out the latest, it should be fixed by now, thanks for reporting the issue!

**Comment by akkaze** [comment]
It has been fixed,now save/restore works correctly.But I find there is some other bugs, for example, ld1 and st1 instructions will lead to segmentation fault, can you fix it for me or how can I fix it by myself. I found that asmjit is really convenient for writting optimized math functions in compiler mode without writting assmebly, I am trying to use it in my daily work

**Comment by kobalicek** [comment]
I created a separate issue here: https://github.com/asmjit/asmjit/issues/338
