### ISSUE TITLE
asmjit should report error for invalid conditional instructions

### ISSUE THREAD

**Issue by Lyve1981** [asmjit/asmjit#341]
Unlike 32 bit ARM, 64 bit ARM does not allow conditional execution of instructions except for branches. However, something like this is accepted by the Builder:

`asm.cond_not_zero().lsl(gp, gp, asmjit::Imm(1));`

It even emits machine code and outputs assembly (grabbed from the logger)

`lsl.ne x15, x15, 1                          ; EFF97FD3`

However, this is not supported (the instruction is executed unconditionally) and should result in an error.

**Comment by kobalicek** [comment]
It should report an invalid instruction now. There is no dedicated error code for this error though.
