### ISSUE TITLE
How to read extern variable?

### ISSUE THREAD

**Issue by gamagan** [asmjit/asmjit#345]
Hello, 
I'm learning to use AsmJit and to write x86-64 assembly together by doing exercises in assembly and translating them to AsmJit. While following some book exercises, I hit a roadblock.
I'm trying to implement, in AsmJit, the code shown below. I was able to do it in raw ASM using MASM in MSVC.

I don't know how to accomplish the following 2 lines:
`extern g_Ch02_02_Val1:dword`
`add ecx, [g_Ch02_02_Val1]`

I've been reading the asmjit.com docs, but I can't find the answer.
Sorry if this is a dumb question.

One more question: 
Besides reading the docs page, https://asmjit.com/doc/index.html, can you recommend other approaches to learn AsmJit?

Thanks

```
extern g_Ch02_02_Val1:dword   ; external doubleword (32-bit) value

.code

; u32 IntegerLogical(u32 a, u32 b, u32 c,  u32 d)
;
; Calculate (((a & b) | c ) ^ d) + g_Ch02_02_Val1
IntegerLogical proc
    and ecx, edx                ; ecx = a & b
    or  ecx, r8d                ; ecx = (a & b) | c
    xor ecx, r9d                ; ecx = ((a & b) | c) ^ d
    add ecx, [g_Ch02_02_Val1]   ; ecx = (((a & b) | c) ^ d) + g_Ch02_02_Val1

    mov eax, ecx                ; eax = final result
    ret                         ; return to caller
IntegerLogical endp

end
```

**Comment by kobalicek** [comment]
It really depends on what you are trying to do. What you see in your asm example is consumed by both assembler and linker, but AsmJit only implements the assembler part - the linker it has is limited to just handle relocations / fixups that are mostly needed by JIT code generation.

If your variable is a constant, you can use a constant pool. If the constant is known at the moment you are compiling your C++ project, that constant pool could be defined in your C++ app as well as `static const var[] = {}` (just reference it via a pointer or function argument).

If the constant is a mutable global, then you need to handle the allocation of it, and again, pass its pointer either via a function argument or just embedding the pointer in the code.

For example this way you can create a dynamic global - of course you have to deal with the lifetime of the generated code and the global as well - but that's something that is out of scope of AsmJit.

```c++
void* myNewConstant = malloc(16);
x86::Assembler a = ...;

a.mov(x86::rax, myNewConstant);
a.add(x86::rax, 1);
```

**Comment by kobalicek** [comment]
I'm closing, if you feel it hasn't been answered properly, please reopen :)

**Comment by gamagan** [comment]
> I'm closing, if you feel it hasn't been answered properly, please reopen :)

Ok, so if I get a pointer to the extern variable, and then I'm generating some jit, how can I read from that pointer directly?

```
void Fn(u32* externVar) {
       // how to directly read from address of externVar using mov?
       // ...
      x86::mov(rax, dword_ptr(externVar)); // This type of thing
}
```

**Comment by kobalicek** [comment]
You need a pointer to that variable:

```
extern int variable;

assembler.mov(var_ptr, uintptr_t(&variable));

// do whatever with var_ptr, such as load.
assembler.mov(some_reg, x86::ptr(var_ptr));
```

**Comment by gamagan** [comment]
I'm sorry that I need to be spoon fed, but what is `var_ptr`?

**Comment by kobalicek** [comment]
A register like `Gp` (for example rax)

**Comment by gamagan** [comment]
Finally got it working. Thank you very much.
