### ISSUE TITLE
A question about arm assembler

### ISSUE THREAD

**Issue by nmanhong** [asmjit/asmjit#346]
In the arm's assembler, in the a64instdb file, there is a definition of the instruction code, but I found that some variables of the instruction are directly given, which I can't understand. For example, the adc instruction in the instruction file is 0b0001101000000000000000, but in the instruction manual, its 31-bit is an sf variable. This sf determines whether it is 32-bit or 64-bit. Why can it be directly defined as 0 in a64instdb

**Comment by nmanhong** [comment]
@kobalicek

**Comment by kobalicek** [comment]
There are bits that are changed by the assembler - these bits are always zero in the database - assembler then just flips them.

**Comment by nmanhong** [comment]
Thanks
I am learning this asmjit recently, but there are some places I don’t understand very well. In the InstInfo _instInfoTable table of the file a64assembler, there are several parameters that I can’t understand, for example
"INST(Adc, BaseRRR, (0b0001101000000000000000, kWX, kZR, kWX, kZR, kWX, kZR, true), kRWI_W, 0, 0 ,1 ),"
In this line, first, kW represents a 32-bit register, and kX represents a 64-bit register, but what does KWX represent? And this kRWI_W stands for read and write mode, what kind of read and write mode does it represent? I don’t know what role the nameDataIndex parameter has, it seems that there is no such thing in the INST macro.

**Comment by nmanhong** [comment]
@kobalicek

**Comment by kobalicek** [comment]
The first member is instruction name/id, then a encoding category, and then a specific data follow. There is a struct for each encoding, like:

```c++
struct BaseRRR {
  M_OPCODE(opcode, 22)
  uint32_t aType : 2;
  uint32_t aHiId : 6;
  uint32_t bType : 2;
  uint32_t bHiId : 6;
  uint32_t cType : 2;
  uint32_t cHiId : 6;
  uint32_t uniform : 1;
};
```

it's then used by the Assembler to do basic checks and to encode the instruction properly.

BTW these are all internals, you definitely don't need to know about these to use AsmJit.

**Comment by nmanhong** [comment]
@kobalicek
We are a loongarch system, not based on x86 or arm instructions. I need to understand these in order to use asmjit on our system

**Comment by kobalicek** [comment]
Are you working on a port?

If you are working on a port you will most likely need different data. For example x86 and aarch64 backends are pretty different in terms of instruction database - I would go with "simpler is better", but this really depends on the target architecture.

**Comment by nmanhong** [comment]
@kobalicek
yes，I use our company’s cpu, but I am not familiar with the internals of asmjit, I am going to refer to the arm, but now it seems that I am not familiar with the arm

**Comment by nmanhong** [comment]
@kobalicek
`struct BaseRRR {
  M_OPCODE(opcode, 22)
  uint32_t aType : 2;
  uint32_t aHiId : 6;
  uint32_t bType : 2;
  uint32_t bHiId : 6;
  uint32_t cType : 2;
  uint32_t cHiId : 6;
  uint32_t uniform : 1;
};`
In this structure, what do these two parameters mean? Can you tell me something? aHiId and uniform. aHiId occupies six digits, but the parameters you call in arm are kZR and kSP. These two are the 0 register and the stack register? I don’t know what it does? Uniform occupies one place. It displays true and false in the arm. What is its function?

**Comment by nmanhong** [comment]
@kobalicek
`struct BaseRRR {
  M_OPCODE(opcode, 22)
  uint32_t aType : 2;
  uint32_t aHiId : 6;
  uint32_t bType : 2;
  uint32_t bHiId : 6;
  uint32_t cType : 2;
  uint32_t cHiId : 6;
  uint32_t uniform : 1;
};`
In this structure, what do these two parameters mean? Can you tell me something? aHiId and uniform. aHiId occupies six digits, but the parameters you call in arm are kZR and kSP. These two are the 0 register and the stack register? I don’t know what it does? Uniform occupies one place. It displays true and false in the arm. What is its function?

**Comment by kobalicek** [comment]
The best way of understanding what the fields do is grepping `BaseRRR`.

In general, you would find the instruction database and Assembler's emit, which uses the data:

```c++
    case InstDB::kEncodingBaseRRR: {
      const InstDB::EncodingData::BaseRRR& opData = InstDB::EncodingData::baseRRR[encodingIndex];

      if (isign4 == ENC_OPS3(Reg, Reg, Reg)) {
        uint32_t x;
        if (!checkGpType(o0, opData.aType, &x))
          goto InvalidInstruction;

        if (!checkGpType(o1, opData.bType))
          goto InvalidInstruction;

        if (!checkGpType(o2, opData.cType))
          goto InvalidInstruction;

        if (opData.uniform && !checkSignature(o0, o1, o2))
          goto InvalidInstruction;

        if (!checkGpId(o0, opData.aHiId))
          goto InvalidPhysId;

        if (!checkGpId(o1, opData.bHiId))
          goto InvalidPhysId;

        if (!checkGpId(o2, opData.cHiId))
          goto InvalidPhysId;

        opcode.reset(opData.opcode());
        opcode.addImm(x, 31);
        opcode.addReg(o2, 16);
        opcode.addReg(o1, 5);
        opcode.addReg(o0, 0);
        goto EmitOp;
      }

      break;
    }
```

As you can see, the data drives how the Assembler validates operands and how it generates the instruction's opcode. Note that this data describes aarch64, but it's specific to asmjit - other assemblers would use most likely different data with different members and validation / encoding flow.

**Comment by xen0n** [comment]
@nmanhong You may find the [loongarch-opcodes](https://github.com/loongson-community/loongarch-opcodes) work valuable for generating LoongArch instruction definitions and maybe encoders; because LoongArch instruction formats are highly irregular (do you want to hand-write encoders for 39 different encodings?), such a table-based approach could be essential for maintainability. You're going to write a script in Go to emit code for asmjit use; I'd be happy to review your PR.

**Comment by kobalicek** [comment]
I would just to note that I would like to have the instruction database in asmjit. My goal is to not have any dependencies on third party databases or scripting (including asmdb, which will get merged with asmjit eventually). This means that I think also the instruction format should get standardized across platforms, and generators too. It's my long term goal.

I would consider Python for a generator language (or keep node.js), but not go.

**Comment by xen0n** [comment]
> I would just to note that I would like to have the instruction database in asmjit. My goal is to not have any dependencies on third party databases or scripting (including asmdb, which will get merged with asmjit eventually). This means that I think also the instruction format should get standardized across platforms, and generators too. It's my long term goal.
> 
> I would consider Python for a generator language (or keep node.js), but not go.

Sure; I'm just talking about one possible approach of auto-generating instruction definitions, not anything concrete, and definitely not the only possible thing to do.

However, I personally think that referring to (semi-)official instruction encoding data should be the best practice when maintaining packages dealing with machine code; the RISC-V people have the [riscv-opcodes](https://github.com/riscv/riscv-opcodes) project, while Loongson hasn't done the same officially so loongarch-opcodes was started as a community effort. Introducing such data by means of git submodules should add minimal complexity.

**Comment by xen0n** [comment]
And I'd like to note that QEMU's decodetree format might be a good choice for defining instruction encodings. It's originally designed to be used in the *decoding* direction, so we need to write an entirely different code generator for emitting *encoders*, but then people are presumably already familiar with DSLs like these, and it's ISA-agnostic and relatively easy to implement even from scratch.

**Comment by kobalicek** [comment]
I think the biggest problem here is, that asmjit requires a bit more information than what you need for encoding - for example read/write information, changed flags information, CPU features requred to execute an instruction, validation information. This is why the x86 generator is pretty complex, because it's a lot of information to pack into a small library such as asmjit. That's why it's pretty difficult to write a reasonable generator.

There are atm 2 approaches. The aarch64 approach is a bit different, but that's a direction I would go in the future - having multiple tables, one for each encoding, and one shared table that would define the extra information like read/write, features, etc...

**Comment by nmanhong** [comment]
@kobalicek
hi，I have successfully added the loongarch instruction by referring to the arm's assembler, and have all passed the asmjit_test_assembler test. I wrote the basic instructions by myself. I used the python script for the vector instructions. If I want to use fbgemm, do I just need to assemble it? Does the compiler need to be ported? Also about the use of separate assembler tests to use your arm code? Rather than simply looking at whether the generated machine code is right.

**Comment by xen0n** [comment]
Hi @nmanhong, would you mind sharing your work via a draft PR so people could have a look at it? This way everyone has less work to do, just in case (e.g. the overall structure needs rework and other unpleasant situations)

**Comment by nmanhong** [comment]
@xen0n 
Sorry, our vector instructions are not currently open, and I can’t share them, but soon our vector instructions will be open, and then I can share them.

**Comment by xen0n** [comment]
> @xen0n Sorry, our vector instructions are not currently open, and I can’t share them, but soon our vector instructions will be open, and then I can share them.

You may submit the base instruction part first, no problem.

**Comment by kobalicek** [comment]
@nmanhong That's cool, I assume you wrote your own tests and put them in a separate file?

**Comment by nmanhong** [comment]
@kobalicek
This Google Translate is a bit wrong, I asked you for a separate test of the assembler, not writing it myself，But the test of generating machine code was successful

**Comment by kobalicek** [comment]
The existing tests only verify X86 and AArch64 - if you added a new architecture you would have to add the tests as well - like `test_assembler_mips.cpp`

**Comment by nmanhong** [comment]
@kobalicek
Yes, I’ve added this test, but it’s just a test that generates machine code for instructions. Is there any test that’s actually run?

**Comment by kobalicek** [comment]
Usually only Compiler tests are executed as Compiler allows to generate functions for wide range of operating systems. Assembler tests just make sure the encoding of instructions works, which should be enough in most cases.

The purpose of assembler tests is to test ALL instructions provided.

**Comment by kobalicek** [comment]
Closing, please reopen if you have any further questions.
