### ISSUE TITLE
Unnecessary mov to rax created on a member function call with no arguments (kIdThisCall)

### ISSUE THREAD

**Issue by PaulWeustink** [asmjit/asmjit#347]
When a class function is called that has no arguments, there is an unnecessary mov created:
```
	InvokeNode* invokeNode;
	compiler.invoke (&invokeNode, imm (MyFunction), FuncSignatureT<int, void *> (CallConv::kIdThisCall));
	invokeNode->setArg (0, imm (this));
```

This generates code like:
```
	mov rax, 2807707964912
	mov rcx, rax
	call 140696659091376   
```

This code should be:
```
	mov rcx, 2807707964912
	call 140696659091376   
```

Unfortunately I do not know where to find and fix this. Any help?

**Comment by kobalicek** [comment]
I'm wondering, but that would not be the easiest, does that happen also in `refactor` branch? But since `refactor` branch has a lot of refactoring and API changes, I'm not sure it would be trivial to test that. I did some tuning there, but I'm unsure whether it would affect this particular issue

**Comment by kobalicek** [comment]
It would be nice if this is retested against the latest master. Would you be able to test it?

**Comment by PaulWeustink** [comment]
Sure I will try to test the new master tomorrow!

**Comment by kobalicek** [comment]
Closing as it should be fixed!
