### ISSUE TITLE
(aarch64 branch) B instruction with Imm arg compiles into garbage

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#349]
Hello, I'm trying to emit a simple trampoline using Aarch64 assembler. It basically contains only a single B instruction to an external function. It fails with illegal instruction, seemingly because it uses wrong relocation type.

**Comment by kobalicek** [comment]
Thanks!

Let me know whether this commit https://github.com/asmjit/asmjit/commit/4223a28a79c8797d0caf2aad4a865c8f25c31720 fixes the issue.

**Comment by Nekotekina** [comment]
Seems fixed, thank you!

**Comment by kobalicek** [comment]
It broke something else, but I will fix that. Thanks for confirmation :)

**Comment by kobalicek** [comment]
Closing, this should be fixed in aarch64 branch.
