### ISSUE TITLE
asmjit on the wasm platform

### ISSUE THREAD

**Issue by fire** [asmjit/asmjit#350]
Hi, is it possible to use asmjit on the wasm platform?

**Comment by kobalicek** [comment]
I'm closing as this was answered in gitter, thanks!

**Comment by ernestum** [comment]
But what was the answer though?

**Comment by kobalicek** [comment]
You can use asmjit on wasm platform, but asmjit has no wasm backend. So you can use it to generate x86 or aarch64 code.
