### ISSUE TITLE
Possible bug in ZoneTree

### ISSUE THREAD

**Issue by jhogberg** [asmjit/asmjit#352]
Hi!

I've noticed that `ZoneTree` may crash or exhibit odd behavior depending on compiler flags. I've narrowed it down to the following sequence:

```c++
#include <asmjit/x86.h>
 
using namespace asmjit;

int main() {
  Environment env = Environment::host();

  CodeHolder code;
  code.init(env);

  x86::Assembler a(&code);

  a.call(imm(0x55677b725fd7ul));
  a.call(imm(0x55677b746370ul));
  a.call(imm(0x55677b658be6ul));
  a.call(imm(0x55677b5be2c0ul));
  a.call(imm(0x55677b5be760ul));

  return 0;
}
```

This might work depending on your compiler: in our environment everything seemed to work fine until given `-fprofile-arcs -O2`, which made the last `call` above enter an infinite loop.

Applying the following patch makes it crash every time, as the assumption that `saveChild != nullptr` doesn't hold. Removing the statement altogether makes everything work when compiled with the affected flags, but I haven't dug deep enough to say it's the right thing to do. Is it meant to always be non-null?

```diff
diff --git a/src/asmjit/core/zonetree.h b/src/asmjit/core/zonetree.h
index 64ccdc8..55dfae3 100644
--- a/src/asmjit/core/zonetree.h
+++ b/src/asmjit/core/zonetree.h
@@ -353,7 +353,7 @@ public:
     ASMJIT_ASSUME(save != nullptr);
 
     ZoneTreeNode* saveChild = save->_getChild(dir);
-    ASMJIT_ASSUME(saveChild != nullptr);
+    ASMJIT_ASSERT(saveChild != nullptr);
 
     root->_setChild(!dir, saveChild);
     save->_setChild( dir, root);
```

**Comment by kobalicek** [comment]
It hits the assert if you try it in debug mode. I think the assert is wrong, but I will check this first.

**Comment by jhogberg** [comment]
Righto. :)

One thing that struck me is that `ASMJIT_ASSUME` isn't verified in debug mode at the moment. Do you think it's a good idea to redefine it as `ASMJIT_ASSERT` in debug mode to catch problems like this?

**Comment by kobalicek** [comment]
I have removed the assumption for now.

I think that indeed these assumptions should be asserts in debug mode. They are in the end only hints for compiler and static analysis tools.
