### ISSUE TITLE
How to generate multiple functions to reuse 

### ISSUE THREAD

**Issue by StandingPadAnimations** [asmjit/asmjit#354]
I have 2 questions related to functions:
* How to generate multiple functions and store them in separate classes?
* How to dynamically make function signatures? 
The last one isn't really related to asmjit, but I'm curious on how to do it

**Comment by kobalicek** [comment]
Could you describe what you mean with `separate classes`? I think I don't understand the question. You can generate multiple functions with AsmJit (with all emitters).

Dynamic function signatures are possible with FuncSignatureBuilder, see https://asmjit.com/doc/classasmjit_1_1FuncSignatureBuilder.html

**Comment by StandingPadAnimations** [comment]
Basically, how to store the resulting function in a variable and create a new one. Would I have to make a new instance of the compiler class?

**Comment by kobalicek** [comment]
You can store multiple functions to a single Runtime, for example checkout the example here:

  - https://asmjit.com/doc/classasmjit_1_1x86_1_1Compiler.html
  - JitRuntime: https://asmjit.com/doc/classasmjit_1_1JitRuntime.html

CodeHolder holds code, and emitters attach to it. To reuse a `CodeHolder`, just reset it and reattach the emitter you use to it. You will most likely save some memory allocations by doing this.

**Comment by kobalicek** [comment]
If you add the generated function to JitRuntime, it would stay there unless you remove it from it or destroy JitRuntime. You can of course call generated functions from generated functions.

**Comment by oscarfv** [comment]
I think I have a very similar requirement.

I'm using `x86::Assembler` to generate multiple functions, some of them act as entry points, the rest are called by one or more entry points. `JitRuntime::add` returns the beginning of the generated assembler, but I would need something like "get the address of this label, and this one, and this one".

`CodeHolder` has `labelOffset` and `labelOffsetFromBase`, but those are not callable addresses, nor they are easily convertible to callable addresses, aren't they?

Could I just add the value returned by `CodeHolder::labelOffset` to the address returned by `JitRuntime::add` and get the actual address of the machine code associated to a label?

**Comment by kobalicek** [comment]
LabelOffsetFromBase would give an offset, if you add the offset to the pointer returned by JitRuntime::add() you would get a callable address, does that answer your question?

**Comment by oscarfv** [comment]
> LabelOffsetFromBase would give an offset, if you add the offset to the pointer returned by JitRuntime::add() you would get a callable address, does that answer your question?

Yes, thank you. I'll test that approach right now.

(please note that I'm not the original reporter, I don't know if this solution is adequate for him.)

**Comment by StandingPadAnimations** [comment]
I think that helps. Thanks

Also on an unrelated note, how do we use `const char*` in a ConstPool? I have something like:
```cpp
const char* VariableName = std::string(Args).c_str();
asmjit::x86::Mem ConstPool = m_RendorJITCompiler <- How do I store a const char here?
asmjit::x86::Gp Arg = m_RendorJITCompiler.newGpd();
m_RendorJITCompiler.mov(Arg, ConstPool);
Variables[Args] = std::make_pair(VariableType::Float, Arg);
```

**Comment by StandingPadAnimations** [comment]
Ahhh. So how would I store them normally?

**Comment by kobalicek** [comment]
Well, I meant to just create your own pool, or just append strings into some vector or std::string and then embed it when you are done - that would be the easiest I think

**Comment by kobalicek** [comment]
You would embed that vector as data and reference the data, not the vector. The vector would be just temporary. To embed anything later, you just need a Label that will be the beginning of the data. If you append anything to a vector, you know the index you are appending to, so `x86::ptr(Label, index)` would be the address of the data.

**Comment by oscarfv** [comment]
For the record, his is what worked for me:

```
auto aFunction = a.newLabel();
...
a.ret();
a.bind(aFunction);
...
a.ret();
void *fn;
runtime.add(&fn, &code);
// now we in fn the address of the start of the generated code
// but we want the address bound to aFunction as well, so:

auto addressOfAFunction = (void*) reinterpret_cast<char*>(fn)+code.labelOffset(aFunction);
```

@kobalicek : if you want to use a label to calculate an address from within the generated code, you need to use the necessary instructions.

In your example `lea rax, [stringPool + 6] // reference some string` does not reference a string, it puts a value into `rax` that corresponds to the address of the sixth byte after the address `stringPool` is bound too. If you need to point to the first char of the nth string, you need to calculate the offset from `stringPool` yourself, or bind a label to each string:

```
mov rax, string2 ; reference string2
// note the mov, not lea, because a label here acts as an immediate value.

string1:
"hello\0"
string2:
"someOtherStringReferenced\0"
string3:
"etc...\0"
```

HTH.

**Comment by oscarfv** [comment]
@kobalicek : with your `ConstPool` how do you know the offset of the n-th string?

BTW, why do you need to define those strings the generated assembler? You could as well do something like this (untested):

```
const char* myStrings[] = { "zero", "one", "two", "three"};

a.mov(x86::rax, imm(myStrings[1])) // Point to the first char of "one"
```

**Comment by kobalicek** [comment]
`ConstPool` was not designed for strings, only for constants up to 64 bytes (AVX-512).

You only need to embed strings if they are not known at compile time (C++ compile time in this sense).

**Comment by oscarfv** [comment]
@kobalicek : somehow I thought that you were the individual who opened this issue and I was trying to help :-) Just now I realized that you are the author of asmjit, so I my "help" is totally superfluous. Sorry for the confusion. And thanks for asmjit, which is doing wonders here as an alternate backend for my compiler.

**Comment by kobalicek** [comment]
haha it's okay :)

**Comment by StandingPadAnimations** [comment]
> You only need to embed strings if they are not known at compile time

Wouldn't a vector also work? (I'm not an expert with assembly so I'm not sure if there would be issues)

**Comment by StandingPadAnimations** [comment]
> Well, not sure I understand - you would use label, and embed data after it. Then to reference anything in assembly, you would just form address having that label and optionally some offset if there is more strings.
> 
> ```
> // ... some assembly ...
> lea rax, [stringPool + 6] // reference some string
> // ... some assembly ...
> 
> // ... end of assembly ...
> 
> stringPool: // beginning of strings
> "hello\0"
> "someOtherStringReferenced\0"
> "etc...\0"
> ```

@kobalicek just curious, how would I embed the actual strings? The label is easy but I'm not sure how I embed strings
