### ISSUE TITLE
Using asmjit as subrepository gets detached very often

### ISSUE THREAD

**Issue by Lyve1981** [asmjit/asmjit#355]
We use asmjit in a project and this project has asmjit added as subrepository.

As we need arm support, we use the aarch64 branch.

However, every few weeks, the repository gets detached because the commit we are referencing to is gone. Whenever I check the repository history, the "Added initial AArch64 support" is always at the top of the history and the commit ID has changed.

People that want to clone our repository are unable to clone including asmjit and are getting build errors therefore.

Is this due to some special way this repository is maintained? What is the proper way to include asmjit including aarch64 into a project?

Thanks in advance!

**Comment by kobalicek** [comment]
Hi, aarch64 has been merged to master, so you can point to master now, which will never detach.

And yeah, sorry for that, I prefer rebasing my own branches, I can imagine it was kinda inconvenient.

**Comment by Lyve1981** [comment]
Oh I didn't know its already in master now, thats great news, thanks a lot!
