### ISSUE TITLE
Vector code for ARM

### ISSUE THREAD

**Issue by peastman** [asmjit/asmjit#360]
I apologize if this is a very basic question.  I think I'm missing some concepts about how to work with asmjit.

I'm trying to create vectorized code for ARM64.  I don't understand how to convert between the documentation for ARM assembly and the functions provided by asmjit.  Here is a simplified example to demonstrate a problem I'm stuck on.  It creates a function that loads a constant into the first element of a vector register, then stores the entire vector to memory.

```c++
JitRuntime runtime;
CodeHolder code;
code.init(runtime.environment());
a64::Compiler c(&code);
c.addFunc(FuncSignatureT<void>());
float constant = 5.0;
arm::Vec constantVar = c.newVecS();
arm::Gp constantPointer = c.newIntPtr();
c.mov(constantPointer, imm(&constant));
c.ldr(constantVar, arm::ptr(constantPointer));
float result[4];
arm::Gp resultPointer = c.newIntPtr();
c.mov(resultPointer, imm(result));
c.str(constantVar, arm::ptr(resultPointer));
c.endFunc();
c.finalize();
void (*fn)();
runtime.add(&fn, &code);
fn();
printf("%g %g %g %g\n", result[0], result[1], result[2], result[3]);
```

When I run it, it works as expected.  The output is

```
5 3.60134e-43 0 0
```

But I actually want to do something different: load the constant into all four elements of the vector, so the output is `5 5 5 5`.  [The documentation](https://developer.arm.com/documentation/ddi0602/2021-12/SIMD-FP-Instructions/LD1R--Load-one-single-element-structure-and-Replicate-to-all-lanes--of-one-register--) indicates I should use LD1R instead of LDR.  If I simply change `c.ldr(...)` to `c.ld1r(...)`, the program crashes with "Illegal instruction: 4".

Clearly I'm doing something wrong, but I'm not sure what.  One point I'm particularly confused about is that the LD1R instruction has a "size" argument to tell it I'm operating on four byte values.  `ld1r()` doesn't have any corresponding argument.  How do I tell it what size values to operate on?  Does it figure that out automatically from the fact that I created the register with `newVecS()`?

Thanks for your help.

**Comment by kobalicek** [comment]
When you see something like `<Vt>.<T>` in the manual it means that the instruction's operand (register) requires an element size information.

for example you can write `c.ld1r(constantVar.s4(), a64::ptr(constaintPointer))` - that would be `LD1R vReg.4s, [ptr]` in AArch64.

Let me know whether that helps.

**Comment by peastman** [comment]
Thanks!  Changing that line to `c.ld1r(constantVar.s4(), arm::ptr(constantPointer))`, it no longer crashes.  I also had to add `.s4()` when storing the value to memory.  Otherwise it would only write the first element.  With those two changes, it now works as expected.

Thanks for the quick reply!

**Comment by kobalicek** [comment]
Welcome :)

BTW use `newVecQ()` to create a virtual register if you plan to use all 128-bits - `newVecS()` creates 32-bit register - asmjit would only manage its 32 bits if it needs to be spilled.

**Comment by peastman** [comment]
Good point, thanks.

If I want to use the INS instruction to copy element 3 of one vector to element 0 of another vector, is the following the correct syntax?

```c++
c.ins(dest.s(0), source.s(3));
```

**Comment by kobalicek** [comment]
Yes this looks like a correct syntax. With AArch64 sometimes there are restrictions (register indexes, etc), so it's always good to have the AArch64 architecture instruction manual open.
