### ISSUE TITLE
JMP and CALL instructions address bug?

### ISSUE THREAD

**Issue by 7x-hex-x7** [asmjit/asmjit#365]
Hello, I have a bug with **JMP** and **CALL** instructions. Why do they return a null address?

Here is my C++ code:

	__int64 iCodeCaveStructureInvisibility = 0x1677000;

	__int64 iByteInvisibility = 0x16770100;

	int jmp_01 = 0x00D51775;

	Environment environment;
	environment.setArch(Arch::kX86);

	CodeHolder codeHolder;
	codeHolder.init(environment);
	Assembler asm_01(&codeHolder);

	Label labelPopCode = asm_01.newLabel();

	asm_01.push(ebx);
	asm_01.test(ecx, ecx);
	asm_01.short_().je(labelPopCode);
	asm_01.mov(ebx, ptr(iByteInvisibility));
	asm_01.mov(ptr(ecx, 0x04), ebx);
	//Pop code
	asm_01.bind(labelPopCode);
	asm_01.pop(ebx);
	//Original code
	asm_01.mov(eax, ptr(ecx, 0x04));
	asm_01.test(eax, eax);
	//Return to original function
	asm_01.jmp(jmp_01);

	CodeBuffer& buffer = codeHolder.textSection()->buffer();

	WriteProcessMemory(memoryTool->hProcess, (LPVOID)iCodeCaveStructureInvisibility, buffer.data(), buffer.size(), NULL);

Disassembler output:

```
16770000 - 53                    - push ebx
16770001 - 85 C9                 - test ecx,ecx
16770003 - 74 09                 - je 1677000E
16770005 - 8B 1D 00017716        - mov ebx,[16770100]
1677000B - 89 59 04              - mov [ecx+04],ebx
1677000E - 5B                    - pop ebx
1677000F - 8B 41 04              - mov eax,[ecx+04]
16770012 - 85 C0                 - test eax,eax
16770014 - E9 00000000           - jmp 16770019
```

I tried using **asm_01.long_().jmp(jmp_01);** but the same result. There is a analogous issue with the **CALL** instruction.

Is it issue because of the long distance between addresses? Although it should look something like this: **E9 5C1734FC**

**Comment by kobalicek** [comment]
You must relocate the code, before you copy anything:

```
uint64_t base = /* your base */;
codeHolder.flatten();
codeHolder.relocateToBase(base);
```

Let me know whether that helps.

**Comment by 7x-hex-x7** [comment]
> You must relocate the code, before you copy anything:
> 
> ```
> uint64_t base = /* your base */;
> codeHolder.flatten();
> codeHolder.relocateToBase(base);
> ```
> 
> Let me know whether that helps.
> 
> If you know the base, then it's better to setup code holder with that base, so it would not create reloc entries for jumps/calls.

Everything is working properly now, thank u very much!
