### ISSUE TITLE
[arm64] `ldrsh` with 64-bit output register

### ISSUE THREAD

**Issue by lei-april** [asmjit/asmjit#372]
This is a follow-up to https://github.com/asmjit/asmjit/issues/370.

With https://github.com/asmjit/asmjit/commit/d925605671770b667eefc960de2b50eb07990ecd, `[reg, reg]` addressing mode works as expected now, but `[reg, imm]` still produces incorrect output register as before.

![image](https://user-images.githubusercontent.com/5738276/174513013-67154712-d7ad-4746-ab4c-c41b3be16ed7.png)

**Comment by kobalicek** [comment]
Thanks!
