### ISSUE TITLE
sys_icache_invalidate  and pthread_jit_write_protect_np  can't use on iOS ,any method can replace these?

### ISSUE THREAD

**Issue by moxiaohao** [asmjit/asmjit#379]

**Comment by kobalicek** [comment]
Can you provide more details? Are these functions not available, or not linkable, etc...?

I don't use asmjit on iOS myself, so somebody more experienced with this target should help I think

**Comment by moxiaohao** [comment]
Sorry , the sys_icache_invalidate can be used, i make a mistake .

pthread_jit_write_protect_np is not available on iOS ,i wonder whether i  can find a method replace it or whether this method is neccessry ? can I just delete this method invocation ?


![image](https://user-images.githubusercontent.com/1642539/185572072-f66f8737-a722-4160-b5e0-939afd6a2219.png)


![image](https://user-images.githubusercontent.com/1642539/185569360-8511d343-e50b-4b8f-b5d4-65f90cb17668.png)

**Comment by kobalicek** [comment]
I think the whole MAP_JIT functionality would have to be disabled on iOS

**Comment by moxiaohao** [comment]
Yep, iOS disabled jit functionality, But when App is Published and have a few bugs ,republish is so hard .

**Comment by kobalicek** [comment]
Can you test `disable_map_jit_on_ios` branch?

However, if MAP_JIT is not available, JitRuntime would not be usable, so I'm not sure what is the benefit of asmjit on such a restricted platform.

**Comment by kobalicek** [comment]
I think this can be closed as I have already merged some fixes, can you verify / close?
