### ISSUE TITLE
Indirect jumping to a single label broken by 509866e

### ISSUE THREAD

**Issue by Chlumsky** [asmjit/asmjit#380]
Hi, not sure if you remember me from #286 but I just wanted to let you know that the library no longer works for me since commit 509866e. I've been successfully using commit e78bba8 without any problems whatsoever for over two years, but when I was recently updating my dependencies, I found that newer versions of AsmJit crash my program. In debug mode, I am getting this assertion: https://github.com/asmjit/asmjit/blob/5c469e3f7c307da939d38d72e09f08db7ca076ef/src/asmjit/core/rapass.cpp#L331

And in release mode, it simply crashes with a write access violation. Everything still seems to work in the previous commit, c130455.

**Comment by kobalicek** [comment]
When you turn on diagnostics, via the following:

```
cc.addDiagnosticOptions(DiagnosticOptions::kRAAnnotate | DiagnosticOptions::kRADebugAll);
```

does it print anything?

BTW: can you reproduce the crash on master branch?

**Comment by Chlumsky** [comment]
Yes, this is on master branch and no, it doesn't seem to print anything.

**Comment by Chlumsky** [comment]
Also, on an unrelated note, I am using Visual Studio 2022, but I also tried building it with Visual Studio 2015, and even though it didn't immediately compile, I only had to change two lines, so if you happen to fix this issue, I would appreciate if you also added these so that I can retain compatibility:

https://github.com/asmjit/asmjit/blob/5c469e3f7c307da939d38d72e09f08db7ca076ef/src/asmjit/core/emitterutils_p.h#L26

to

```c++
static constexpr Operand noExt[3] = { };
```

and

https://github.com/asmjit/asmjit/blob/5c469e3f7c307da939d38d72e09f08db7ca076ef/src/asmjit/core/api-config.h#L589-L591

to

```c++
#if defined(_DOXYGEN) || (defined(_MSC_VER) && _MSC_VER <= 1900)
```

because it already has the comparison operators for some reason and redefining them causes ambiguity (I don't have VS2017 so not sure if the version number should be higher).

**Comment by kobalicek** [comment]
I tried to write a test that could theoretically hit the assert, but no luck actually hitting it. It's hard to tell, what feels suspicious is the condition, would you try replacing the code with:

```
  for (RABlock* block : _blocks) {
    if (block->hasJumpTable()) {
      const RABlocks& successors = block->successors();
      if (successors.size() > 1) {
        RABlock* firstSuccessor = successors[0];
        // NOTE: Shared assignments connect all possible successors so we only need the first to propagate exit scratch
        // GP registers.
        ASMJIT_ASSERT(firstSuccessor->hasSharedAssignmentId());
        RASharedAssignment& sa = _sharedAssignments[firstSuccessor->sharedAssignmentId()];
        sa.addEntryScratchGpRegs(block->exitScratchGpRegs());
      }
    }
    if (block->hasSharedAssignmentId()) {
      RASharedAssignment& sa = _sharedAssignments[block->sharedAssignmentId()];
      sa.addEntryScratchGpRegs(block->_entryScratchGpRegs);
    }
  }
```

But still not sure about this one.

It would be nice to have at least the content of the Compiler dumped, that could give me a hint where to look

**Comment by Chlumsky** [comment]
Looks like this fixes it. 👍

**Comment by kobalicek** [comment]
Thanks for confirmation. I have a test-case for this one already, will fix it.

**Comment by Chlumsky** [comment]
Thank you very much for the fix, but do you think you could also add these changes https://github.com/asmjit/asmjit/issues/380#issuecomment-1250209970? I know you don't want to support old compilers, but I'm sure it would be harmless. Or should I submit a pull request?

**Comment by kobalicek** [comment]
I will look into that, but over the next weekend, I just want to have the bug fixed for now as I don't like bugs :)

**Comment by kobalicek** [comment]
@Chlumsky Are you still interested in that support for VS 2015? If so, please create an issue and I will take a look over the weekend.
