### ISSUE TITLE
assembler.movsx(rax, eax) should cause an error

### ISSUE THREAD

**Issue by corey-** [asmjit/asmjit#381]
assembler.movsx(rax, eax) silently changes it to movsx rax, ax and doesn't return an error. movsx rax, eax is not a valid opcode and should return an error. Very frustrating when I forget to use the latter form and it takes lots of debugging to find the mistake since my JIT error handler was never called.

**Comment by kobalicek** [comment]
I would suggest turning on instruction validation in your debug builds, as mentioned in the documentation here:

https://asmjit.com/doc/index.html

Instruction validation in your debug builds can reveal problems too. AsmJit provides validation at instruction level that can be enabled via [BaseEmitter::addDiagnosticOptions()](https://asmjit.com/doc/classasmjit_1_1BaseEmitter.html#a119495fe694b04b5fb2e0d951a983899). See [DiagnosticOptions](https://asmjit.com/doc/group__asmjit__core.html#ga3f15a58e31dae90dec0f0887b8aee7d4) for more details.

Assembler in general only does the necessary checks to assemble an instruction, it won't do a full validation (although I would like to change this once I have a fully generated assembler).

**Comment by corey-** [comment]
Ah, sorry did not see those options. That works perfectly so far, thanks!
