### ISSUE TITLE
Inconsistent InvalidState error when returning Xmm register 

### ISSUE THREAD

**Issue by WireWhiz** [asmjit/asmjit#384]
Hi, I'm currently using asmjit to build a jit-compiled scripting language, and I'm wondering if you have to manually call something like:
```
Reg& ret = registers[valIndex.index];
cc.movss(xmm0, ret.as<Xmm>());
cc.ret(xmm0);
```
if you created the original register you want to return like this:
```
 registers.push_back(cc.newReg(TypeId::kFloat32));
```
I'm using the x86::Compiler, and I find that if I don't do this and just pass the original register I inconsistently get InvalidState errors for different combinations of function argument types. Like float(int, float) might work just fine but float(float, int) might give the error. And it's also affected by creating new registers.

**Comment by WireWhiz** [comment]
Even with the fix, still get the bug with this test script:
```float main(float a, float b, float c, float d, float e) { return a + b - c * d / e; }```
It would be calling the equivalent of this to generate the assembly:
```
using namespace asmjit::x86;

...

asmjit::CodeHolder ch;
Compiler cc(&ch);

std::vector<asmjit::x86::Reg> registers;
std::unordered_map<uint16_t, asmjit::x86::Mem> constants;

asmjit::FuncSignatureBuilder sigBuilder;
sigBuilder.addArg(asmjit::TypeId::kFloat32);
sigBuilder.addArg(asmjit::TypeId::kFloat32);
sigBuilder.addArg(asmjit::TypeId::kFloat32);
sigBuilder.addArg(asmjit::TypeId::kFloat32);
sigBuilder.addArg(asmjit::TypeId::kFloat32);
sigBuilder.setRet(asmjit::TypeId::kFloat32);

auto* f = cc.addFunc(sigBuilder);

for (size_t i = 0; i < 5; ++i)
{
    registers.push_back(cc.newReg(asmjit::TypeId::kFloat32));
    f->setArg(i, registers[i]);
}

registers.push_back(cc.newReg(TypeId::kFloat32));
auto a= registers[5].as<Xmm>();
auto b= registers[0].as<Xmm>();
cc.movss(a, b);

auto a = registers[5].as<Xmm>();
auto b = registers[1].as<Xmm>();
cc.addss(a, b);

registers.push_back(cc.newReg(TypeId::kFloat32));
a = registers[5].as<Xmm>();
b = registers[2].as<Xmm>();
cc.movss(a, b);

a = registers[6].as<Xmm>();
b = registers[3].as<Xmm>();
cc.mulss(a, b);

a = registers[6].as<Xmm>();
b = registers[4].as<Xmm>();
cc.movss(a, b);

a = registers[5].as<Xmm>();
b = registers[6].as<Xmm>();
cc.subss(a, b);

auto& ret = registers[5];
cc.movss(xmm0, ret.as<Xmm>());
cc.ret(xmm0);

cc.endFunc()
cc.finalize() //InvalidState returned here
```

**Comment by WireWhiz** [comment]
I've tracked it down to the emitArgMove function on line 309 in emithelper.cpp if that helps. I'm going to see if I can narrow it down even more.

**Comment by kobalicek** [comment]
Unfortunately I won't be able to look into this now. I'm moving at the moment, my workstation already packed.

Just by looking at the code, I think you should always use `newXmmSs()` to create XMM registers (not sure whether I have ever used `kFloat32` this way).

**Comment by WireWhiz** [comment]
I have a simple ErrorHandler set up to print errors at the moment, but I haven't set up a logger yet. I've also set the compiler to use kValidateAssembler and kRADebugAll

**Comment by WireWhiz** [comment]
That seems to have fixed it! Just swapping out where I would usually call cc.newReg to this function seems to have fixed it:
```
Reg newReg(asmjit::TypeId type, Compiler& cc)
{
    switch(type)
    {
        case asmjit::TypeId::kInt32:
            return cc.newInt32();
        case asmjit::TypeId::kFloat32:
            return cc.newXmmSs();
        default:
            throw std::runtime_error("Unimplemented type");
    }
}
```

**Comment by kobalicek** [comment]
Can we close this? Or anything to answer yet?

**Comment by WireWhiz** [comment]
My issue has been fixed
