### ISSUE TITLE
Strange code fragment

### ISSUE THREAD

**Issue by mjunix** [asmjit/asmjit#392]
https://github.com/asmjit/asmjit/blob/0c03ed2f7497441ac0de232bda2e6b8cc041b2dc/src/asmjit/x86/x86assembler.cpp#L496

`InstOptions::kX86_ModMR` on both sides of operator.

Intentional or a bug?

**Comment by kobalicek** [comment]
Definitely not intentional - one of them should be `kX86_ModRM` and the other `kX86_ModMR`.

I don't think this is affecting anyone, but it's a bug

**Comment by kobalicek** [comment]
Thanks for spotting that!
