### ISSUE TITLE
RISC-V port

### ISSUE THREAD

**Issue by pazamelin** [asmjit/asmjit#393]
Hello!

Are there any plans on adding RISC-V backend?
[This](https://github.com/asmjit/asmjit#todo) TODO list in the README.md file mentiones it, but there seems to be no other info on that matter.

Are you planning to implement it in the future? Do you have any timelines for it? Would you accept external contributions? 
I think having a RISC-V support here could be benefitial both for this project and the emerging RISC-V ecosystem.

Thanks,

**Comment by kobalicek** [comment]
Yeah there is a work in progress to support RISC-V, but it's not done by me and I don't know the status.

**Comment by pazamelin** [comment]
Many thanks for the prompt reply.
If it's possible, could you please point out who is doing it?
