### ISSUE TITLE
Deployed docs do not match source code

### ISSUE THREAD

**Issue by connorjclark** [asmjit/asmjit#394]
https://github.com/asmjit/asmjit/blob/master/src/asmjit/core.h#L1496-L1512

https://asmjit.com/doc/group__asmjit__logging.html#:~:text=And%20finally%2C%20the%20example%20below

Although I am using the most recent commit, are the docs only tracking the most recent released version? The repo doesn't have any tags or releases so I didn't know which revision would be best, so I just picked the latest commit on master.

**Comment by kobalicek** [comment]
Yeah true, it's not automatic at the moment

**Comment by kobalicek** [comment]
It's still not automatic, but I have scripted this pretty well on my end so I would close this now.
