### ISSUE TITLE
vmxoff instruction

### ISSUE THREAD

**Issue by FaerHack** [asmjit/asmjit#398]
Are there any plans to add vmxoff instruction support to x64 assembler?

**Comment by kobalicek** [comment]
yeah not sure why it's missing

**Comment by FaerHack** [comment]
yeah

**Comment by kobalicek** [comment]
The instruction is now provided, since  https://github.com/asmjit/asmjit/commit/e4e61c4f15135eadccb6ba050805a01e35ef7642
