### ISSUE TITLE
Shaping new JIT allocator API

### ISSUE THREAD

**Issue by kobalicek** [asmjit/asmjit#401]
### Motivation

At the moment there are 3 layers that can be used to allocate executable memory:

  * `VirtMem` (low level API)
  * `JitAllocator` (middle level API)
  * `JitRuntime` (high level API integrating with `CodeHolder` by inheriting `Target`)

`VirtMem` is basically a foundation of the other two, and `JitAllocator` is used by `JitRuntime` under the hood. Sometimes, people don't want to use `JitRuntime` and would use directly either `VirtMem` or `JitAllocator` depending on the use case. However, it's more difficult to use these APIs correctly compared to `JitRuntime`, because `VirtMem` abstracts multiple operating systems and some of them use very specific approaches to allow JITs (for example Apple with their `MAP_JIT`).

### JitAllocator API

At the moment, using `JitAllocator` alone means to do the following to copy code into the "executable" memory:

```c++
void* copyCode(JitAllocator* allocator, void* code, size_t codeSize) {
  void* rx;
  void* rw;

  if (allocator->alloc(&rx, &rw, codeSize) != kErrorOk) {
    // Handle the error.
    return nullptr;
  }

  {
    VirtMem::ProtectJitReadWriteScope rwScope(rx, codeSize);
    memcpy(rw, code, codeSize);
  }

  // now `rx` can be executed
  return rx;
}
```

There are two purposes of `ProtectJitReadWriteScope`:

  * Call `VirtMem::protectJitMemory()` to temporarily change permissions of pages that store the code; to be able to copy the code into the executable memory. This function only does something on Apple Silicon at the moment by calling `pthread_jit_write_protect_np()`.
  * Flush instruction cache after the code has been written (done by `ProtectJitReadWriteScope` destructor).

This design is overall pretty ok as it allows to either have RWX pages (if allowed), dual mapping, or memory mapped with `MAP_JIT`. And the user of `JitAllocator` doesn't really have to know which one is actually used as it's properly abstracted.

However, this design of `JitAllocator` API provides too much freedom and I'm not sure whether it would be sufficient in the future in which new hardening policies could be introduced or new HW capabilities would make writing JIT compilers even more difficult when enabled. In addition, the current `JitAllocator` API cannot be used to implement other techniques, for example having a single mapping and flipping RW and RX permissions (basically not allowing JIT code to run during the write).

In other words, it would be nice to have a door open for new approaches (even for experimenting purposes) and prepare users for the day in which DualMapping would become prohibited.

### New Design

To fix the potential future issues with `JitAllocator` API and to provide a better playground for experimenting, the following changes would be necessary:

  * `JitAllocator` needs to know more about when the JIT code would be executed. I can imagine multiple options:
    - Compiled once, sealed, and then executed.
    - Never executed during compilation, user makes sure that no thread executes code in pages where a new code is being copied or where the code is patched / removed.
    - Current semantics - existing code may be running during JIT compilation, JIT allocator must basically use dual mapping or MAP_JIT to make sure that threads executing the code won't fault.
  * `JitAllocator` should return something like a "handle" referencing the allocated memory from its `alloc()` function, which can be then used to copy content into the provided address. However, instead of instructing users to copy the data there by themselves, maybe `JitAllocator` can actually provide API for doing that - this can even be a callback like API, in which `JitAllocator` would call a user function with rw pointer and let it copy the data there, for example if the code source is from multiple sections and not a single continuous memory buffer. This API would make sure to use `ProtectJitReadWriteScope` under the hood, or any other viable technique (like temporarily changing permissions).
  * Allow batch copies to optimize cases in which user wants to copy multiple functions and the allocators has to do something to allow that copy

In general, the API can be simplified to something like this:

```c++
// Returns executable memory, which can be then released by allocator->release(...).
void* allocExec(JitAllocator* allocator, void* code, size_t codeSize) {
  JitAllocator::Span span;

  if (allocator->alloc(span, codeSize) != kErrorOk) {
    // Handle the error.
    return nullptr;
  }

  allocator->write(span,
    0, // offset in the referenced piece of code
    code,  codeSize // source from to copy
  );

  return span.rx();
}
```

In case the copy logic is more complex:

```c++
void* allocExec(JitAllocator* allocator, void* code, size_t codeSize) {
  JitAllocator::Span span;

  if (allocator->alloc(span, codeSize) != kErrorOk) {
    // Handle the error.
    return nullptr;
  }

  // Lambda would be turned to a regular C callback, then called via it.
  allocator->write(span, 0, [&](void* rw) -> Error {
    memcpy(rw, code, codeSize);
    return kErrorOk; // propagated error code.
  });

  return span.rx();
}
```

And for optimized multiple copies, the API could offer to create a scope:

```c++
void* allocExec(JitAllocator* allocator, void* code, size_t codeSize) {
  JitAllocator::Span span;

  if (allocator->alloc(span, codeSize) != kErrorOk) {
    // Handle the error.
    return nullptr;
  }

  {
    JitAllocator::WriteScope writeScope(allocator);
    // Lambda would be turned to a regular C callback, then called via it.
    writeScope.copy(span, 0, [&](void* rw) -> Error {
      memcpy(rw, code, codeSize);
      return kErrorOk; // propagated error code.
    });
    // possibly more copies...
  }

  return span.rx();
}
```

Note that the allocation in this case can be seen as just reserving the memory and returning some kind of reference to it (`Span`). Memory can be reserved safely without touching executable pages (JitAllocator doesn't store anything in executable pages, only user code is there), so this part of `JitAllocator` can stay almost as is.

However, `JitAllocator` would need to scope any modification to the allocated memory, hence using either JitAllocator directly or creating a write scope, which would optimize cases in which the mapping permissions are changed on every modification and then turned back, for example.

### Discussion

This issue was created to discuss the following:

  - Is the current API sufficient? How to support environments where it's not sufficient?
  - Is the new API design usable from user's perspective? Is it good considering future restrictions?
  - Which new techniques could be added to the new API to make it fit more use cases?

Even if a new API is added the current API would stay for some time, so it's not like it will be removed, it's about providing a new better API that would enable using JITs even in more restricted environments without users having to implement all the bits by themselves. Additionally, I would like to remove the need for using dual mapping in some cases, and the new API should be able to offer that.

**Comment by jhogberg** [comment]
> Flush instruction cache after the code has been written (done by `ProtectJitReadWriteScope` destructor).

To add another wrinkle to this, it's not enough to do this on the thread that modified the code in a multi-threaded environment. For it to work properly one needs to issue an instruction synchronization barrier on all threads that will execute the code (either by using a serializing instruction like `cpuid` on `x86` or `isb` on `aarch64`).

We ran into this recently on `aarch64`, doing it wrong worked for an embarrassingly long time because the way we synchronized other things made us hit implicit barriers all the time (mainly syscalls and being scheduled out).

> Is the current API sufficient? How to support environments where it's not sufficient?

We find it sufficient, but if `JitAllocator` gave us less freedom to cross-modify running code we'd either start using `VirtMem` directly or roll that on our own too. We're using it out of convenience and wouldn't lose much if you started making drastic changes in this area, it would be a bit of extra work but we've been thinking about doing that anyway to get more control over the memory layout.

> Is the new API design usable from user's perspective?

I think so, nearly all uses of `JitAllocator` are followed by a copy and instruction cache flush anyway so wrapping that in a `write()` function is just more convenient.

> Which new techniques could be added to the new API to make it fit more use cases?

To go back to the instruction cache stuff, I think people would appreciate something to make multi-threaded instruction synchronization easier to handle. You don't have to do anything as funky as cross-modifying running code to run into issues, it's enough to free code and then generate code at the same address.

**Comment by kobalicek** [comment]
@jhogberg That's the point of this discussion to actually design the new API in a way so you would not need to create your own abstraction on top of `VirtMem` - although it's already great that you would do it on top of `VirtMem` and not creating one from scratch :)

I don't plan to remove features from `JitAllocator` actually, I just think that a bit different design could solve a lot of issues while offering a very similar set of features. If we settle on spans and offer a `write()` API and write scopes, then JitAllocator can be refactored at any time to offer something new without having to touch any code that uses it.

For example I have lately found a function `pthread_jit_write_with_callback_np()` - if a new API is added to `JitAllocator` that would allow the callback (as already drafted in the issue) then we would be able to support `pthread_jit_write_with_callback_np()` out of box and the application would be able to even use `PTHREAD_JIT_WRITE_ALLOW_CALLBACKS_NP()` to even tighten the security, etc...

BTW I have already implemented some bits yesterday, you can check out this branch - impact on user code is minimal:

  - https://github.com/asmjit/asmjit/tree/jit_alloc

BTW that "instruction synchronization barrier" is a good point. I have the allocator should track removed code in each block and if adding code to a block in which the code has been removed we should issue this barrier. I will look into this, but most likely I will start adding this feature to jit_alloc branch. BTW testing this would be fun as well.

**Comment by jhogberg** [comment]
> @jhogberg That's the point of this discussion to actually design the new API in a way so you would not need to create your own abstraction on top of `VirtMem` - although it's already great that you would do it on top of `VirtMem` and not creating one from scratch :)

Sure, I just wanted you to know that if our requirements place too many strange constraints on the new design, it wouldn't be too much effort to change things on our end.

> I think the allocator should track removed code in each block and if adding code to a block in which the code has been removed we should issue this barrier

The tricky bit is issuing it on all (other) threads that might execute code. MacOS and Windows settle this internally behind their instruction cache flushing APIs, on Linux you can use `sys_membarrier(2)`, but other platforms require help from the user.

**Comment by kobalicek** [comment]
@jhogberg I think one solution to have a cross-platform barrier could be having something like a counter that would be incremented every time something is removed from executable memory and a place where each thread would call something like `VirtMem::maybeSynchronizeBarrier()` (or something nicer) that would compare a global counter with a thread local one and issue that barrier if there is a mismatch (and then update the thread local counter) - however, it's true that this would be on the user to call, not sure if it's user friendly though, however, if there is no way to ask the OS to do that I'm unsure how else this could potentially be solved.

Additionally, if this cannot be solved, we can just forbid removing already allocated code by just marking that place as a waste and releasing the whole mapped block once all functions in that block are removed (but this could be a waste in cases that code is removed, but also stays there).

I think that reviewing the `jit_alloc` branch would be nice, as the only missing thing there is a multiple write scope.

**Comment by jhogberg** [comment]
> however, it's true that this would be on the user to call, not sure if it's user friendly though, however, if there is no way to ask the OS to do that I'm unsure how else this could potentially be solved.

There's no better alternative that I know of, so it's probably best just to bite the bullet. I think having the write functions return an error code to flag this condition would be enough. Thankfully the most popular platforms have syscalls to handle it without manual intervention so most people won't ever see it.

> I think that reviewing the `jit_alloc` branch would be nice, as the only missing thing there is a multiple write scope.

It looks good, though people might want a cheaper write variant that skips the instruction barrier when it's known that it isn't necessary, e.g. changing a `b` or `b.cond` branch target on `aarch64`, which is one of a few alterations that the architecture explicitly allows without barriers (see section `B2.2.5 Concurrent modification ...` in the reference manual if you're curious).

**Comment by kobalicek** [comment]
I have updated the https://github.com/asmjit/asmjit/tree/jit_alloc branch.

Still not sure whether the API is okay, basically it's now possible to control the cache flush via a parameter, and there is now a WriteScope, which is not really doing anything extra at the moment, it's just about designing a sane API at the moment.

I'm still thinking how to model better the `flushInstructionCache()` and `CachePolicy` - in the end this should be configurable whether to flush caches in all threads or whether local flush is okay.

I also thought about an idea of flushing cache before writing to executable memory, in batches. For example, JitAllocator allocates a new block, marks all segments as dirty, and then when allocating memory it would flush in batches, like 4kB, 8kB, 16kB - and then mark these regions as flushed. Then when you again use `JitAllocator::alloc` and it gives you a span which region was already flushed, it would be marked as `NoFlush` (or something smarter) and the writer would know to not flush that one. In theory, if a region of executable memory was flushed, no thread ever executed it afterwards, then it should be safe to write code into it without flushing, right?

**Comment by kobalicek** [comment]
@jhogberg I will be back to this soon.

I think yeah, theoretically CPU can prefetch pages so I guess it would not be safe to do that, which is a pity as with block flushing it would be theoretically pretty fast even if there is a need to do a syscall to propagate the flushing to all threads.

**Comment by jhogberg** [comment]
> But still, I'm not 100% sure, maybe CPUs would only prefetch i-cache lines that are reachable from code - but this is not something I would want to do if there is uncertainty as I really don't like random hard to repro crashes due to this.

I don't think it's a good idea either, even if the processor would restrict instruction prefetching to code that's reachable, there's often data alongside the code (e.g. dispatch/lookup tables) and that being out of date might be bad enough.

**Comment by kobalicek** [comment]
I'm ready to merge `jit_alloc` branch. It's an ABI break, but not source break, so we should slowly move in this direction and see whether this would be a sufficient design or not.

**Comment by kobalicek** [comment]
Jit allocator changes were already merged: https://github.com/asmjit/asmjit/commit/8e2f4de484134605a770101b3e06004461d62350
