### ISSUE TITLE
LAHF issue with x86_64 compiler

### ISSUE THREAD

**Issue by qwsaswq1234** [asmjit/asmjit#412]
Hello,

When using ASMJIT, I encountered an issue with the LAHF instruction.
According to the Intel Software Manual, when using LAHF, the EFLAGS should be loaded into the AH register.
However, when I inspect the result using ASMJIT's Logger, it shows that AL is used instead of AX.
Additionally, when I check the values in memory, I observe the same behavior.

Below is my example code to trigger the issue:

```
  JitRuntime rt;                           // Create a runtime specialized for JIT code execution.
  CodeHolder code;                         // Create a CodeHolder.
  rt._environment.setArch(Arch::kX64);     // Set the target architecture to x64.
  x86::Compiler cc(&code);                 // Create and attach X86Compiler to `code`.
  Zone zone(8 * 1024 * 1024);              // Create a zone to keep all temporary strings.
  void *mem = zone.alloc(8 * 1024 * 1024); // Allocate 8MB of memory from the zone.

  // Skip create log

  Gp Gp_base = cc.newGpq();   // Create a 64-bit general purpose register.
  cc.lea(Gp_base, mem);       // Load the address of `mem` into `Gp_base`.
  Gp tmp_Gpb = cc.newGpb();   // Create a 8-bit general purpose register.
  Gp tmp_Gpw = cc.newGpw();   // Create a 16-bit general purpose register.
  cc.mov(tmp_Gpb, 0x56);      // Move 0x56 into `tmp_Gpb`.
  cc.mov(tmp_Gpw, 0x1234);    // Move 0x1234 into `tmp_Gpw`.
  cc.mov(ptr_16(Gp_base), 0); // Move 0 into `ptr_16(Gp_base)`.
  cc.push(ptr_16(Gp_base));   // Push `ptr_16(Gp_base)` onto the stack.
  cc.popf();                  // Pop stack (= `ptr_16(Gp_base)` = 0) into 16bits of eflags register.
  // ****issue****
  cc.lahf(tmp_Gpb); // Load the flags register into `tmp_Gpb`.
  // ****issue****
  cc.mov(prt_8(Gp_base, 16), tmp_Gpb); // Move `tmp_Gpb` into `prt_8(Gp_base, 16)`.

  // Skip add generated code to runtime & execute
```

Assembly code created by ASMJIT's Logger:

```
  lea rcx, [0x7F317E888040]
  mov al, 0x56
  mov ax, 0x1234
  mov word ptr [rcx], 0
  push word ptr [rcx]
  popf
  lahf al                   ; <--- here should be AH
  mov byte [rcx+0x10], al   ; <--- here should be AH
```

My mem results with initial value 0x74
```
byte offset | value
0x0         | 74747474_74740000
0x8         | 74747474_74747474
0x10        | 74747474_74747434
```

According to the Intel Software Manual, the value at address offset 0x10 should not be 0x34, meaning it should not come from the low byte of tmp_Gpw.

Furthermore, when I use the SAHF instruction, will I also encounter similar error?

**Comment by kobalicek** [comment]
I think this is a bit tricky in this case.

AsmJit doesn't allocate HI register in its register allocator (byte register just really means LO part of it). Thus, to successfully use LAHF, which requires the AH register, just allocate at least a word register and use its hi byte.

```
Gp tmp_Gpb = cc.newGpw().r8Hi();
```

Let me know whether this works for you.

**Comment by qwsaswq1234** [comment]
Hi @kobalicek 

It works very well for me. Thank you for your help.
