### ISSUE TITLE
Return "Segmentation fault" when use std instruction

### ISSUE THREAD

**Issue by nick31072002** [asmjit/asmjit#413]
Hi,

I have problem when use std instruction, when i use std instruction, the linux return "Segmentation fault" error.
Is there anybody could figure out what's going on?

 Here is my code
```
// Signature of the generated function.
typedef void (*MemCpy32)(void);

Error execute_asm()
{
  JitRuntime rt;   // Runtime specialized for JIT code execution.
  CodeHolder code; // Holds code and relocation information.
  rt._environment.setArch(Arch::kX64);
  code.init(rt.environment(), // Initialize code to match the JIT environment.
            rt.cpuFeatures());
  x86::Compiler cc(&code); // Create and attach x86::Compiler to code.

  FuncNode *funcNode = cc.addFunc(FuncSignatureT<void>()); //   Return value - void      (no return value).

  // ==============================================================================================================
  // ==============================================================================================================
  cc.std();  // got error at here
  // ==============================================================================================================
  // ==============================================================================================================

  cc.endFunc();  // End of the function body.
  cc.finalize(); // Translate and assemble the whole 'cc' content.

  // Add the generated code to the runtime.
  MemCpy32 memcpy32;
  Error err = rt.add(&memcpy32, &code);

  // Handle a possible error returned by AsmJit.
  if (err)
    return err;
  // ----> CodeHolder is no longer needed from here and can be destroyed <----
  // Test the generated code.
  memcpy32();
  rt.release(memcpy32);

  return err;
}
```

**Comment by kobalicek** [comment]
Here are my comments:

  1. JitRuntime already provides a properly setup environment, never do `rt._environment.xxx`
  2. Use error handling and make sure there are no errors.
  3. Use logging, creating issues without any kind of log means I cannot really help
  4. I think it's undefined behavior to alter the direction flag in a function and to not change it back

So, I'm not sure whether you have encountered error while executing `cc.std()` or whether you got error after executing the JIT compiled code, please clarify.

**Comment by nick31072002** [comment]
Hi,

I think my error is after executing the JIT compiled code in LINUX OS, but the same code in WIN10 OS is fine.

Here are my description:
1. JitRuntime already provides a properly setup environment, never do rt._environment.xxx
   -> I want to use X64 instruction, but have no idea how to do it.
        After do "rt._environment.setArch(Arch::kX64);", it's working.
2. Use error handling and make sure there are no errors.
    The error handling didn't show error at this scenario.
3. Use logging, creating issues without any kind of log means I cannot really help
    Log in logger file
```
  L1:
  nop
  nop
  nop
  std
  nop
  nop
  nop
  L0:
  ret
```
4. I think it's undefined behavior to alter the direction flag in a function and to not change it back
   Is it means can't use JIT to change CF(direction flag) ?
   I want to test string instrction, so i have to change CF.

**Comment by kobalicek** [comment]
The requirement is that: "The direction flag DF in the %rFLAGS register must be clear (set to "forward" direction) on function entry and return".

If you change DF to 1 and exit from function, you have entered the world of undefined behavior and as you see, it will crash when the first instruction that relies on `DF==0` is executed.

**Comment by nick31072002** [comment]
Thank you for the information about DF, it's helpful for me.
