### ISSUE TITLE
Jmp to label size

### ISSUE THREAD

**Issue by w451** [asmjit/asmjit#414]
Any way to force "jmp(label)" to always be rel32?
Wanting to do this so I can figure out how big a block of code is going to be before compiling.

**Comment by w451** [comment]
Solved with:
label._setSignaturePart<0xFFu << 24>(32);

**Comment by kobalicek** [comment]
That's not the solution - never manipulate signatures this way.

To force rel32 encoding, use long_() prefix:

`assembler.long_().jmp(label);`
