### ISSUE TITLE
How to load the address of a label to a register?

### ISSUE THREAD

**Issue by dawnrs** [asmjit/asmjit#419]
The recommendations in the documentation are as follows:
```C++
void embedData(x86::Assembler& a, const Label& L_Data) {
  x86::Gp addr = a.zax();  // EAX or RAX.
  x86::Gp val = x86::edi;  // Where to store some value...
 
  // Approach 1 - Load the address to register through LEA. This approach
  //              is flexible as the address can be then manipulated, for
  //              example if you have a data array, which would need index.
  a.lea(addr, L_Data);     // Loads the address of the label to EAX or RAX.
  a.mov(val, dword_ptr(addr));

}
```
But it doesn't work. The function `x86::Assembler::lea` is not support the argument with Label type.
The relative source code is as follows:
https://github.com/asmjit/asmjit/blob/7e64eabca49c1a4d2cbfb06e4b9d3987bce7f7b3/src/asmjit/x86/x86emitter.h#L490

So, what should I do to load the address of a label to a register.
Thanks for any help.

**Comment by kobalicek** [comment]
It should be written as `a.lea(addr, x86::ptr(L_Data))`
