### ISSUE TITLE
"memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set"

### ISSUE THREAD

**Issue by jhogberg** [asmjit/asmjit#421]
As reported in https://github.com/erlang/otp/issues/7858 by @licaon-kter, setting execute permissions on a page mapped onto an memfd results in a warning in the system log on recent versions of Linux. `MFD_EXEC` should be set on creation to say that we explicitly want to map executable pages.

**Comment by kobalicek** [comment]
This is a possible quick fix: https://github.com/asmjit/asmjit/commits/vm_memfd_exec

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/asmjit/asmjit/commit/1da9e4d957fc8c48d1eac68c76c1b139b3691a24

I would be happy if I can get a verification that the warning is actually fixed.

**Comment by kobalicek** [comment]
Closing, please reopen if the fix is not working

**Comment by licaon-kter** [comment]
What's the expected ETA for a release containing this?

**Comment by kobalicek** [comment]
You can consider it already released. AsmJit doesn't have traditional releases yet - master branch is the stable one.

**Comment by licaon-kter** [comment]
Yes, no, I mean part of an OTP release :)

**Comment by jhogberg** [comment]
We'll release it in OTP 27 since the risk of this breaking in the near future is zero. "Don't break user space" is central to linux Kernel developers, and changing this would certainly break user space.
