### ISSUE TITLE
Liveness analysis differs in Release mode vs Debug mode

### ISSUE THREAD

**Issue by connorjclark** [asmjit/asmjit#427]
Using the latest commit from main branch. MSVC is 193833133, 64-bit. I'm also forcing a specific environment (I'm working on a regression test that should run equivalently on all platforms):

```cpp
Environment env{};
env._arch = Arch::kX64;
env._platform = Platform::kOSX;
env._platformABI = PlatformABI::kGNU;
env._objectFormat = ObjectFormat::kJIT;
code.init(env);
state.calling_convention = CallConvId::kCDecl;
```

I found a difference in output between Debug and Release builds for my usage of asmjit, and isolated the difference to what seems to be a bug caused by an optimization in MSVC (which may suggest some undefined behavior somewhere). I've not reproduced this for Debug builds (where presumably the optimization does not occur) or on other OSs w/ clang (mac and ubunutu).

The place where the liveness analysis differs in a Release build is during the first-pass of the "generate in/out" stage, the one that recalcs in/out for every block as they are added to the worklist:

https://github.com/asmjit/asmjit/blob/118ae6ced160f68dd142a0d758aa7efb4356196a/src/asmjit/core/rapass.cpp#L907-L911

I have a reproduction that, in the first iteration of this loop, will have a few bits set on Release mode that are not set on Debug mode: some bits in the first block's in state. I've confirmed that the input values are the same in both build modes.

```
LiveOps::recalcInOut(block, numBitWords, true);
// This will abort on Release, but not on Debug. That `C` is the only difference.
if (i == 0 && _pov[0]->liveIn().data()[0] == 0x00C0000000000406) abort();
```

This difference makes the function asm output use _way_ more stack space than when a Debug build does it.

I've run my program under ASAN, and so have ruled out any obvious memory issues that might explain this. I've even unrolled this loop and ran the first iteration outside it, and the result _is different_ than what happens when the loop does the first iteration. This suggested to me that perhaps a compiler optimization plays an important role. The disassembly for the `op<In>`, called by this recalc function, actually used SIMD to do a bunch of the work on the BitWords at once (neat!). If I play "bad programmer" and prevent that optimization:

```
for (uint32_t i = 0; i < n; i++) {
  BitWord before = dst[i];
  BitWord after = Operator::op(before, a[i], b[i], c[i]);
  if(after==123) printf("%d\n", (int)after);

  dst[i] = after;
  changed |= (before ^ after);
}
```

With this, the compiler can't use those SIMD instructions, and the difference between Release and Debug modes goes away.

The reproduction I have right now is not the simplest, and it may only work with my specific version of MSVC. I can try to create a separate reproduction soon - it'll be some effort though, so it'll take me awhile to get that sorted. In the meantime, here's instructions on how to (hopefully) see the same issue:

<details> 
  <summary>repro</summary>

```sh
git clone https://github.com/connorjclark/ZeldaClassic.git
cd ZeldaClassic
git checkout asmjit-liveness-repro

cp src/metadata/*.h.sig src/metadata/sigs/
cmake -B build -S .
```

Add this local modification to build/_deps/asmjit-src/src/asmjit/core/rapass.cpp
in the `for (i = 0; i < numReachableBlocks; i++) {` loop after `LiveOps::recalcInOut`.

```cpp
if (i == 0 && _pov[0]->liveIn().data()[0] == 0x00C0000000000406) abort();
```
```sh
cmake --build build --config Release -t zplayer
cmake --build build --config Debug -t zplayer

# This should abort before anything is rendered to the screen.
cd build/Release
./zplayer.exe -replay ../../tmp-folder/playground_prime.zplay -jit -jit-env-test -jit-threads 0 -jit-precompile -frame 0


# This should not abort.
cd build/Debug
./zplayer.exe -replay ../../tmp-folder/playground_prime.zplay -jit -jit-env-test -jit-threads 0 -jit-precompile -frame 0
```

</details>

**Comment by kobalicek** [comment]
@connorjclark I'm not sure whether it would be possible, but are you able to run the project with ASAN, UBSAN, and MSAN (separately) on Linux? This would be really helpful to see if anything shows up (these tools are used on CI so AsmJit builds are clean at least considering the tests asmjit has).

I can try the repro on Windows, but I will be only able to fully test this over the weekend, hope that's fine.

**Comment by kobalicek** [comment]
BTW the alignment issue should show in UBSAN, if it's misaligned, it would report that. I hope it's the alignment as that would be the easiest thing to fix.

**Comment by kobalicek** [comment]
I have checked that out and I think the bit-word data is properly aligned. Still not ruling it out, but `ZoneAllocator` aligns everything to 32 bytes. Most likely this would be something else.

**Comment by kobalicek** [comment]
Yeah this indeed looks like a bug in MSVC.

**Comment by kobalicek** [comment]
Actually it looks more like a bug in MSVC. I will try to repro it over the weekend.

**Comment by kobalicek** [comment]
Wow thanks a lot for taking the time to repro it, I will watch this.

**Comment by kobalicek** [comment]
I'm still thinking about workarounding this for MSVC case as I don't expect everybody would be compiling asmjit with updated compilers - the only thing is I haven't found a good workaround. Maybe #ifdef and disabling autovectorization in that loop is indeed the best idea. But honestly I don't trust MSVC at all after this as it could screw any bit operation basically.

**Comment by kobalicek** [comment]
@connorjclark Would you be able to test `issue_427_workaround` branch and verify it's working?

**Comment by kobalicek** [comment]
I'm not sure I trust MS that much, but yeah I think it makes sense to do a version check as well.

**Comment by kobalicek** [comment]
Okay, thank's again for your time trying to repro this issue and filling a MSVC bug!

Fixed by https://github.com/asmjit/asmjit/commit/bfa0bf690c2e90cc0844f2f012efa41b916bde7e
