### ISSUE TITLE
calling names when use call instruction

### ISSUE THREAD

**Issue by paule32** [asmjit/asmjit#428]
Hello,
Is it possible to give names for the "call" instruction instead program internal offset number's ?
When it is possible, how can I do this ?

**Comment by kobalicek** [comment]
I think you would have to elaborate why that would be necessary. If you want to keep track about what is happening, you can always use an inline comment, which would display the name as a comment, however, if you are calling a function with absolute address, then there is no "name" replacement or anything like that. And AsmJit will not lookup symbols, that's something outside of scope of AsmJit.

There are named labels that can be used, but that would have to be bound (so the function would be emitted as well).

**Comment by kobalicek** [comment]
Closing, please reopen if you have further questions.
