### ISSUE TITLE
Are the generated ISA databases still in the public domain?

### ISSUE THREAD

**Issue by mehrdadn** [asmjit/asmjit#429]
### Details

Hi there, the old asmdb was (quite generously) in the [public domain](https://github.com/asmjit/asmdb/blob/7d2fe069597e67f1881240290985d22e9c28b145/LICENSE.md). However, ever since the database was moved into asmjit, it seems to have implicitly inherited asmjit's license. I wasn't sure if this was intentional or unintentional, so I thought I'd ask whether it would be possible to keep the ISA databases in the public domain? Thank you.

**Comment by kobalicek** [comment]
Thanks for pointing this out!

I think it indeed inherited the Zlib license with the merge of these two projects. So I'm gonna mark it dual licensed under Zlib and public domain, free of choice.

**Comment by mehrdadn** [comment]
Amazing! Thank you!

**Comment by kobalicek** [comment]
Closing as resolved by https://github.com/asmjit/asmjit/commit/9e39b1e81447e0e4367479ead02b546feca787c1
