### ISSUE TITLE
[BUG] jmp far & call far (FF25 00000000 ptr & FF15 02000000 ptr)

### ISSUE THREAD

**Issue by kkptm** [asmjit/asmjit#433]
### Issue Description

x86assembler.cpp->
...
          if (Environment::is64Bit(arch()) && x86IsJmpOrCall(instId)) {
              __int64 ofst = abs((__int64)jumpAddress - (__int64)re->_sourceOffset);
              if (jumpAddress & 0xFFFFFFFF00000000 && !(ofst > INT_MIN && ofst < INT_MAX))
              {
                  if (instId == Inst::kIdJmp)
                  {
                      writer.emit16uLE(0x25FF);
                      writer.emit32uLE(0);
                      writer.emit32uLE(jumpAddress);
                      writer.emit32uLE(jumpAddress >> 32);
                      goto EmitDone;
                  }
                  else if (instId == Inst::kIdCall)
                  {
                      writer.emit16uLE(0x15FF);
                      writer.emit32uLE(2);
                      writer.emit16uLE(0x08EB);
                      writer.emit32uLE(jumpAddress);
                      writer.emit32uLE(jumpAddress >> 32);
                      goto EmitDone;
                  }
              }
It would have been easy to fix the BUG, but since I didn't study the library in detail, I'm Posting what I found here

**Comment by kobalicek** [comment]
Can you please elaborate?

I don't see a bug anywhere right now. AsmJit assembles far jumps as other assemblers via `ljmp` and `lcall` instructions.

**Comment by kkptm** [comment]
Assembler assembler;
	    CodeHolder asmcode;
	    asmcode.reset();
	    asmcode.init(asmjit::Environment(Arch::kX64), 0);
	    asmcode.attach(&assembler);
	    assembler.addDiagnosticOptions(asmjit::DiagnosticOptions::kValidateAssembler);
	    {
		    assembler.jmp(0xA123456789);
		    assembler.call(0xA123456789);
	    }
	    asmjit::String encodedOpcode;
	    asmjit::Section* text = asmcode.textSection();
	    text->buffer()[0];
	    encodedOpcode.appendHex(text->data(), text->bufferSize());
	    printf(encodedOpcode.data());
it outputs:
40 E9 00000000
40 E8 00000000

**Comment by kkptm** [comment]
the correct absolute address jump in 64-bit programs should be:
FF25 00 00 00 00 [64bit address]
and absolute address call:
FF15 02 00 00 00 [64bit address]

**Comment by kobalicek** [comment]
FF25/FF15 encodes `jmp|call r64/m64` forms - you can have that if you use `jmp [mem]` form of the instruction. When you specify absolute address as an immediate AsmJit bails to relative encoding and in some cases it would output a relocable code so it can patch it later.

In your case there is REX prefix so it can patch the instruction to FFxx form later when relative addressing would be out of reach.

**Comment by kkptm** [comment]
so it is

**Comment by kobalicek** [comment]
I'm going to clarify this.

The instruction sequences proposed are not instructions, but they are instructions or multiple instructions + data. To do a jump with absolute address that is stored next to the jump, you can simply do:

```c++
Label L = assembler->newLabel();
assembler->jmp(x86::mem(L));
assembler->dq(uint64_t(address));
```

Alternatively, without a label with RIP addressing:

```c++
assembler->jmp(x86::ptr(x86::rip));
assembler->dq(uint64_t(address));
```

The thing is that I don't want to create a macro-assembler from AsmJit as that would be much more confusing than just offering what the target ISA offers.

**Comment by kobalicek** [comment]
Closing as the behavior of AsmJit is OK.
