### ISSUE TITLE
The correctness question of InstInfo for sub and sub instructions

### ISSUE THREAD

**Issue by Bri1987** [asmjit/asmjit#434]
### Details

In _instInfoTable in a64instdb.cpp , I notice that Inst Add, Adds, Sub, Subs are all belong to struct BaseAddSub, but their 'RW Info' are different. Inst Add and Adds are kRWI_W , but Inst Sub and Subs are kRWI_X. I wonder why Inst Sub and Subs are KRWI_X ?

The reason for raising this question is that we encountered a problem while using InstAPI:: queryRWInfo. We want to use it to help determine the legitimacy of an assembly program. However, when encountering Sub and Subs instructions, the first operand (i.e. the destination register) shows that its flag is both readable and writable, which affects our judgment. We thought its information could only be isWrite() is true but not be isRead() is also true. And we notice Add instruction won't be this, so we wonder why.

**Comment by ZehMatt** [comment]
Why do you assume its not read? In order to subtract or add two values it has to be read.

**Comment by Bri1987** [comment]
Oh Thank you so much!
