### ISSUE TITLE
linker giving error when using the library.

### ISSUE THREAD

**Issue by UserNotfoundR** [asmjit/asmjit#437]
### Issue Description

![image](https://github.com/asmjit/asmjit/assets/128847349/ae1bc22a-84d3-46d3-a095-a59e20422165)
No matter the compiler, the error is always the same. And I don't know why it happens. Just in case, I'll leave the my code below.
```
#include <C:\Users\RieidiGamer\Desktop\Novapasta\asmjit\src\asmjit\asmjit.h>
#include <iostream>
#include <vector>

// Função para converter e exibir o código de máquina
void convert_and_display_machine_code(asmjit::CodeHolder& code) {
    asmjit::Section* section = code.textSection();
    const uint8_t* codeData = section->data();
    size_t codeSize = section->realSize();

    // Exibir o código de máquina em hexadecimal
    for (size_t i = 0; i < codeSize; i++) {
        printf("%02X ", codeData[i]);
    }
    printf("\n");
}

void convert_add(asmjit::x86::Assembler& a, int val1, int val2) { 
    a.mov(asmjit::x86::rax, val1); 
    a.add(asmjit::x86::rax, val2); 
}

void convert_sub(asmjit::x86::Assembler& a, int val1, int val2) { 
    a.mov(asmjit::x86::rax, val1); 
    a.sub(asmjit::x86::rax, val2); 
}

void convert_div(asmjit::x86::Assembler& a, int val1, int val2) { 
    a.mov(asmjit::x86::rax, val1); 
    a.mov(asmjit::x86::rbx, val2); 
    a.cqo(); // Sign-extend rax into rdx:rax for division
    a.idiv(asmjit::x86::rbx); 
}

void convert_mul(asmjit::x86::Assembler& a, int val1, int val2) { 
    a.mov(asmjit::x86::rax, val1); 
    a.mov(asmjit::x86::rbx, val2); 
    a.imul(asmjit::x86::rax, asmjit::x86::rbx); 
}

typedef void (*conversion_func)(asmjit::x86::Assembler&, int, int);

int main() {
    char op;
    int val1, val2;

    std::cout << "Digite a expressão (por exemplo, '25 + 2'): ";
    std::cin >> val1 >> op >> val2;

    conversion_func conversion_table[] = {
        convert_add,
        convert_sub,
        convert_div,
        convert_mul
    };

    int opcode = -1;
    switch (op) {
        case '+': opcode = 0; break;
        case '-': opcode = 1; break;
        case '/': opcode = 2; break;
        case '*': opcode = 3; break;
        default: std::cout << "Operador inválido\n"; return 1;
    }

    // Setup do ASMJIT
    asmjit::JitRuntime rt;
    asmjit::CodeHolder code;
    code.init(rt.environment());
    asmjit::x86::Assembler a(&code);

    // Converter a instrução
    if (opcode != -1) {
        conversion_func func = conversion_table[opcode];
        func(a, val1, val2);

        // Finalizar e exibir o código de máquina
        a.finalize();
        convert_and_display_machine_code(code);
    } else {
        std::cout << "Operador inválido\n";
        return 1;
    }

    return 0;
}
```

**Comment by kobalicek** [comment]
Unresolved symbols. I hope the documentation statement is enough in this case:

  - https://asmjit.com/doc/group__asmjit__build.html

Projects that use AsmJit statically must define [ASMJIT_STATIC](https://asmjit.com/doc/group__asmjit__build.html#gabcd1a6399d893d32c3bc5c8419c7a694) in all compilation units that use AsmJit, otherwise AsmJit would use dynamic library imports in [ASMJIT_API](https://asmjit.com/doc/group__asmjit__core.html#ga52f7f1d75697b2d155eaa0d2a83ddb82) decorator. The recommendation is to define this macro across the whole project that uses AsmJit this way.

**Comment by UserNotfoundR** [comment]
![image](https://github.com/asmjit/asmjit/assets/128847349/fea304b7-9ef1-4c90-84c7-51a4a7de0d14)
It was not...

**Comment by kobalicek** [comment]
Of course this won't work - if you use asmjit, you have to either link to it or embed it in your project.

**Comment by UserNotfoundR** [comment]
How do I link asmjit?

**Comment by UserNotfoundR** [comment]
I have no idea how to incorporate or Link AsmJIT never used before

**Comment by kobalicek** [comment]
If you have no idea about this stuff the best thing is to create a new project and setup the stuff there. I would recommend using cmake, setting a cmake variable `ASMJIT_EMBED` to `TRUE`, including asmjit's CMakeLists.txt from it, and adding `asmjit::asmjit` as a dependency to your target (executable).

I cannot think about anything simpler than this.

If you want to use command line like this, you have to build asmjit first, and then to use command line to link to it (clang's `-l` and `L` options for linking, and `I` for include paths).

**Comment by UserNotfoundR** [comment]
Thank you, I understand. Now I have a question: does asmjit directly support assembly code? Literally to "mov rax 10" or is there already a function that can convert the assembly to this "IR"?

**Comment by kobalicek** [comment]
I hope the documentation can give you an answer to the question, just start here to explore the API:

  - https://asmjit.com/doc/classasmjit_1_1x86_1_1Assembler.html

AsmJit's purpose is to assemble code, so yeah it offers API that accepts instruction + operands and can encode it to machine code. It offers much more, but this is where I would start to explore the library and its possibilities.

**Comment by UserNotfoundR** [comment]
É que eu tenho um código de máquina que é literalmente o printf e aí ele tem mais de 200 linhas e fica difícil fica fazendo assim: ```a.mov(asmjit::x86::rbx, val2);```
