### ISSUE TITLE
JitAllocator alloc method

### ISSUE THREAD

**Issue by RCECoder** [asmjit/asmjit#439]
### Details

In the Explicit Code Relocation example here:
https://asmjit.com/doc/group__asmjit__core.html

The line 
void* p = allocator.[alloc](https://asmjit.com/doc/classasmjit_1_1JitAllocator.html#a4be1c94241d2a41541f2b59e9d907f2d)(estimatedSize);

Has errors

> error C2661: 'asmjit::_abi_1_13::JitAllocator::alloc': no overloaded function takes 1 arguments
> error C2440: 'initializing': cannot convert from 'asmjit::_abi_1_13::Error' to 'void *'

Are these examples not updated to the latest version?

**Comment by kobalicek** [comment]
It's possible some parts are out of sync with the code as there is currently no way to verify whether the documentation is correct (at least I don't know how to possibly script this).

I will check it out and fix this one,

**Comment by kobalicek** [comment]
Closed by https://github.com/asmjit/asmjit/commit/f5df7a2b1bd942fc1169d0f563dacbe34e6a11ac
