### ISSUE TITLE
O(N^2) Complexity calling reserve

### ISSUE THREAD

**Issue by J-Richter** [asmjit/asmjit#440]
### Issue Description

`radefs_p.h:nonOverlappingUnionOf()` calls `_data.reserve()` which has no exponential growing strategy. This function is called in a loop from `rapass.cpp`. In a degenerated use-case of mine this `_reserve` is called with 12 byte increments up to around 500kb.

Changing the call from `reserve` to a call to `resize` decreases the runtime from 5 to 2 seconds. Its still slow, but the complexity should be better with this change.

**Comment by kobalicek** [comment]
Ok, I think this is a problem indeed and I will look into it. Thanks for spending your time to find this one!

**Comment by kobalicek** [comment]
BTW if you are generating huge functions it's probably not idea, there is still some work to do to basically allow such stress tests such as here:

  - https://github.com/asmjit/asmjit/pull/431

**Comment by J-Richter** [comment]
I'm planning to split the generated function into multiple. But I first wanted to inverstigate if there is some easy fix. 
Are there any other guidelines on how to design the code so that the register allocator has less to do?

**Comment by kobalicek** [comment]
@J-Richter It would be great if you could confirm the improvement. There are no tests that would verify the complexity of RA at the moment.

**Comment by J-Richter** [comment]
Looks better now! Thanks.
