### ISSUE TITLE
Incompatibility with C++20

### ISSUE THREAD

**Issue by nima-sayadi** [asmjit/asmjit#442]
### Issue Description

When trying to compile our tool, we get the below warnings which indicate that ASMJIT is **not compatible with C++20**

`api-config.h:519:16: warning: template-id not allowed for constructor in C++20`
`api-config.h:519:16: note: remove the <>`
`zone.h:394:3: note: in expansion of macro ASMJIT_NONCOPYABLE`

![IMG_5F5649C5-1541-4EE9-B76F-78D98B117EFB](https://github.com/user-attachments/assets/b426076e-0c7b-4208-9e59-85b0193b2d75)

### Operating System

Linux

### Architecture

Not specified

**Comment by kobalicek** [comment]
Please could you verify whether the issue happens on master?

I cannot repro this. There are C++20 and C++23 runs part of the build matrix on CI and none of them reports any warnings.

**Comment by nima-sayadi** [comment]
Thank you for your quick response.
Apparently, it happens on master.

https://github.com/comsec-group/blacksmith/blob/b1e2a9689408dbe6c1aff736f126d897d3b7ed6f/external/CMakeLists.txt#L20

**Comment by kobalicek** [comment]
I see this in the referenced file:

```
if (BLACKSMITH_ENABLE_JITTING)
    message(STATUS "Fetching external dependency asmjit")
    set(MESSAGE_QUIET OFF)

    FetchContent_Declare(
            asmjit
            GIT_REPOSITORY https://github.com/asmjit/asmjit.git
            GIT_TAG 78de7d9c81a6ad1b0f732b52666960d9be1c6461
    )

    FetchContent_MakeAvailable(asmjit)

    set(MESSAGE_QUIET OFF)
    message(STATUS "Fetching external dependency asmjit -- done!")
endif()
```

Which refers to a commit from 2021:

  - https://github.com/asmjit/asmjit/commit/78de7d9c81a6ad1b0f732b52666960d9be1c6461

So, you should definitely update if you want your issue to be resolved.

**Comment by nima-sayadi** [comment]
Thank you for your response
