### ISSUE TITLE
Duplicate entry in x86 inst db

### ISSUE THREAD

**Issue by Goubermouche** [asmjit/asmjit#443]
### Issue Description

[Master]

Hi, I've skimmed through the asmjit instruction database, and I've found something, which appears to be a duplicate entry for a single instruction: 

the following table:
```
{"category": "VIRTUALIZATION", "volatile": true, "data": [...
```
Appears to contain the same variant of the following instruction twice: 
```
{"inst": "vmmcall", "op": "0F 01 D9" , "ext": "SVM"},
```
Hope this helps.

### Operating System

Not specified / possibly all

### Architecture

X86 / X86_64

**Comment by kobalicek** [comment]
True, one `vmmcall` should be removed, thanks for spotting that out!

**Comment by kobalicek** [comment]
Fixed by https://github.com/asmjit/asmjit/commit/b4a2976458e45b814d2da14fe55c628cd1c27b83

Thanks!
