### ISSUE TITLE
VC++calls the function generated by "asmjit" after optimization is enabled, and an exception occurs

### ISSUE THREAD

**Issue by w4454962** [asmjit/asmjit#445]
### Details

When the optimization level of O2 and above is enabled, calling the agreed function machine code generated by asmjit or calling back the vc++function in the generated machine code will trigger an exception

For example, when I use the ebx register to store pointers in asmjit, ebx is a register that is not easily lost. When I call the strncmp function in asmjit, ebx will be lost. I really don't understand why. Normally, strncmp is a function in runtime, and they will be strictly saved when using ebx according to the agreement. After use, the register will be restored. How could the registers saved by upper level functions be lost?

**Comment by w4454962** [comment]
The problem of losing registers in this interaction disappears when I use o1 or turn off optimization. I can guess that this is related to the compiler's register optimization allocation, but I don't know how to generate safe and callable function machine code while supporting optimization

**Comment by kobalicek** [comment]
If you are generating code for Windows, you have to comply with its ABI. For example:

  - https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention

AsmJit is designed to emit instructions, it doesn't care whether they make sense. It's generally required that AsmJit users know the ABI of the environment they target. You can use AsmJit's Compiler if you want a higher level code generation experience, but it's a trade-off.

**Comment by w4454962** [comment]
OK
