### ISSUE TITLE
Crash on JitRuntime when calling reset() 

### ISSUE THREAD

**Issue by gamagan** [asmjit/asmjit#451]
### Issue Description

The latest version as of today, #[e723962], crashes when calling reset on a newly made JitRuntime.

```
JitRuntime rt;
rt.reset(); // crash
```

A hard reset does not crash:
```
JitRuntime rt;
rt.reset(ResetPolicy::kHard);  // ok
```

### Operating System

Windows

### Architecture

X86 / X86_64

**Comment by kobalicek** [comment]
Fixed by f1096428b87e9d16305de16e91f2a7f52aef5a88 - thanks!
