### ISSUE TITLE
RIP-Relative Addressing and runtime compiling

### ISSUE THREAD

**Issue by gamagan** [asmjit/asmjit#452]
### Details

I'm confused about the use of RIP-Relative Addressing in AsmJit.

In offline assembly, RIP-RA would be used to read the contents of 
a  global variable, like:

`add [g_my_int], eax`

That computes an offset during offline compilation. Also, it can only
be used to access global data (afaik).

In AsmJit, I would accomplish that in this way:
```
asm_.mov(r11, uintptr_t(&g_my_int)); 
asm_.add(dword_ptr(r11), eax);
```

... because the JIT compiling would be done at runtime, so there is
no offset value for "g_my_int" to use; I would use the runtime pointer 
of the global.

As an exercise, I tried using the following and, as I expected, it doesn't work.

`asm_.add(dword_ptr(rip, uintptr_t(&g_my_int)), eax);`

So, what is the actual use of RIP-RA in AsmJit?

**Comment by kobalicek** [comment]
It's to make it possible to use rip retative addressing from user code - for example if you disassemble some code, you don't need label annotations and can still reassemble it correctly if AsmJit provides the right primitives. I'm not saying I have used this form, but it's possible and also compatible with other assemblers that provide this syntax.

**Comment by gamagan** [comment]
>  for example if you disassemble some code, you don't need label annotations and can still reassemble it correctly if AsmJit provides the right primitives.

I don't fully understand what this means. Can you restate that example in a different way?
