### ISSUE TITLE
How to learn about Virtual Registers?

### ISSUE THREAD

**Issue by gamagan** [asmjit/asmjit#453]
### Details

I'm creating AsmJit test-cases for learning the api. One of those test cases is about converting `asmjit::Assembler` code to use `asmjit::Compiler` code. I'm converting the code from Assembler to Compiler as close to 1-to-1 as I can. The code works fine with the Assembler, but it crashes at the Compiler section marked below.

I first tried to solve the problem by looking at the documentation regarding virtual registers. I was hoping to find some info discussing their usage, requirements, constraints, etc. However, I wasn't able to find the data.

Since Virtual Registers are fundamental to working with the Compiler, what's a recommended way to learn about them?

Target function signature:
```
    i32(u32 a, u32 b, u32* c, u32* d)
```

Assembler:
```
    Label invalidCount = asm_.newLabel();

    asm_.xor_(eax, eax);
    asm_.cmp(edx, 31);
    asm_.ja(invalidCount);
    asm_.xchg(ecx, edx);
    asm_.mov(eax, edx);
    asm_.shl(eax, cl);
    asm_.mov(qword_ptr(r8), eax);
    asm_.shr(edx, cl);
    asm_.mov(qword_ptr(r9), edx);
    asm_.mov(eax, 1);
    asm_.bind(invalidCount);
    asm_.ret();
```

Compiler:
```    
    Label invalidCount = cc_.newLabel();

    // Using newUIntPtr based on example code on AsmJit docs.
    Gp ra = cc_.newUIntPtr("a");
    Gp rb = cc_.newUIntPtr("b");
    Gp rc = cc_.newUIntPtr("c");
    Gp rd = cc_.newUIntPtr("d");

    Gp res = cc_.newGpd();

    fun_.setArg(0, ra);
    fun_.setArg(1, rb);
    fun_.setArg(2, rc);
    fun_.setArg(3, rd);

    cc_.xor_(res, res);
    cc_.cmp(rb, 31);
    cc_.ja(invalidCount);
    cc_.xchg(ra, rb);
    cc_.mov(res, rb);     ////////// Crashes here

    // ...

    cc_.bind(invalidCount);
    cc_.ret(res);
```

**Comment by gamagan** [comment]
Btw, for others:

The error was because `Gp res = cc_.newGpd();` creates a 32bit register. It should be `Gp res = cc_.newGpq();`

But, this question is about the virtual register info, not about fixing the error itself.

**Comment by ZehMatt** [comment]
Virtual registers is exactly what it sounds like, virtual registers that just work like the physical registers except that you get way more. My advice would be to read the documentation if you want to learn more about it.

**Comment by gamagan** [comment]
> My advice would be to read the documentation if you want to learn more about it.

Oh, cool. You found documentation for them? I couldn't find it, so I made this post for asking a strategy for learning about them.

Can you please point me to the documentation you found?

**Comment by ZehMatt** [comment]
https://asmjit.com/doc/group__asmjit__compiler.html

**Comment by gamagan** [comment]
x
