### ISSUE TITLE
how can i create asm like "add x1, x1, w1, uxtw" in aarch64 env?

### ISSUE THREAD

**Issue by jwimd** [asmjit/asmjit#454]
### Details

just as the title

**Comment by kobalicek** [comment]
The way to encode it would be:

```assembler->add(x1, x2, w3, uxtw(0))```

However, it seems this combination is not handled in the encoder.

**Comment by kobalicek** [comment]
I'm going to fix this over the weekend.

It's only about the validation and not encoding (the assembler just refuses valid constructs and accepts invalid constructs - it wants both source operands to match in size, which is wrong here).

**Comment by kobalicek** [comment]
Should be fixed by d28c4be2e7fccca665e646617882b18dc8711f6f
