### ISSUE TITLE
Crashes when using idiv and invoke in the same function

### ISSUE THREAD

**Issue by ReneMuala** [asmjit/asmjit#459]
### Details

Greetings, im getting crashed when using invoke and idiv or divss in the same function.
i tried to use cqo, but the Compiler implementation requires params, which the instruction itself does not seem to need.

```c++
    JitRuntime rt;                           // Runtime specialized for JIT code execution.
  CodeHolder code;                         // Holds code and relocation information.

  code.init(rt.environment(),              // Initialize code to match the JIT environment.
            rt.cpuFeatures());
  x86::Compiler cc(&code);  
...
  InvokeNode* invokeNode;                  // Function invocation:
  cc.invoke(&invokeNode,                   //   - InvokeNode (output).
    native,                     //   - Function address or Label.
    FuncSignature::build<void>());     //   - Function signature.
    
  cc.idiv(x, y);                            // <- error.
```

**Comment by kobalicek** [comment]
These instructions have an explicit form, which can be seen like an intrinsic. The compiler needs the inputs/outputs otherwise it would not be able to allocate registers.

So, `cqo` has 2 operands in this case (output, input), like this:

```
  ASMJIT_INST_1x(cbw, Cbw, Gp_AX)                                      // ANY [EXPLICIT] AX      <- Sign Extend AL
  ASMJIT_INST_2x(cdq, Cdq, Gp_EDX, Gp_EAX)                             // ANY [EXPLICIT] EDX:EAX <- Sign Extend EAX
  ASMJIT_INST_1x(cdqe, Cdqe, Gp_EAX)                                   // X64 [EXPLICIT] RAX     <- Sign Extend EAX
  ASMJIT_INST_2x(cqo, Cqo, Gp_RDX, Gp_RAX)                             // X64 [EXPLICIT] RDX:RAX <- Sign Extend RAX
  ASMJIT_INST_2x(cwd, Cwd, Gp_DX, Gp_AX)                               // ANY [EXPLICIT] DX:AX   <- Sign Extend AX
  ASMJIT_INST_1x(cwde, Cwde, Gp_EAX)                                   // ANY [EXPLICIT] EAX     <- Sign Extend AX
```

The same for idiv - you need to use at least 3 operands in this case so the compiler knows the registers:

```
  ASMJIT_INST_2x(idiv, Idiv, Gp, Gp)                                   // ANY [EXPLICIT]  AH[Rem]: AL[Quot] <- AX / r8
  ASMJIT_INST_2x(idiv, Idiv, Gp, Mem)                                  // ANY [EXPLICIT]  AH[Rem]: AL[Quot] <- AX / m8
  ASMJIT_INST_3x(idiv, Idiv, Gp, Gp, Gp)                               // ANY [EXPLICIT] xDX[Rem]:xAX[Quot] <- xDX:xAX / r16|r32|r64
  ASMJIT_INST_3x(idiv, Idiv, Gp, Gp, Mem)                              // ANY [EXPLICIT] xDX[Rem]:xAX[Quot] <- xDX:xAX / m16|m32|m64
```

See x86emitter.h for more details regarding explicit forms.

**Comment by ReneMuala** [comment]
> These instructions have an explicit form, which can be seen like an intrinsic. The compiler needs the inputs/outputs otherwise it would not be able to allocate registers.
> 
> So, `cqo` has 2 operands in this case (output, input), like this:
> 
> ```
>   ASMJIT_INST_1x(cbw, Cbw, Gp_AX)                                      // ANY [EXPLICIT] AX      <- Sign Extend AL
>   ASMJIT_INST_2x(cdq, Cdq, Gp_EDX, Gp_EAX)                             // ANY [EXPLICIT] EDX:EAX <- Sign Extend EAX
>   ASMJIT_INST_1x(cdqe, Cdqe, Gp_EAX)                                   // X64 [EXPLICIT] RAX     <- Sign Extend EAX
>   ASMJIT_INST_2x(cqo, Cqo, Gp_RDX, Gp_RAX)                             // X64 [EXPLICIT] RDX:RAX <- Sign Extend RAX
>   ASMJIT_INST_2x(cwd, Cwd, Gp_DX, Gp_AX)                               // ANY [EXPLICIT] DX:AX   <- Sign Extend AX
>   ASMJIT_INST_1x(cwde, Cwde, Gp_EAX)                                   // ANY [EXPLICIT] EAX     <- Sign Extend AX
> ```
> 
> The same for idiv - you need to use at least 3 operands in this case so the compiler knows the registers:
> 
> ```
>   ASMJIT_INST_2x(idiv, Idiv, Gp, Gp)                                   // ANY [EXPLICIT]  AH[Rem]: AL[Quot] <- AX / r8
>   ASMJIT_INST_2x(idiv, Idiv, Gp, Mem)                                  // ANY [EXPLICIT]  AH[Rem]: AL[Quot] <- AX / m8
>   ASMJIT_INST_3x(idiv, Idiv, Gp, Gp, Gp)                               // ANY [EXPLICIT] xDX[Rem]:xAX[Quot] <- xDX:xAX / r16|r32|r64
>   ASMJIT_INST_3x(idiv, Idiv, Gp, Gp, Mem)                              // ANY [EXPLICIT] xDX[Rem]:xAX[Quot] <- xDX:xAX / m16|m32|m64
> ```
> 
> See x86emitter.h for more details regarding explicit forms.

Thanks for the expanation, i ended up fixing the problem but the program stills crash when i try to perform operations after using the invoke instruction.

for example:
```
 InvokeNode* invokeNode;                  // Function invocation:
  cc.invoke(&invokeNode,                   //   - InvokeNode (output).
    native,                     //   - Function address or Label.
    FuncSignature::build<void>(CallConvId::kStdCall));     //   - Function signature.

  // invokeNode->setArg(0, x);                // Assign x as the first argument.
  // invokeNode->setRet(0, x);                // Assign x as a return value as well.
    auto r = cc.newXmmSs().as<x86::Gp>();
    cc.xor_(r,r);
  cc.idiv(r, x, y); /// <- error here      
 ```
 
 but everything goes fine when i remove the invoke. What could it be?

**Comment by kobalicek** [comment]
I think it's time to turn on logger and error handler, and to turn on instruction validation.

For example this:

```c++
uto r = cc.newXmmSs().as<x86::Gp>();
```

You cannot cast XMM register to GP - that's something that doesn't make sense. Please check out "Recommendations" section here, it should provide all you need to debug these kinds of problems:

  - https://asmjit.com/doc/index.html

**Comment by ReneMuala** [comment]
Thanks!
