### ISSUE TITLE
Structured exception handling

### ISSUE THREAD

**Issue by Nekotekina** [asmjit/asmjit#48]
Hi! I think, there is some issue on Windows x64 that stack cannot be unwinded if an exception occurs in dynamically generated code... And it seems that RtlAddFunctionTable call is needed. I can't catch exceptions using _set_se_translator, and probably it's the reason that MSVC can't display callstack in debugger when entering JIT code.

http://msdn.microsoft.com/ru-ru/library/windows/desktop/ms680588(v=vs.85).aspx

I don't fully understand it, seems it requires some data that is hard to retrieve from X86Compiler...

**Comment by kobalicek** [comment]
I'm not sure whether to keep this open or close. I checked out how it works and it seems that with a little metadata asmjit will be able to generate the tables required for the structured exception handling. But I won't implement this myself.

If there is an interest I would welcome such contribution.

**Comment by Nekotekina** [comment]
Thank you for the research. How that metadata could be retrieved though?

**Comment by roterdam** [comment]
@kobalicek why do you believe RtlInstallFunctionTableCallback is more appropriate?

**Comment by kobalicek** [comment]
I don't have any opinion here. MSDN says `RtlInstallFunctionTableCallback` is more appropriate for JIT generated code, but it's not the only way. I think that users who intend to use exception handling should provide me more information so I can start thinking how this information can be queries from the Compiler.

**Comment by kobalicek** [comment]
I'm closing as I don't see how I can help with this atm.

**Comment by dpjudas** [comment]
For anyone looking for code supporting this, I've created a github gist from my implementation:

https://gist.github.com/dpjudas/925d5c4ffef90bd8114be3b465069fff

It still requires some work to become a real PR for asmjit, but at least this should give anyone a starting point if they want to add direct support.
