### ISSUE TITLE
Add support for opcode selection

### ISSUE THREAD

**Issue by torshie** [asmjit/asmjit#64]
As said in http://stackoverflow.com/questions/19467610/why-does-nasm-use-0x89-when-it-assembles-a-mov-instruction-between-registers , some x86 instructions has two opcodes. asmjit seems to choose different opcodes from what GAS choose.
I need such function in order to control the bytes generated by asmjit, so I can compare the generated bytes to some existing ones.

**Comment by kobalicek** [comment]
I worked on this, it's already implemented in asmjit:next branch, closing. Thanks for suggestion.

**Comment by kobalicek** [comment]
BTW I didn't found a better name than `modmr()`, can still change the option name..
