### ISSUE TITLE
Ability to generate executables / libraries

### ISSUE THREAD

**Issue by kobalicek** [asmjit/asmjit#77]
The following has to be implemented in order to make it possible:
1. Sections
   - asmjit needs to understand sections, this has to go to `asmjit::Assembler`
   - every section should have id, some flags, and it's own buffer
   - changing section should just switch buffers
2. Symbols
   - asmjit needs to understand symbols to be exported / imported
   - symbol should be a label, that has a name and some additional flags (export / import, etc)
3. Runtime - support for making executables / libraries in runtime.
   - runtime should be able to do the rest (generating correct headers for executable / library, etc)

Maybe someone is interested in this and can help, I'm currently not able to implement all of this.

**Comment by kirbyfan64** [comment]
I know that LuaJIT can output binary files; you can read the Lua code that writes the files as an example.

**Comment by ZehM4tt** [comment]
This would make AsmJit a really powerful library especially compilers could be built so easily with this.

**Comment by kobalicek** [comment]
I have already refactored asmjit a bit to make this more feasible to implement.

Adding sections and symbol management should be relatively easy to do.

**Comment by kobalicek** [comment]
Just to update the issue - asmjit:next has already support for sections internally, but it uses only the first section (.text) at the moment. For JIT code-generation I will only allow the first section as it probably doesn't make sense to have more sections, but other targets, I will allow any number of sections, but then the Linker will have work with them and use relocation tables to generate the library.

I think that there are probably more features missing to be able to generate libraries. I have checked nasm and the syntax allows and provides some additional concepts that are used to deal with relocable code. If anyone wants this feature some help would be appreciated :)

**Comment by kobalicek** [comment]
This feature will go to asmtk, maybe we can start a discussion there instead?

**Comment by kobalicek** [comment]
Closing, this feature will be implemented in asmtk instead.
